In [5]:
import sys
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.max_rows", None)

# ======================================================
# CAMINHOS DO PROJETO
# ======================================================

# O notebook está em:
# article_5/src/notebooks/experiments.ipynb

PROJECT_ROOT = Path.cwd().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
DATA_DIR = SRC_DIR / "data"
OUTPUTS_DIR = SRC_DIR / "outputs"

# Garantir que article_5 está disponível para imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_DIR:", DATA_DIR)
print("DATA_DIR existe:", DATA_DIR.exists())

print("\nFicheiros disponíveis:")
for file in sorted(DATA_DIR.iterdir()):
    print("-", file.name)

PROJECT_ROOT: c:\Users\msnev\article_5
DATA_DIR: c:\Users\msnev\article_5\src\data
DATA_DIR existe: True

Ficheiros disponíveis:
- dataframe_hotel_id_week_year_meteo_google_trend.csv
- dataset_sentiment_and_emotion_analysis_year_week.csv
- dataset_sentiment_and_emotion_analysis_year_week_artigo4.csv
- dataset_sentiment_and_emotion_analysis_year_week_artigo4_info_expectation.csv
- dataset_sentiment_and_emotion_analysis_year_week_artigo4_info_expectation_gpt5.csv
- df_info_hotel_ocupacao_kpis_weekly.csv
- hotels_info_extra.csv
- id_hotels_and_info_extra_and_reviews.csv
- reviews_by_hotel_translated.parquet
- translation_checkpoints

In [6]:
# ======================================================
# LEITURA DOS DATASETS
# ======================================================

df_info_hotel_ocupacao_kpis_weekly = pd.read_csv(
    DATA_DIR / "df_info_hotel_ocupacao_kpis_weekly.csv",
    low_memory=False
)

dataset_sentiment_and_emotion_analysis_year_week = pd.read_csv(
    DATA_DIR / "dataset_sentiment_and_emotion_analysis_year_week_artigo4_info_expectation_gpt5.csv",
    low_memory=False
)

dataset_sentiment_and_emotion_analysis_year_week_artigo3 = pd.read_csv(
    DATA_DIR / "dataset_sentiment_and_emotion_analysis_year_week.csv",
    low_memory=False
)

#reviews_by_hotel = pd.read_csv(
#    DATA_DIR / "id_hotels_and_info_extra_and_reviews.csv",
#    low_memory=False
#)
reviews_by_hotel = pd.read_parquet(
    DATA_DIR / "reviews_by_hotel_translated.parquet"
)

info_extra_hotel = pd.read_csv(
    DATA_DIR / "hotels_info_extra.csv",
    sep=";",
    usecols=["nome_hotel_url", "ID_HOTEL"],
    low_memory=False
)

print("KPIs:", df_info_hotel_ocupacao_kpis_weekly.shape)
print("Experiential variables:", dataset_sentiment_and_emotion_analysis_year_week.shape)
print("Sentiment/emotion:", dataset_sentiment_and_emotion_analysis_year_week_artigo3.shape)
print("Reviews:", reviews_by_hotel.shape)
print("Informação dos hotéis:", info_extra_hotel.shape)

KPIs: (58778, 21)
Experiential variables: (41097, 73)
Sentiment/emotion: (41097, 38)
Reviews: (452061, 34)
Informação dos hotéis: (548, 2)

In [7]:
import os
import json
import time
import pandas as pd
from tqdm.auto import tqdm
from openai import OpenAI
from dotenv import load_dotenv

from openai import OpenAI

AZURE_API_KEY = "BYh6Xij0td0cPnTcdbF5Gb4fPCKaqKM0IDxe9ZeVlN49Kk5gZqPjJQQJ99CBACYeBjFXJ3w3AAABACOG7Z9d"

client = OpenAI(
    api_key=AZURE_API_KEY,
    base_url="https://ai-pgbiht.openai.azure.com/openai/v1"
)

MODEL = "gpt-5-mini"

c:\Users\msnev\anaconda3\envs\llama_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Tradução

In [4]:
response = client.responses.create(
    model=MODEL,
    input="Translate to English: Porta do banheiro necessita de manutenção."
)

print(response.output_text)

"The bathroom door needs maintenance."

(Alternative: "The bathroom door needs repair.")

In [5]:
import os
import json
import time
from pathlib import Path

import pandas as pd
from tqdm.auto import tqdm
from openai import OpenAI
from dotenv import load_dotenv


# ============================================================
# CONFIGURAÇÃO
# ============================================================

CHECKPOINT_DIR = Path("../data/translation_checkpoints")
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)


FINAL_OUTPUT_PATH = Path(
    "../data/reviews_by_hotel_translated.parquet"
)


columns_to_translate = [
    "review_text_liked",
    "review_text_disliked",
]


# Começaria com 30.
# Se continuar muito lento, podemos posteriormente otimizar.
batch_size = 15

max_retries = 3


# ============================================================
# FUNÇÕES AUXILIARES
# ============================================================

def clean_text(value):
    """Transforma valores válidos em string limpa."""

    if pd.isna(value):
        return None

    value = str(value).strip()

    if not value:
        return None

    if value.lower() in {"nan", "none"}:
        return None

    return value


def translate_batch_openai(
    texts,
    max_retries=3
):
    """
    Traduz um batch de textos para inglês usando
    Structured Outputs.
    """

    items = [
        {
            "id": i,
            "text": text
        }
        for i, text in enumerate(texts)
    ]

    prompt = f"""
Translate all hotel review texts below into English.

Rules:
- Preserve the original meaning.
- Do not summarize.
- Do not add explanations.
- If the text is already English, return it unchanged.
- Preserve names and proper nouns.
- Return exactly one translation per input item.
- Preserve each id exactly.

Input:
{json.dumps(items, ensure_ascii=False)}
"""

    schema = {
        "type": "object",
        "properties": {
            "translations": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "translation": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "id",
                        "translation"
                    ],
                    "additionalProperties": False
                }
            }
        },
        "required": [
            "translations"
        ],
        "additionalProperties": False
    }

    last_error = None

    for attempt in range(
        1,
        max_retries + 1
    ):

        try:

            response = client.responses.create(
                model=MODEL,
                input=prompt,

                text={
                    "format": {
                        "type": "json_schema",
                        "name": "translation_batch",
                        "schema": schema,
                        "strict": True
                    }
                }
            )

            raw = response.output_text

            if not raw:
                raise ValueError(
                    "Empty response from API."
                )

            result = json.loads(raw)

            result_items = result[
                "translations"
            ]

            translations = {
                int(item["id"]):
                item["translation"]
                for item in result_items
            }

            expected_ids = set(
                range(len(texts))
            )

            received_ids = set(
                translations.keys()
            )

            if received_ids != expected_ids:

                missing = (
                    expected_ids
                    - received_ids
                )

                extra = (
                    received_ids
                    - expected_ids
                )

                raise ValueError(
                    f"Invalid IDs. "
                    f"Missing={sorted(missing)}, "
                    f"Extra={sorted(extra)}"
                )

            return [
                translations[i]
                for i in range(
                    len(texts)
                )
            ]

        except Exception as error:

            last_error = error

            print(
                f"\nTentativa "
                f"{attempt}/{max_retries} "
                f"falhou: {error}"
            )

            if attempt < max_retries:

                wait_time = 5 * attempt

                print(
                    f"Aguardar "
                    f"{wait_time}s..."
                )

                time.sleep(
                    wait_time
                )

    raise RuntimeError(
        "Batch falhou após "
        f"{max_retries} tentativas. "
        f"Último erro: {last_error}"
    )


def translate_individually(text):
    """
    Fallback para quando um batch falha repetidamente.
    """

    try:

        result = translate_batch_openai(
            [text],
            max_retries=2
        )

        return result[0]

    except Exception as error:

        print(
            f"\nFalha individual: {error}"
        )

        return None


def save_checkpoint(
    translation_dict,
    checkpoint_path
):
    """Guarda traduções já realizadas."""

    checkpoint_df = pd.DataFrame(
        {
            "original": list(
                translation_dict.keys()
            ),
            "english": list(
                translation_dict.values()
            )
        }
    )

    checkpoint_df.to_parquet(
        checkpoint_path,
        index=False
    )

In [6]:
# ============================================================
# PREPARAÇÃO DA LÍNGUA
# ============================================================

reviews_by_hotel["original_lang"] = (
    reviews_by_hotel["original_lang"]
    .astype("string")
    .str.lower()
    .str.strip()
)


for column in columns_to_translate:

    print("\n")
    print("=" * 70)
    print(f"COLUNA: {column}")
    print("=" * 70)

    output_column = f"en_{column}"

    checkpoint_path = (
        CHECKPOINT_DIR
        / f"{column}_translations.parquet"
    )

    # ========================================================
    # 1. TEXTOS VÁLIDOS
    # ========================================================

    original_clean = (
        reviews_by_hotel[column]
        .apply(clean_text)
    )

    # ========================================================
    # 2. TEXTOS EM INGLÊS
    # ========================================================

    english_mask = (
        reviews_by_hotel["original_lang"]
        .eq("en")
        & original_clean.notna()
    )

    print(
        f"Reviews em inglês: "
        f"{english_mask.sum():,}"
    )

    # ========================================================
    # 3. CARREGAR CHECKPOINT
    # ========================================================

    if checkpoint_path.exists():

        checkpoint = pd.read_parquet(
            checkpoint_path
        )

        # remover eventuais valores vazios
        checkpoint = checkpoint[
            checkpoint["original"].notna()
            & checkpoint["english"].notna()
        ].copy()

        translation_dict = dict(
            zip(
                checkpoint["original"],
                checkpoint["english"]
            )
        )

        print(
            f"Checkpoint encontrado: "
            f"{len(translation_dict):,} traduções"
        )

    else:

        translation_dict = {}

        print(
            "Nenhum checkpoint anterior encontrado."
        )

    # ========================================================
    # 4. INGLÊS NÃO PRECISA DE API
    # ========================================================

    english_texts = (
        original_clean[
            english_mask
        ]
        .drop_duplicates()
    )

    for text in english_texts:

        translation_dict[text] = text

    print(
        f"Textos ingleses adicionados diretamente: "
        f"{len(english_texts):,}"
    )

    # ========================================================
    # 5. APENAS TEXTOS NÃO INGLESES
    # ========================================================

    non_english_mask = (
        ~reviews_by_hotel["original_lang"].eq("en")
        & original_clean.notna()
    )

    unique_non_english = (
        original_clean[
            non_english_mask
        ]
        .drop_duplicates()
    )

    print(
        f"Textos únicos não ingleses: "
        f"{len(unique_non_english):,}"
    )

    # ========================================================
    # 6. RETIRAR OS QUE JÁ ESTÃO NO CHECKPOINT
    # ========================================================

    texts_to_translate = [
        text
        for text in unique_non_english.tolist()
        if text not in translation_dict
    ]

    print(
        f"Faltam traduzir via API: "
        f"{len(texts_to_translate):,}"
    )

    # ========================================================
    # 7. TRADUÇÃO
    # ========================================================

    failed_texts = []

    total_batches = (
        len(texts_to_translate)
        + batch_size - 1
    ) // batch_size

    for batch_number, i in enumerate(
        tqdm(
            range(
                0,
                len(texts_to_translate),
                batch_size
            ),
            total=total_batches,
            desc=f"Traduzindo {column}"
        ),
        start=1
    ):

        batch = texts_to_translate[
            i:i + batch_size
        ]

        try:

            translated = (
                translate_batch_openai(
                    batch,
                    max_retries=max_retries
                )
            )

            for original, english in zip(
                batch,
                translated
            ):

                if english is not None:

                    english = str(
                        english
                    ).strip()

                    if english:

                        translation_dict[
                            original
                        ] = english

        except Exception as error:

            print(
                f"\nBatch {batch_number} "
                f"falhou definitivamente:"
            )

            print(error)

            print(
                "A tentar os textos "
                "individualmente..."
            )

            # ----------------------------------------------
            # fallback individual
            # ----------------------------------------------

            for text in batch:

                english = (
                    translate_individually(
                        text
                    )
                )

                if english:

                    translation_dict[
                        text
                    ] = english

                else:

                    failed_texts.append(
                        text
                    )

        # ====================================================
        # 8. CHECKPOINT A CADA 10 BATCHES
        # ====================================================

        if batch_number % 10 == 0:

            save_checkpoint(
                translation_dict,
                checkpoint_path
            )

    # ========================================================
    # 9. CHECKPOINT FINAL
    # ========================================================

    save_checkpoint(
        translation_dict,
        checkpoint_path
    )

    # ========================================================
    # 10. MAPEAR PARA O DATAFRAME ORIGINAL
    # ========================================================

    reviews_by_hotel[
        output_column
    ] = (
        original_clean
        .map(translation_dict)
        .astype("string")
    )

    # ========================================================
    # 11. ESTATÍSTICAS
    # ========================================================

    valid_original = (
        original_clean.notna()
    )

    translated_ok = (
        reviews_by_hotel[
            output_column
        ].notna()
        & valid_original
    )

    missing_translation = (
        valid_original
        & reviews_by_hotel[
            output_column
        ].isna()
    )

    print("\nRESULTADO")
    print("-" * 50)

    print(
        f"Textos válidos: "
        f"{valid_original.sum():,}"
    )

    print(
        f"Textos com versão inglesa: "
        f"{translated_ok.sum():,}"
    )

    print(
        f"Textos ainda sem tradução: "
        f"{missing_translation.sum():,}"
    )

    print(
        f"Falhas definitivas nesta execução: "
        f"{len(failed_texts):,}"
    )


# ============================================================
# 12. GUARDAR DATASET COMPLETO
# ============================================================

reviews_by_hotel.to_parquet(
    FINAL_OUTPUT_PATH,
    index=False
)

print("\n")
print("=" * 70)
print("TRADUÇÃO TERMINADA")
print("=" * 70)

print(
    f"Dataset guardado em:\n"
    f"{FINAL_OUTPUT_PATH}"
)

======================================================================
COLUNA: review_text_liked
======================================================================
Reviews em inglês: 47,553
Checkpoint encontrado: 60,230 traduções
Textos ingleses adicionados diretamente: 44,829
Textos únicos não ingleses: 179,713
Faltam traduzir via API: 163,721

Traduzindo review_text_liked:  27%|██▋       | 2943/10915 [14:17:33<46:50:39, 21.15s/it]

Tentativa 1/3 falhou: Unterminated string starting at: line 1 column 1763 (char 1762)
Aguardar 5s...

Tentativa 2/3 falhou: Unterminated string starting at: line 1 column 2008 (char 2007)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 2944 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Traduzindo review_text_liked:  30%|██▉       | 3258/10915 [15:55:08<36:08:16, 16.99s/it]

Tentativa 1/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4659, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4659, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 10s...

Tentativa 3/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4659, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Batch 3259 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4659, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1949, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1949, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1949, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Traduzindo review_text_liked:  33%|███▎      | 3567/10915 [17:32:07<37:13:36, 18.24s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_liked:  51%|█████     | 5521/10915 [27:38:14<26:39:48, 17.80s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_liked:  58%|█████▊    | 6358/10915 [31:49:28<20:03:51, 15.85s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_liked:  71%|███████▏  | 7794/10915 [38:53:38<15:25:51, 17.80s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Traduzindo review_text_liked:  73%|███████▎  | 7963/10915 [39:48:50<17:02:54, 20.79s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 7964 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': True, 'severity': 'medium'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1874, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': True, 'severity': 'medium'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1874, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': True, 'severity': 'medium'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1874, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Traduzindo review_text_liked:  92%|█████████▏| 10091/10915 [52:00:23<4:47:47, 20.96s/it]

Tentativa 1/3 falhou: Invalid IDs. Missing=[14], Extra=[]
Aguardar 5s...

Traduzindo review_text_liked:  96%|█████████▌| 10489/10915 [54:03:05<1:53:41, 16.01s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Unterminated string starting at: line 1 column 1757 (char 1756)
Aguardar 10s...

Tentativa 3/3 falhou: Unterminated string starting at: line 1 column 40 (char 39)

Batch 10490 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Unterminated string starting at: line 1 column 40 (char 39)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_liked: 100%|██████████| 10915/10915 [56:21:37<00:00, 18.59s/it]

RESULTADO
--------------------------------------------------
Textos válidos: 246,932
Textos com versão inglesa: 246,930
Textos ainda sem tradução: 2
Falhas definitivas nesta execução: 2


======================================================================
COLUNA: review_text_disliked
======================================================================
Reviews em inglês: 32,877
Nenhum checkpoint anterior encontrado.
Textos ingleses adicionados diretamente: 27,900
Textos únicos não ingleses: 114,183
Faltam traduzir via API: 113,681

Traduzindo review_text_disliked:   0%|          | 8/7579 [03:14<55:46:14, 26.52s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:   1%|          | 44/7579 [15:33<38:06:52, 18.21s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 45 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2035, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2035, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2035, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Traduzindo review_text_disliked:   7%|▋         | 526/7579 [2:40:15<40:44:59, 20.80s/it]

Tentativa 1/3 falhou: Unterminated string starting at: line 1 column 1794 (char 1793)
Aguardar 5s...

Traduzindo review_text_disliked:   7%|▋         | 541/7579 [2:45:08<42:04:25, 21.52s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 542 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1857, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1857, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1857, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Traduzindo review_text_disliked:   7%|▋         | 548/7579 [2:49:02<42:47:11, 21.91s/it]

Tentativa 1/3 falhou: Unterminated string starting at: line 1 column 1140 (char 1139)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 549 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1927, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1927, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1927, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Traduzindo review_text_disliked:   8%|▊         | 612/7579 [3:13:19<39:46:34, 20.55s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:   8%|▊         | 625/7579 [3:18:23<44:35:48, 23.09s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Traduzindo review_text_disliked:   9%|▊         | 647/7579 [3:26:43<36:48:11, 19.11s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:   9%|▉         | 699/7579 [3:45:13<40:57:33, 21.43s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Unterminated string starting at: line 1 column 40 (char 39)
Aguardar 10s...

Traduzindo review_text_disliked:  19%|█▉        | 1426/7579 [7:40:00<33:19:20, 19.50s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  19%|█▉        | 1434/7579 [7:42:48<33:39:23, 19.72s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  19%|█▉        | 1438/7579 [7:45:00<45:11:05, 26.49s/it]

Tentativa 1/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4409, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4409, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 10s...

Tentativa 3/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4409, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Batch 1439 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4409, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2113, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2113, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2113, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Tentativa 1/2 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/2 falhou: Expecting value: line 1 column 1 (char 0)

Falha individual: Batch falhou após 2 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)

Traduzindo review_text_disliked:  28%|██▊       | 2094/7579 [11:17:47<34:38:18, 22.73s/it]

Tentativa 1/3 falhou: Unterminated string starting at: line 1 column 2371 (char 2370)
Aguardar 5s...

Traduzindo review_text_disliked:  29%|██▉       | 2205/7579 [11:59:37<33:03:14, 22.14s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 2206 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/2 falhou: Expecting value: line 1 column 1 (char 0)

Falha individual: Batch falhou após 2 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)

Traduzindo review_text_disliked:  48%|████▊     | 3629/7579 [20:14:24<16:33:59, 15.10s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  52%|█████▏    | 3929/7579 [21:55:50<19:38:21, 19.37s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Traduzindo review_text_disliked:  53%|█████▎    | 4025/7579 [22:24:24<16:40:50, 16.90s/it]

Tentativa 1/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4001, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4001, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 10s...

Tentativa 3/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4001, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Batch 4026 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4001, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1889, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1889, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 1889, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Traduzindo review_text_disliked:  56%|█████▌    | 4252/7579 [23:33:23<20:01:53, 21.68s/it]

Tentativa 1/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4967, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4967, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 10s...

Tentativa 3/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4967, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Batch 4253 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 4967, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
A tentar os textos individualmente...

Tentativa 1/2 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/2 falhou: Expecting value: line 1 column 1 (char 0)

Falha individual: Batch falhou após 2 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)

Traduzindo review_text_disliked:  58%|█████▊    | 4365/7579 [24:13:35<20:48:45, 23.31s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  60%|██████    | 4566/7579 [25:12:29<18:29:01, 22.08s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting ',' delimiter: line 1 column 3233 (char 3232)
Aguardar 10s...

Tentativa 3/3 falhou: Unterminated string starting at: line 1 column 3503 (char 3502)

Batch 4567 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Unterminated string starting at: line 1 column 3503 (char 3502)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/2 falhou: Expecting value: line 1 column 1 (char 0)

Falha individual: Batch falhou após 2 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)

Traduzindo review_text_disliked:  63%|██████▎   | 4745/7579 [26:12:16<14:14:44, 18.10s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  64%|██████▍   | 4869/7579 [26:51:58<13:43:59, 18.24s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  72%|███████▏  | 5490/7579 [30:01:12<10:57:48, 18.89s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Traduzindo review_text_disliked:  72%|███████▏  | 5494/7579 [30:03:23<14:49:14, 25.59s/it]

Tentativa 1/3 falhou: Connection error.
Aguardar 5s...

Tentativa 2/3 falhou: Connection error.
Aguardar 10s...

Traduzindo review_text_disliked:  75%|███████▌  | 5715/7579 [31:13:16<10:34:21, 20.42s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  77%|███████▋  | 5854/7579 [31:58:09<8:36:24, 17.96s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Unterminated string starting at: line 1 column 1631 (char 1630)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 5855 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  80%|████████  | 6088/7579 [33:13:55<9:56:30, 24.00s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Traduzindo review_text_disliked:  80%|████████  | 6097/7579 [33:18:14<12:26:29, 30.22s/it]

Tentativa 1/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3872, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3872, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 10s...

Tentativa 3/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3872, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Batch 6098 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3872, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
A tentar os textos individualmente...

Tentativa 1/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2227, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/2 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2227, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Falha individual: Batch falhou após 2 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 2227, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Traduzindo review_text_disliked:  90%|████████▉ | 6816/7579 [37:06:16<3:20:07, 15.74s/it]

Tentativa 1/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3870, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 5s...

Tentativa 2/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3870, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
Aguardar 10s...

Tentativa 3/3 falhou: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3870, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}

Batch 6817 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Error code: 400 - {'error': {'message': 'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766', 'type': 'invalid_request_error', 'param': 'prompt', 'code': 'content_filter', 'content_filters': [{'blocked': True, 'source_type': 'prompt', 'content_filter_raw': [], 'content_filter_results': {'hate': {'filtered': True, 'severity': 'medium'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'detected': False, 'filtered': False}}, 'content_filter_offsets': {'start_offset': 0, 'end_offset': 3870, 'check_offset': 0}}], 'innererror': {'code': 'ContentFiltered'}}}
A tentar os textos individualmente...

Traduzindo review_text_disliked:  98%|█████████▊| 7430/7579 [40:24:50<49:04, 19.76s/it]

Tentativa 1/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/3 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 10s...

Tentativa 3/3 falhou: Expecting value: line 1 column 1 (char 0)

Batch 7431 falhou definitivamente:
Batch falhou após 3 tentativas. Último erro: Expecting value: line 1 column 1 (char 0)
A tentar os textos individualmente...

Tentativa 1/2 falhou: Expecting value: line 1 column 1 (char 0)
Aguardar 5s...

Tentativa 2/2 falhou: Unterminated string starting at: line 5 column 22 (char 64)

Falha individual: Batch falhou após 2 tentativas. Último erro: Unterminated string starting at: line 5 column 22 (char 64)

Traduzindo review_text_disliked: 100%|██████████| 7579/7579 [41:13:39<00:00, 19.58s/it]

RESULTADO
--------------------------------------------------
Textos válidos: 168,094
Textos com versão inglesa: 168,083
Textos ainda sem tradução: 11
Falhas definitivas nesta execução: 11


======================================================================
TRADUÇÃO TERMINADA
======================================================================
Dataset guardado em:
..\data\reviews_by_hotel_translated.parquet

In [7]:
# ============================================================
# 1. QUANTOS FICARAM SEM TRADUÇÃO?
# ============================================================

for column in [
    "review_text_liked",
    "review_text_disliked",
]:
    en_column = f"en_{column}"

    valid_original = (
        reviews_by_hotel[column]
        .notna()
        & reviews_by_hotel[column]
        .astype(str)
        .str.strip()
        .ne("")
    )

    missing_translation = (
        valid_original
        & (
            reviews_by_hotel[en_column].isna()
            | reviews_by_hotel[en_column]
            .astype("string")
            .str.strip()
            .eq("")
        )
    )

    print("=" * 60)
    print(column)
    print(f"Textos válidos: {valid_original.sum():,}")
    print(
        f"Traduzidos: "
        f"{(valid_original & ~missing_translation).sum():,}"
    )
    print(
        f"Por traduzir: "
        f"{missing_translation.sum():,}"
    )
    print(
        f"% traduzido: "
        f"{100 * (valid_original & ~missing_translation).sum() / valid_original.sum():.4f}%"
    )

============================================================
review_text_liked
Textos válidos: 246,934
Traduzidos: 246,930
Por traduzir: 4
% traduzido: 99.9984%
============================================================
review_text_disliked
Textos válidos: 168,148
Traduzidos: 168,083
Por traduzir: 65
% traduzido: 99.9613%

In [8]:
missing_rows = []

for column in [
    "review_text_liked",
    "review_text_disliked",
]:
    en_column = f"en_{column}"

    mask = (
        reviews_by_hotel[column].notna()
        & reviews_by_hotel[column]
        .astype(str)
        .str.strip()
        .ne("")
        & (
            reviews_by_hotel[en_column].isna()
            | reviews_by_hotel[en_column]
            .astype("string")
            .str.strip()
            .eq("")
        )
    )

    temp = reviews_by_hotel.loc[
        mask,
        [
            "original_lang",
            column,
            en_column
        ]
    ].copy()

    temp["source_column"] = column

    missing_rows.append(temp)

missing_df = pd.concat(
    missing_rows,
    ignore_index=True
)

display(missing_df)

print(
    "Total de textos ainda sem tradução:",
    len(missing_df)
)

,original_lang,review_text_liked,en_review_text_liked,source_column,review_text_disliked,en_review_text_disliked
0,en-us,none,<NA>,review_text_liked,NaN,<NA>
1,es,"lo que n me gusto ,, fue los grupos de britanicos .. ya que no respetan al resto de los clientes.. son muy incivicos .. y actuan como si estuvieran solos .. ya que la gente tiene el derecho de estar tranquilos ,,",<NA>,review_text_liked,NaN,<NA>
2,en,none,<NA>,review_text_liked,NaN,<NA>
3,pt,Barulho a noite toda. Brasileiros a falar alto as 4 da manhã como se fosse de manhã. Gaveta no quarto com anal plug e vibradores. Nojento,<NA>,review_text_liked,NaN,<NA>
4,en-us,NaN,<NA>,review_text_disliked,none,<NA>
5,pl,NaN,<NA>,review_text_disliked,Otrzymaliśmy inny pokój niż zarezerwowaliśmy. Po interwencji został zmieniony. W pokoju czajnik ale brak kawy i herbaty. Na śniadaniu szału nie ma. Porto Moniz oblegane przez imigrantów łącznie z wejściem do metra - odstraszające wrażenie. Oni tam koczują i załatwiają swoje potrzeby fizjologiczne.,<NA>
6,en,NaN,<NA>,review_text_disliked,none,<NA>
7,en-us,NaN,<NA>,review_text_disliked,none,<NA>
8,en,NaN,<NA>,review_text_disliked,none,<NA>
9,en-us,NaN,<NA>,review_text_disliked,"Location is sketchy, filled with bad immigrants. However, it was close to the city center and we didn’t have any issues.",<NA>
10,es,NaN,<NA>,review_text_disliked,"La mujer de la recepción no era muy agradable. Aunque el hotel está bastante céntrico , justo esta zona está llena de inmigrantes y mendigos. No corresponde el precio para la zona donde está",<NA>
11,en,NaN,<NA>,review_text_disliked,none,<NA>
12,en-us,NaN,<NA>,review_text_disliked,none,<NA>
13,en-us,NaN,<NA>,review_text_disliked,none,<NA>
14,en-us,NaN,<NA>,review_text_disliked,none,<NA>
15,en,NaN,<NA>,review_text_disliked,none,<NA>
16,pt-br,NaN,<NA>,review_text_disliked,"Ultimamente nas ultima estadias estou meio desapontado com a quantidade de arabes e marroquinos, nada contra, mas parece que eles nao respeitam as outras pessoas que estao no quarto, acendem cigarros, falam ao telefone a noite toda, falam muito alto entre eles, nao deixam o restante das pessoas dormirem, depois de um dia longo de viagem, a gente fica desapontado com o local",<NA>
17,es,NaN,<NA>,review_text_disliked,Estaba lleno de extranjeros sin papeles desubicados todos. Era un aguantadero de árabes que vivían ahí y se tornó difícil. Los baños son mixtos y eso está muy mal sobre todo en ese ambiente tan machista,<NA>
18,de,NaN,<NA>,review_text_disliked,none,<NA>
19,en-us,NaN,<NA>,review_text_disliked,none,<NA>
20,en,NaN,<NA>,review_text_disliked,none,<NA>
21,en,NaN,<NA>,review_text_disliked,none,<NA>
22,en,NaN,<NA>,review_text_disliked,none,<NA>
23,en-us,NaN,<NA>,review_text_disliked,none,<NA>
24,en-us,NaN,<NA>,review_text_disliked,none,<NA>
25,en-us,NaN,<NA>,review_text_disliked,none,<NA>
26,en-us,NaN,<NA>,review_text_disliked,none,<NA>
27,fr,NaN,<NA>,review_text_disliked,Le non respect de ma demande initiale. Avais signalé que j étais 1 personne à mobilité réduite. Nombreuses marches (36) avant d atteindre le seul ascenseur et encore d autres marches pour accéder à la chambre (9). Baignoire très haute alors que douche avait été confirmée (accès impossible). En résumé : à fuir pour les personnes handicapées.,<NA>
28,en-us,NaN,<NA>,review_text_disliked,none,<NA>
29,en-us,NaN,<NA>,review_text_disliked,none,<NA>
30,en-us,NaN,<NA>,review_text_disliked,none,<NA>
31,en,NaN,<NA>,review_text_disliked,none,<NA>
32,en-us,NaN,<NA>,review_text_disliked,none,<NA>
33,en,NaN,<NA>,review_text_disliked,none,<NA>
34,en-us,NaN,<NA>,review_text_disliked,none,<NA>
35,en,NaN,<NA>,review_text_disliked,none,<NA>
36,en,NaN,<NA>,review_text_disliked,none,<NA>
37,en,NaN,<NA>,review_text_disliked,none,<NA>
38,en-us,NaN,<NA>,review_text_disliked,none,<NA>
39,en-us,NaN,<NA>,review_text_disliked,none,<NA>
40,fr,NaN,<NA>,review_text_disliked,"Ce qui dommage pour ce séjour, un bus de chinois très bruyants et malsain élèves. Nuit pas reposante car les chinois ont fait du bruit tard dans la nuit",<NA>
41,en,NaN,<NA>,review_text_disliked,none,<NA>
42,en-us,NaN,<NA>,review_text_disliked,none,<NA>
43,en,NaN,<NA>,review_text_disliked,none,<NA>
44,fr,NaN,<NA>,review_text_disliked,Beaucoup d anglais buvaient et étaient soûls dès 16h. Ils étaient bruyants. Il faudrait le préciser que la ville est réservée à une population anglaise qui passe ses journées dans des pubs à boire et faire du bruit. L odeur de nourriture provenant des restaurants trop proches de l hôtel est très désagréable,<NA>
45,en,NaN,<NA>,review_text_disliked,none,<NA>
46,en-us,NaN,<NA>,review_text_disliked,none,<NA>
47,pt,NaN,<NA>,review_text_disliked,"Muita coisa inconcebível para os padrões dos Hotéis actuais. Principalmente a forma robótica como fomos tratados na recepção por uma Senhora da qual não sabemos o nome mas podemos dizer que estava a trabalhar no dia 28 Abril 2025 às 22h. Uma Senhora altamente arrogante que não se mostrou minimamente interessada em tentar resolver simples questões e dúvidas apresentadas por nós. Tratamento tão robótico e tão tóxico que nos fez nem desfrutar do segundo dia do quarto que pagamos. Claro que o hotel não teve culpa do famoso apagão, como não se consegue também compreender o porquê de só o Hotel às 22:15 ser o único local na zona sem luz externa. Não existiu uma única tentativa da parte do hotel em tentar compensar o facto de ainda termos chegado ao nosso quarto e não conseguiamos sequer nos vislumbrar sem a presença das lanternas dos Tlms. Decidimos vir embora, obviamente. E fomos recebidos na receção com um lindo sorriso hipócrita e de desprezo da famosa Senhora recepcionista,, mesmo a Senhora em questão sabendo que ainda tínhamos mais uma noite para pernoitar e um pequeno almoço também já pago. Depois temos a questão do famoso espumante prometido por alguém do Booking, visto tratar-se de uma noite de nupcias e qual a nossa surpresa o famoso espumante não se encontrava no quarto. Até esse pormenor, simples e banal a Senhora da recepção desprezou e desvalorizou. Conclusão. Não foi uma boa estadia. Não guardamos boas recordações e referências do local. Típico Hotel Português onde os Portugueses são tratados com verdadeiro desprezo. Ficava muito bem, o hotel ter tentado de alguma forma compensar o problema do famoso apagão, porque se o Hotel não teve culpa nenhuma, o Cliente de certeza esse é que não teve, e pagou por algo que não desfrutou. Hotel de 4 ⭐ com mentalidade de local bem mais pequenino e sem nível.",<NA>
48,en,NaN,<NA>,review_text_disliked,none,<NA>
49,en,NaN,<NA>,review_text_disliked,none,<NA>
50,en-us,NaN,<NA>,review_text_disliked,none,<NA>
51,en,NaN,<NA>,review_text_disliked,none,<NA>
52,en,NaN,<NA>,review_text_disliked,none,<NA>
53,en-us,NaN,<NA>,review_text_disliked,none,<NA>
54,en-us,NaN,<NA>,review_text_disliked,none,<NA>
55,en-us,NaN,<NA>,review_text_disliked,none,<NA>
56,en,NaN,<NA>,review_text_disliked,none,<NA>
57,en-us,NaN,<NA>,review_text_disliked,none,<NA>
58,fr,NaN,<NA>,review_text_disliked,"Hormis la femme à l’accueil qui est souriante, agréable et serviable, il y a un gros problème avec les femmes de ménage qui n’ont pas vraiment de respect pour les personnes qui souhaitent dormir un peu… Ménage très tôt et beaucoup de bruit, elles parlent très fort, et lorsque on leur demande de faire attention, on se fait limite engueu… Le manque d’isolation phonique, donc le bruit des communs, des voisins, des salles de bains, et de la rue pourtant pas très passante, car pas de volet.",<NA>
59,en-us,NaN,<NA>,review_text_disliked,none,<NA>
60,zh-tw,NaN,<NA>,review_text_disliked,none,<NA>
61,en,NaN,<NA>,review_text_disliked,none,<NA>
62,en-us,NaN,<NA>,review_text_disliked,none,<NA>
63,en-us,NaN,<NA>,review_text_disliked,none,<NA>
64,en,NaN,<NA>,review_text_disliked,none,<NA>
65,en-us,NaN,<NA>,review_text_disliked,none,<NA>
66,en,NaN,<NA>,review_text_disliked,none,<NA>
67,es,NaN,<NA>,review_text_disliked,"Lo peor que sólo una planta en un edificio,las demás plantas son otros negocios, no hay asistencia de perosnal por las noches, nos toco arriba algún tipo de burdel de mujeres de sexo y no pudimos dormir nada en toda la noche,no pararon hasta las 8:00 am, se escuchaban porrazos y gritos toda la noche de forma exagerada,no es recomendable ir a este hostal,no podiamos avisar a nadie porque tampoco había asistencia personal arriba, nos arruinó nuestra estancia en Lisboa, nos tuvimos que ir a España para poder dormir al día siguiente y perder todo el día.No recomendado. Muy caro para ser hostal y no tener baño propio.",<NA>
68,en,NaN,<NA>,review_text_disliked,none,<NA>

Total de textos ainda sem tradução: 69

In [9]:
sample_liked = (
    reviews_by_hotel[
        reviews_by_hotel["original_lang"].ne("en")
        & reviews_by_hotel["review_text_liked"].notna()
        & reviews_by_hotel["en_review_text_liked"].notna()
    ][
        [
            "original_lang",
            "review_text_liked",
            "en_review_text_liked"
        ]
    ]
    .sample(
        n=20,
        random_state=42
    )
)

display(sample_liked)

,original_lang,review_text_liked,en_review_text_liked
230482,es,Personal agradable. Restaurante y limpieza,Nice staff. Restaurant and cleanliness
414958,pt,Da localização,The location.
278155,pt,O tamanho da cama,The size of the bed.
102892,en-us,"It was very safety, and clean a place I love the definition of go back💯","It was very safety, and clean a place I love the definition of go back💯"
290071,he,"הבריכה , ארוחת בוקר","The pool, breakfast"
186538,es,Todo excelente,Everything excellent
54497,en-us,"Great location, very central and close to Metro.","Great location, very central and close to Metro."
110658,fr,Petit déjeuner un peu répétitif,Breakfast a bit repetitive
26774,fr,super petit déjeuner et personnel très gentil ! Magnifique ambiance d’époque dans l’hôtel.,Great breakfast and very kind staff! Magnificent period ambiance in the hotel.
166192,en-us,"Good, but we expected mote typical Portuguese food","Good, but we expected mote typical Portuguese food"
102007,fr,"La propreté, la sympathie du personnel toujours attentif, les petits déjeuners très variés, l'attention portée à l'anniversaire de mon époux avec la surprise d'une bouteille de vin et un petit gâteau. La proximité de la station de métro.","Cleanliness, the friendliness of the always attentive staff, the very varied breakfasts, the attention paid to my husband's birthday with the surprise of a bottle of wine and a small cake. The proximity of the metro station."
221684,pt,"Gostei da localização, perto do centro da cidade. Do pequeno almoço, do quarto mas é pena ter carpete e do facto de ter parqueamento.","I liked the location, near the city center. I liked the breakfast and the room, but it's a pity it has carpet; I also liked the fact that it has parking."
91785,es,"La ubicación, muy cerca de una estación de metro y un parking donde dejar el coche. Calle tranquila, sin mucho tráfico, con comercios y restaurantes donde comimos muy bien. El hotel tiene instalaciones modernas y renovadas, la habitación no muy grande pero confortable para una sola persona y con una pequeña terraza.","The location: very close to a metro station and a parking lot to leave the car. Quiet street with little traffic, with shops and restaurants where we ate very well. The hotel has modern, renovated facilities; the room is not very large but comfortable for one person and has a small terrace."
210755,pt-br,"Local bonito, instalação aconchegante, bom café da manhã.","Beautiful location, cozy accommodation, good breakfast."
133869,es,Me ponían agua y café todos los días,They provided water and coffee every day.
339751,en-us,it was very clean and the host so nica and comprehensive.,it was very clean and the host so nica and comprehensive.
78130,pt-br,"Da cortina nas camas, dava mais privacidade.",Curtains on the beds would give more privacy.
57747,nl,de ligging en het matras,the location and the mattress
295120,en-us,The bed was very comfortable. The staff exceptionally helpful. The spa was clean and very well equipped. The breakfast was plentiful.,The bed was very comfortable. The staff exceptionally helpful. The spa was clean and very well equipped. The breakfast was plentiful.
261600,nl,"Locatie is prima, midden in het centrum je kan alles te voet doen. Lekker op de rooftop nog even chillen.","Location is great, right in the center you can do everything on foot. Nice to chill for a bit on the rooftop."

In [10]:
sample_disliked = (
    reviews_by_hotel[
        reviews_by_hotel["original_lang"].ne("en")
        & reviews_by_hotel["review_text_disliked"].notna()
        & reviews_by_hotel["en_review_text_disliked"].notna()
    ][
        [
            "original_lang",
            "review_text_disliked",
            "en_review_text_disliked"
        ]
    ]
    .sample(
        n=20,
        random_state=42
    )
)

display(sample_disliked)

,original_lang,review_text_disliked,en_review_text_disliked
91684,de,Kleines Zimmer,Small room.
58292,en-us,"Not the best location in and of itself. Close to public transportation, though, and within easy walking distance of the Parque Eduardo VII and Jardim Botânico (botanical gardens). Uber between the main bus station and to the airport was very affordable at <€10. Some discrepancies in the advertised amenities like no restaurant on property outside of breakfast and some of the rooms aren't yet updated.","Not the best location in and of itself. Close to public transportation, though, and within easy walking distance of the Parque Eduardo VII and Jardim Botânico (botanical gardens). Uber between the main bus station and to the airport was very affordable at <€10. Some discrepancies in the advertised amenities like no restaurant on property outside of breakfast and some of the rooms aren't yet updated."
429248,pt,"Na altura de tomar banho, não consegui ter água quente e esperei bastante tempo. Passado um tempo consegui ter água quente no lavatório.","When it was time to shower, I couldn't get hot water and waited a long time. After a while I managed to get hot water in the washbasin."
57460,es,Que no tuviera un baño en la habitación,That it didn't have a bathroom in the room.
302470,en-us,the communication with the spa was basically non-existent. Every time we went down to the spa to book a massage no one was there and it said to send an email. We sent an email and they booked us a 3pm appt. We got there at 250p and no one ever showed up. They emailed us at 320pm saying they were running 10 mins late (already 20 mins late) and then by 330 still never showed up and we had to leave so never got our massage. it was pretty unprofessional in my opinion.,the communication with the spa was basically non-existent. Every time we went down to the spa to book a massage no one was there and it said to send an email. We sent an email and they booked us a 3pm appt. We got there at 250p and no one ever showed up. They emailed us at 320pm saying they were running 10 mins late (already 20 mins late) and then by 330 still never showed up and we had to leave so never got our massage. it was pretty unprofessional in my opinion.
225138,pt-br,pequena e sem vista,Small and without a view.
397381,pt,"A apontar será mesmo o acesso ao alojamento, que na altura que viajei estava um pouco degradado, sendo uma estrada de terra batida poderia estar com uma melhor manutençao.","The only thing to note is the access to the accommodation, which when I traveled was somewhat degraded; being a dirt road it could use better maintenance."
200925,it,Arredamento troppo essenziale e un po’ datato,Furnishings are too basic and a bit dated.
246367,fr,"Le réseau d'eau, faible pression.",The water supply had low pressure.
43715,de,"Die Sauberkeit unseres Zimmers lies sehr zu wünschen übrig. Es begann gleich bei unserer Ankunft, über dem Toiletten Deckel war zwar ein Papierbogen angebracht, der die erfolgte Reinigung vermitteln sollte. Als ich den Deckel jedoch öffnete, musste ich feststellen, dass die Toilette voll Kot war. 🤮. Danach fanden wir noch ein fremdes Haar in der Dusche. Bei der Reklamation an der Rezeption wurde zwar wieder eine Reinigungsfrau ins Zimmer entsandt, jedoch ist dieser Vorfall eigentlich nicht zu tolerieren. Weiter wurde uns nur ein Zahnputzbecher ins Bad gestellt und erst bei zweimaliger Reklamation, einer zweiter gegeben. Am letzten Tag bekamen wir keine zwei kleine Handtücher mehr aufs Zimmer und mussten diese wiederum bei der Rezeption abholen.","The cleanliness of our room left much to be desired. It began right at our arrival: a paper sheet was placed over the toilet lid to indicate it had been cleaned. However, when I opened the lid I found that the toilet was full of feces. 🤮 After that we also found a foreign hair in the shower. When we complained at reception another cleaning lady was sent to the room, but this incident is really unacceptable. Furthermore, only one toothbrush cup was placed in the bathroom and only after complaining twice was a second one given. On the last day we did not get two small towels in the room and had to collect them at reception."
436659,nl,Die vrouw daar was ook slecht,That woman there was also bad.
109220,en-us,Can’t think of a thing!,Can’t think of a thing!
362690,pt,O local,O local
344192,de,"Ausstattung der Küche könnte besser sein, z.B. hat eine Kaffeemaschine gefehlt. Frühstück könnte abwechslungsreicher sein. Man bestellt am Vortag was man gerne essen würde. Wenn man längere Zeit in dem Hotel ist, wird das Frühstück eintönig.","The kitchen equipment could be better, e.g., a coffee machine was missing. Breakfast could be more varied. You order the day before what you would like to eat. If you stay in the hotel for a longer time, the breakfast becomes monotonous."
114394,en-us,"The hallways were not well lit, especially the stairwells. I'm all for creating an ambience, but there also has to be safety in mind. Also, I noticed one of the carpet rods on the staircase was completely loose and it became a tripping hazard...I had to push it aside in order to not risk falling down the stairs. I also did not like not having a phone inside the bedroom. It made contacting the front desk a hassle, especially being in a separate building. Finally, and I know not much can be done about this, is the noise from the street. I was in room 1.3, so the street noise was very loud, even with windows closed. Maybe creating a sound barrier of sorts would be helpful.","The hallways were not well lit, especially the stairwells. I'm all for creating an ambience, but there also has to be safety in mind. Also, I noticed one of the carpet rods on the staircase was completely loose and it became a tripping hazard...I had to push it aside in order to not risk falling down the stairs. I also did not like not having a phone inside the bedroom. It made contacting the front desk a hassle, especially being in a separate building. Finally, and I know not much can be done about this, is the noise from the street. I was in room 1.3, so the street noise was very loud, even with windows closed. Maybe creating a sound barrier of sorts would be helpful."
190699,pt,Podia ter uma oferta maior de produtos no pequeno almoço,There could be a wider selection of items at breakfast.
142907,es,Nada,Nada
370386,sk,Nemam ziadne vyhrady voci tomuto ubytovaniu.,I have no complaints about this accommodation.
320983,es,"Que no había enchufes en las mesitas de noche, para poder cargar los móviles mientras los usas, me pareció algo que bajó puntos a este hotel, a pesar de todas las demás cosas buenas.","The fact that there were no sockets in the bedside tables to charge phones while using them seemed to me to lower this hotel's rating, despite all the other good things."
211922,pt,"Porta da entrada do quarto não funcionava, fomos colocados num quarto melhor mas a ter de disponibilizar mais dinheiro. Falta de papel higiénico no quarto, teve de ser solicitado.",The room's entrance door did not work; we were moved to a better room but had to pay extra. There was no toilet paper in the room; it had to be requested.

In [11]:
error_pattern = (
    r"Error 500|Server Error|"
    r"That's an error|That’s an error|"
    r"Please try again later"
)

for col in [
    "en_review_text_liked",
    "en_review_text_disliked"
]:
    bad = (
        reviews_by_hotel[col]
        .astype("string")
        .str.contains(
            error_pattern,
            case=False,
            na=False,
            regex=True
        )
    )

    print(
        f"{col}: "
        f"{bad.sum():,} traduções suspeitas"
    )

en_review_text_liked: 0 traduções suspeitas
en_review_text_disliked: 0 traduções suspeitas

In [12]:
audit = reviews_by_hotel[
    reviews_by_hotel["review_text_disliked"].notna()
    & reviews_by_hotel["en_review_text_disliked"].notna()
].copy()

audit["original_len"] = (
    audit["review_text_disliked"]
    .astype(str)
    .str.len()
)

audit["translation_len"] = (
    audit["en_review_text_disliked"]
    .astype(str)
    .str.len()
)

audit["length_ratio"] = (
    audit["translation_len"]
    / audit["original_len"].replace(0, pd.NA)
)

display(
    audit[
        [
            "original_lang",
            "review_text_disliked",
            "en_review_text_disliked",
            "length_ratio"
        ]
    ]
    .sort_values("length_ratio")
    .head(20)
)

,original_lang,review_text_disliked,en_review_text_disliked,length_ratio
444487,pt-br,academia ginástica,gym,0.166667
285411,el,"Λόγω του ξύλινου δαπέδου ακούγεται το τρίξιμο όποτε περπατήσει κάποιος. Βέβαια, αυτό ειναι αναπόφευκτο και συνηθίζεται εύκολα Debido al suelo de madera, se puede oír el crujido cada vez que alguien camina. Por supuesto, esto es inevitable y es fácil acostumbrarse. Because of the wooden floor, you can hear the creak whenever someone walks. Of course, this is inevitable and easy to get used to","Because of the wooden floor, you can hear the creak whenever someone walks. Of course, this is inevitable and easy to get used to.",0.329949
250772,es,Las hormigas,Ants,0.333333
326447,de,Ein bisschen in die Jahre gekommen.,A bit dated.,0.342857
57867,fr,????? je me demande bien !,I wonder!,0.346154
291747,fr,Changement de serviettes de toilettes,Towel change.,0.351351
89968,pt,Estacionamento com pagamento extra,Paid parking,0.352941
54891,hu,Nincs ilyen,None,0.363636
155867,pt,alimentação,Food,0.363636
154668,pt,Alimentação,Food,0.363636
211421,hu,Nincs ilyen,None,0.363636
207511,nl,Uitsluitend,Only,0.363636
67584,hu,Nincs ilyen,None,0.363636
176407,pt-br,sem sala de esporte,No gym.,0.368421
218958,pt-br,Academia,Gym,0.375000
283418,es,Gimnasio,Gym,0.375000
143136,pt-br,Academia,Gym,0.375000
119975,pt-br,Custo do parque de estacionamento.,Parking cost.,0.382353
18235,it,Dimensioni della camera,Room size,0.391304
149862,es,tamaño de la habitacion,room size,0.391304

In [ ]:
reviews_by_hotel[
    [
        "original_lang",
        "review_text_liked",
        "en_review_text_liked",
        "review_text_disliked",
        "en_review_text_disliked",
        "full_review",
        "en_full_review"
    ]
].head(3).T

## Code - Dev

In [8]:
reviews_by_hotel.head(3)

,Unnamed: 0,nome_hotel_url,username,user_country,room_view,stay_duration,stay_type,review_post_date,review_title,rating,original_lang,review_text_liked,review_text_disliked,full_review,en_full_review,found_helpful,found_unhelpful,owner_resp_text,ID_HOTEL,ID_LOCAL,NUTS2,N_ROOMS,NAME,booking_url,obtained_reviews,hotel?,stars,amenities,principais_comodidades,day,month,year,en_review_text_liked,en_review_text_disliked
0,0,hotelmundial,Hiroyuki,Japan,Double or Twin Room,3 nights,Couple,04-30-2025 00:00:00,Very good,8.0,ja,レンタカーが故障した時に、レンタカー会社とポルトガル語で交渉してくれるなど親切な対応をしてくれて、とても助かりました。,None,title: Very good. liked: レンタカーが故障した時に、レンタカー会社とポルトガル語で交渉してくれるなど親切な対応をしてくれて、とても助かりました。.,None,0,0,None,149,Lisboa,Grande Lisboa,349,Hotel Mundial,https://www.booking.com/hotel/pt/hotelmundial.html,sim,yes,4.0,None,"Estacionamento privado, Acesso Wi-Fi gratuito, Transfer (aeroporto), Quartos familiares, Quartos para não fumadores, Restaurante, Receção disponível 24 horas, Comodidades para pessoas com mobilidade condicionada, Bar, Muito bom pequeno-almoço",30,4,2025,"When our rental car broke down, they kindly helped us by negotiating with the rental company in Portuguese, which was very helpful.",<NA>
1,1,hotelmundial,Helen,Hong Kong,Double or Twin Room,3 nights,Couple,04-30-2025 00:00:00,We had a very good stay and were impressed by the professionalism of the staff.,9.0,en,Location was excellent. The staff were friendly and helpful.,More variety of food at breakfast.,title: We had a very good stay and were impressed by the professionalism of the staff. liked: Location was excellent. The staff were friendly and helpful. disliked: More variety of food at breakfast.,title: We had a very good stay and were impressed by the professionalism of the staff. liked: Location was excellent. The staff were friendly and helpful. disliked: More variety of food at breakfast.,0,0,None,149,Lisboa,Grande Lisboa,349,Hotel Mundial,https://www.booking.com/hotel/pt/hotelmundial.html,sim,yes,4.0,None,"Estacionamento privado, Acesso Wi-Fi gratuito, Transfer (aeroporto), Quartos familiares, Quartos para não fumadores, Restaurante, Receção disponível 24 horas, Comodidades para pessoas com mobilidade condicionada, Bar, Muito bom pequeno-almoço",30,4,2025,Location was excellent. The staff were friendly and helpful.,More variety of food at breakfast.
2,2,hotelmundial,Uwe,Germany,Double or Twin Room,3 nights,Couple,04-30-2025 00:00:00,Kommen gerne wieder!,9.0,de,Besonders gefallen hat uns die zentrale Lage. Sehr gute Erreichbarkeit des öffentlichen Nahverkehrs. Die berühmte Tram 28 und 12 fahren nur wenige Meter vorm Hotel ab. Gleich um die Ecke sind die Haltestellen der Sightseeing Busse. Frühstück war super. Personal hilfsbereit und freundlich.,Nichts,title: Kommen gerne wieder! liked: Besonders gefallen hat uns die zentrale Lage. Sehr gute Erreichbarkeit des öffentlichen Nahverkehrs. Die berühmte Tram 28 und 12 fahren nur wenige Meter vorm Hotel ab. Gleich um die Ecke sind die Haltestellen der Sightseeing Busse. Frühstück war super. Personal hilfsbereit und freundlich. disliked: Nichts.,None,0,0,None,149,Lisboa,Grande Lisboa,349,Hotel Mundial,https://www.booking.com/hotel/pt/hotelmundial.html,sim,yes,4.0,None,"Estacionamento privado, Acesso Wi-Fi gratuito, Transfer (aeroporto), Quartos familiares, Quartos para não fumadores, Restaurante, Receção disponível 24 horas, Comodidades para pessoas com mobilidade condicionada, Bar, Muito bom pequeno-almoço",30,4,2025,We particularly liked the central location. Very good accessibility of public transport. The famous trams 28 and 12 depart just a few meters in front of the hotel. The sightseeing bus stops are just around the corner. Breakfast was great. Staff helpful and friendly.,Nichts

In [9]:
# ======================================================
# NORMALIZAÇÃO DOS NOMES DAS COLUNAS
# ======================================================

datasets_weekly = [
    df_info_hotel_ocupacao_kpis_weekly,
    dataset_sentiment_and_emotion_analysis_year_week,
    dataset_sentiment_and_emotion_analysis_year_week_artigo3,
]

for dataset in datasets_weekly:
    dataset.columns = (
        dataset.columns
        .str.strip()
        .str.upper()
    )

reviews_by_hotel.columns = reviews_by_hotel.columns.str.strip()
info_extra_hotel.columns = info_extra_hotel.columns.str.strip()


# ======================================================
# NORMALIZAÇÃO DE WEEK_YEAR
# ======================================================

df_info_hotel_ocupacao_kpis_weekly = (
    df_info_hotel_ocupacao_kpis_weekly
    .rename(columns={"YEAR_WEEK": "WEEK_YEAR"})
)


def normalize_week_year(series):
    """
    Converte formatos como:
    2024-01
    2024_01
    2024-W01
    2024_W01

    para:
    2024_W01
    """
    return (
        series.astype("string")
        .str.strip()
        .str.replace("-", "_", regex=False)
        .str.replace(r"^(\d{4})_(\d{1,2})$", r"\1_W\2", regex=True)
        .str.replace(r"^(\d{4})_W(\d)$", r"\1_W0\2", regex=True)
    )


for dataset in datasets_weekly:
    if "WEEK_YEAR" in dataset.columns:
        dataset["WEEK_YEAR"] = normalize_week_year(dataset["WEEK_YEAR"])


# Garantir que ID_HOTEL tem o mesmo tipo em todos os datasets
for dataset in datasets_weekly:
    if "ID_HOTEL" in dataset.columns:
        dataset["ID_HOTEL"] = pd.to_numeric(
            dataset["ID_HOTEL"],
            errors="coerce"
        ).astype("Int64")


reviews_by_hotel["ID_HOTEL"] = pd.to_numeric(
    reviews_by_hotel["ID_HOTEL"],
    errors="coerce"
).astype("Int64")

info_extra_hotel["ID_HOTEL"] = pd.to_numeric(
    info_extra_hotel["ID_HOTEL"],
    errors="coerce"
).astype("Int64")

df_info_hotel_ocupacao_kpis_weekly["WEEK_YEAR"] = (
    df_info_hotel_ocupacao_kpis_weekly["WEEK_YEAR"]
    .astype(str)
    .str.strip()
    .str.replace("-", "_", regex=False)
)

df_info_hotel_ocupacao_kpis_weekly["WEEK_YEAR"] = (
    df_info_hotel_ocupacao_kpis_weekly["WEEK_YEAR"]
    .str.replace(
        r"^(\d{4})_(\d{1,2})$",
        lambda m: f"{m.group(1)}_W{int(m.group(2)):02d}",
        regex=True
    )
)

In [10]:
df_info_hotel_ocupacao_kpis_weekly.tail(3)

,UNNAMED: 0,ID_HOTEL,WEEK_YEAR,QUARTOS_OCUPADOS,ID_LOCAL,NUTS2,N_ROOMS,NAME,BOOKING_URL,NOME_HOTEL_URL,OBTAINED_REVIEWS,HOTEL?,STARS,AMENITIES,PRINCIPAIS_COMODIDADES,QUARTOS_DISPONIVEIS,TAXA_OCUPACAO,N_ROOMS_OCCUPIED_WEEK,REVPAR_WEEK,REVPOR_WEEK,TREVPAR_WEEK
58775,58775,197,2021_W23,7,Leiria,Centro (PT),16,Most Art Boutique Hostel,https://www.booking.com/hotel/pt/most-art-boutique-hostel.html,most-art-boutique-hostel,sim,yes,NaN,NaN,"Estacionamento gratuito, Acesso Wi-Fi gratuito, Quartos familiares, Quartos para não fumadores, Comodidades para pessoas com mobilidade condicionada, Transfer (aeroporto), Comodidades para fazer chá e café em todos os quartos",112,6.250000,NaN,NaN,NaN,NaN
58776,58776,101,2022_W03,2,AlcobaÃ§a,Oeste e Vale do Tejo,23,Albergaria SÃ£o Pedro,https://www.booking.com/hotel/pt/albergaria-sao-pedro.html,albergaria-sao-pedro,sim,yes,NaN,NaN,"Acesso Wi-Fi gratuito, Frente à praia, Quartos familiares, Transfer (aeroporto), Serviço de quartos, Quartos para não fumadores, Bar, Excecional pequeno-almoço",161,1.242236,3.0,2.666122,40.880533,2.666122
58777,58777,122,2023_W18,6,Albufeira,Algarve,8,Balaia Plaza AL,https://www.booking.com/hotel/pt/balaia-plaza-al.html,balaia-plaza-al,sim,yes,NaN,"O espaço é todo seu, 74 m² tamanho, Cozinha, Jardim, Piscina, Máquina de lavar roupa, Acesso Wi-Fi gratuito, Terraço, Varanda, Estacionamento gratuito","Piscina exterior, Estacionamento gratuito, Acesso Wi-Fi gratuito, Quartos para não fumadores, Terraço, Jardim, Ar condicionado",56,10.714286,6.0,13.679250,109.434000,13.679250

In [11]:
# ======================================================
# REMOVER COLUNAS REPETIDAS DO DATASET DO ARTIGO 3
# ======================================================

cols_repetidas = [
    "DOMINANT_EMOTION",
    "EMOTION_ENTROPY",
    "N_REVIEWS",
    "SENTIMENT_SCORE_AVG",
    "SENTIMENT_SCORE_STD",
]

dataset_sentiment_and_emotion_analysis_year_week_artigo3 = (
    dataset_sentiment_and_emotion_analysis_year_week_artigo3
    .drop(columns=cols_repetidas, errors="ignore")
)


# ======================================================
# CONSTRUIR DATASET FINAL
# ======================================================

df_final = (
    df_info_hotel_ocupacao_kpis_weekly
    .merge(
        dataset_sentiment_and_emotion_analysis_year_week,
        on=["ID_HOTEL", "WEEK_YEAR"],
        how="left",
        validate="one_to_one",
    )
    .merge(
        dataset_sentiment_and_emotion_analysis_year_week_artigo3,
        on=["ID_HOTEL", "WEEK_YEAR"],
        how="left",
        validate="one_to_one",
    )
)

In [12]:
df_final.count()

UNNAMED: 0_x                             58778
ID_HOTEL                                 58778
WEEK_YEAR                                58778
QUARTOS_OCUPADOS                         58778
ID_LOCAL                                 58778
NUTS2                                    58778
N_ROOMS                                  58778
NAME                                     58778
BOOKING_URL                              58778
NOME_HOTEL_URL                           58778
OBTAINED_REVIEWS                         58778
HOTEL?                                   58778
STARS                                    38113
AMENITIES                                 5973
PRINCIPAIS_COMODIDADES                   58778
QUARTOS_DISPONIVEIS                      58778
TAXA_OCUPACAO                            58778
N_ROOMS_OCCUPIED_WEEK                    39575
REVPAR_WEEK                              39539
REVPOR_WEEK                              39539
TREVPAR_WEEK                             39539
N_REVIEWS                                36122
AVG_RATING                               36122
RATING_STD                               32412
EXPECTATION_INTENSITY_AVG                36122
EXPERIENCE_INTENSITY_AVG                 36122
EXPECTATION_SENTIMENT_AVG                21665
EXPERIENCE_SENTIMENT_AVG                 33020
EXPECTATION_EXPERIENCE_GAP_AVG           33030
SEMANTIC_ALIGNMENT_SCORE_AVG             33030
SEMANTIC_MISALIGNMENT_SCORE_AVG          33030
EXPECTATION_EXPERIENCE_GAP_STD           27295
SEMANTIC_MISALIGNMENT_SCORE_STD          27295
EXPECTATION_TOPICS_LIST                  36122
EXPERIENCE_TOPICS_LIST                   36122
VIOLATED_EXPECTATION_TOPICS_LIST         36122
CONFIRMED_EXPECTATION_TOPICS_LIST        36122
LATENT_EXPECTATION_TOPICS_LIST           36122
EXPECTATION_TOPICS_UNIQUE                36122
EXPERIENCE_TOPICS_UNIQUE                 36122
VIOLATED_EXPECTATION_TOPICS_UNIQUE       36122
CONFIRMED_EXPECTATION_TOPICS_UNIQUE      36122
LATENT_EXPECTATION_TOPICS_UNIQUE         36122
N_EXPECTATION_TOPICS                     36122
N_EXPERIENCE_TOPICS                      36122
N_VIOLATED_EXPECTATION_TOPICS            36122
N_CONFIRMED_EXPECTATION_TOPICS           36122
N_LATENT_EXPECTATION_TOPICS              36122
N_REVIEWS_WITH_EXPECTATION               36122
N_REVIEWS_WITH_VIOLATED_EXPECTATION      36122
EXPECTATION_COVERAGE                     36122
VIOLATION_COVERAGE                       36122
EXPECTATION_VIOLATION_RATIO              21651
EXPECTATION_SHARE                        36122
HIGH_EXPECTATION_SHARE                   36122
HIGH_ALIGNMENT_SHARE                     36122
HIGH_MISALIGNMENT_SHARE                  36122
DOMINANT_EXPECTATION_EXPERIENCE_LABEL    36122
EXPERIENCE_ONLY_SHARE                    36122
MINOR_MISALIGNMENT_SHARE                 36122
MODERATE_MISALIGNMENT_SHARE              36122
MAJOR_MISALIGNMENT_SHARE                 36122
UNCLEAR_SHARE                            36122
EMOTION_ENTROPY                          33030
DOMINANT_EMOTION                         33030
SENTIMENT_SCORE_AVG                      33030
SENTIMENT_SCORE_STD                      30902
EXPECTATION_EXPERIENCE_GAP_AVG_LAG1      32775
EXPECTATION_EXPERIENCE_GAP_AVG_ROLL4     35997
SEMANTIC_MISALIGNMENT_SCORE_AVG_LAG1     32775
SEMANTIC_MISALIGNMENT_SCORE_AVG_ROLL4    35997
EXPECTATION_VIOLATION_RATIO_LAG1         21520
EXPECTATION_VIOLATION_RATIO_ROLL4        32028
MAJOR_MISALIGNMENT_SHARE_LAG1            35860
MAJOR_MISALIGNMENT_SHARE_ROLL4           36122
EMOTION_ENTROPY_LAG1                     32775
EMOTION_ENTROPY_ROLL4                    35997
SENTIMENT_SCORE_AVG_LAG1                 32775
SENTIMENT_SCORE_AVG_ROLL4                35997
EXPECTATION_SHARE_LAG1                   35860
EXPECTATION_SHARE_ROLL4                  36122
HIGH_EXPECTATION_SHARE_LAG1              35860
HIGH_EXPECTATION_SHARE_ROLL4             36122
HIGH_ALIGNMENT_SHARE_LAG1                35860
HIGH_ALIGNMENT_SHARE_ROLL4               36122
HIGH_MISALIGNMENT_SHARE_LAG1             35860
HIGH_MISALIGNMENT_SHARE_ROLL4            36122
HIGH_MISALIGNMENT                        33030
HIGH_EXPECTATION                         36122
HIGH_EMOTIONAL_COMPLEXITY                33030
HIGH_EXPECTATION_VIOLATION               21651
HIGH_POSITIVE_EXPERIENCE                 33020
UNNAMED: 0_y                             36122
N_REVIEWS_POSITIVE                       36122
N_REVIEWS_NEGATIVE                       36122
PERC_REVIEWS_POSITIVE                    36122
PERC_REVIEWS_NEGATIVE                    36122
AVG_REVIEW_LENGTH_POS                    36122
AVG_REVIEW_LENGTH_NEG                    36122
TOTAL_REVIEW_LENGTH_MEAN                 36122
TOTAL_REVIEW_LENGTH_STD                  32413
%EXTREME_RATINGS_1                       36122
%EXTREME_RATINGS_10                      36122
AVG_REVIEW_RATING                        36122
MEDIAN_REVIEW_RATING                     36122
RATING_DISPERSION                        32412
NEGATIVE_TO_POSITIVE_RATIO               35949
SEASON_FLAG                              36122
PERC_NEUTRAL_REVIEWS                     36122
N_DISTINCT_TOPICS                        36122
TOPIC_CONCENTRATION_INDEX                33026
PERC_OPERATIONAL_COMPLAINTS              27057
PERC_STRUCTURAL_PRAISE                   31745
PERC_PRICE_VALUE_MENTIONS                36122
EMERGING_NEGATIVE_TOPIC                  36122
POLARIZATION_INDEX                       36122
PRIORITY_ALERT_FLAG                      36122
REVIEWER_ORIGIN_DIVERSITY                36122
COMPLEXITY_INDEX                         33026
DELTA_SENTIMENT_VS_PREV_WEEK             30457
DELTA_NUM_REVIEWS_VS_PREV_WEEK           35860
ROLLING_AVG_SENTIMENT_4W                 35997
SENTIMENT_TREND_SLOPE                    36122
dtype: int64

In [13]:

# Remover colunas criadas automaticamente na exportação dos CSV
unnamed_cols = [
    col for col in df_final.columns
    if col.upper().startswith("UNNAMED:")
]

df_final = df_final.drop(columns=unnamed_cols, errors="ignore")


# Filtrar o período de análise
df_final = df_final[
    df_final["WEEK_YEAR"].between("2023_W01", "2024_W52")
].copy()


def parse_week_year(value):
    if pd.isna(value):
        return pd.NaT

    try:
        year, week = str(value).split("_W")
        return pd.Timestamp.fromisocalendar(
            int(year),
            int(week),
            1,
        )
    except (ValueError, TypeError):
        return pd.NaT


df_final["WEEK_DATE"] = df_final["WEEK_YEAR"].apply(parse_week_year)

df_final = (
    df_final
    .dropna(subset=["ID_HOTEL", "WEEK_YEAR", "WEEK_DATE"])
    .sort_values(["ID_HOTEL", "WEEK_DATE"])
    .drop_duplicates(subset=["ID_HOTEL", "WEEK_YEAR"])
    .reset_index(drop=True)
)

print("Dimensão do painel:", df_final.shape)
print("Hotéis:", df_final["ID_HOTEL"].nunique())
print("Período:", df_final["WEEK_DATE"].min(), "a", df_final["WEEK_DATE"].max())

Dimensão do painel: (28845, 122)
Hotéis: 329
Período: 2023-01-02 00:00:00 a 2024-12-23 00:00:00

In [14]:
df_final.head(3)

,ID_HOTEL,WEEK_YEAR,QUARTOS_OCUPADOS,ID_LOCAL,NUTS2,N_ROOMS,NAME,BOOKING_URL,NOME_HOTEL_URL,OBTAINED_REVIEWS,HOTEL?,STARS,AMENITIES,PRINCIPAIS_COMODIDADES,QUARTOS_DISPONIVEIS,TAXA_OCUPACAO,N_ROOMS_OCCUPIED_WEEK,REVPAR_WEEK,REVPOR_WEEK,TREVPAR_WEEK,N_REVIEWS,AVG_RATING,RATING_STD,EXPECTATION_INTENSITY_AVG,EXPERIENCE_INTENSITY_AVG,EXPECTATION_SENTIMENT_AVG,EXPERIENCE_SENTIMENT_AVG,EXPECTATION_EXPERIENCE_GAP_AVG,SEMANTIC_ALIGNMENT_SCORE_AVG,SEMANTIC_MISALIGNMENT_SCORE_AVG,EXPECTATION_EXPERIENCE_GAP_STD,SEMANTIC_MISALIGNMENT_SCORE_STD,EXPECTATION_TOPICS_LIST,EXPERIENCE_TOPICS_LIST,VIOLATED_EXPECTATION_TOPICS_LIST,CONFIRMED_EXPECTATION_TOPICS_LIST,LATENT_EXPECTATION_TOPICS_LIST,EXPECTATION_TOPICS_UNIQUE,EXPERIENCE_TOPICS_UNIQUE,VIOLATED_EXPECTATION_TOPICS_UNIQUE,CONFIRMED_EXPECTATION_TOPICS_UNIQUE,LATENT_EXPECTATION_TOPICS_UNIQUE,N_EXPECTATION_TOPICS,N_EXPERIENCE_TOPICS,N_VIOLATED_EXPECTATION_TOPICS,N_CONFIRMED_EXPECTATION_TOPICS,N_LATENT_EXPECTATION_TOPICS,N_REVIEWS_WITH_EXPECTATION,N_REVIEWS_WITH_VIOLATED_EXPECTATION,EXPECTATION_COVERAGE,VIOLATION_COVERAGE,EXPECTATION_VIOLATION_RATIO,EXPECTATION_SHARE,HIGH_EXPECTATION_SHARE,HIGH_ALIGNMENT_SHARE,HIGH_MISALIGNMENT_SHARE,DOMINANT_EXPECTATION_EXPERIENCE_LABEL,EXPERIENCE_ONLY_SHARE,MINOR_MISALIGNMENT_SHARE,MODERATE_MISALIGNMENT_SHARE,MAJOR_MISALIGNMENT_SHARE,UNCLEAR_SHARE,EMOTION_ENTROPY,DOMINANT_EMOTION,SENTIMENT_SCORE_AVG,SENTIMENT_SCORE_STD,EXPECTATION_EXPERIENCE_GAP_AVG_LAG1,EXPECTATION_EXPERIENCE_GAP_AVG_ROLL4,SEMANTIC_MISALIGNMENT_SCORE_AVG_LAG1,SEMANTIC_MISALIGNMENT_SCORE_AVG_ROLL4,EXPECTATION_VIOLATION_RATIO_LAG1,EXPECTATION_VIOLATION_RATIO_ROLL4,MAJOR_MISALIGNMENT_SHARE_LAG1,MAJOR_MISALIGNMENT_SHARE_ROLL4,EMOTION_ENTROPY_LAG1,EMOTION_ENTROPY_ROLL4,SENTIMENT_SCORE_AVG_LAG1,SENTIMENT_SCORE_AVG_ROLL4,EXPECTATION_SHARE_LAG1,EXPECTATION_SHARE_ROLL4,HIGH_EXPECTATION_SHARE_LAG1,HIGH_EXPECTATION_SHARE_ROLL4,HIGH_ALIGNMENT_SHARE_LAG1,HIGH_ALIGNMENT_SHARE_ROLL4,HIGH_MISALIGNMENT_SHARE_LAG1,HIGH_MISALIGNMENT_SHARE_ROLL4,HIGH_MISALIGNMENT,HIGH_EXPECTATION,HIGH_EMOTIONAL_COMPLEXITY,HIGH_EXPECTATION_VIOLATION,HIGH_POSITIVE_EXPERIENCE,N_REVIEWS_POSITIVE,N_REVIEWS_NEGATIVE,PERC_REVIEWS_POSITIVE,PERC_REVIEWS_NEGATIVE,AVG_REVIEW_LENGTH_POS,AVG_REVIEW_LENGTH_NEG,TOTAL_REVIEW_LENGTH_MEAN,TOTAL_REVIEW_LENGTH_STD,%EXTREME_RATINGS_1,%EXTREME_RATINGS_10,AVG_REVIEW_RATING,MEDIAN_REVIEW_RATING,RATING_DISPERSION,NEGATIVE_TO_POSITIVE_RATIO,SEASON_FLAG,PERC_NEUTRAL_REVIEWS,N_DISTINCT_TOPICS,TOPIC_CONCENTRATION_INDEX,PERC_OPERATIONAL_COMPLAINTS,PERC_STRUCTURAL_PRAISE,PERC_PRICE_VALUE_MENTIONS,EMERGING_NEGATIVE_TOPIC,POLARIZATION_INDEX,PRIORITY_ALERT_FLAG,REVIEWER_ORIGIN_DIVERSITY,COMPLEXITY_INDEX,DELTA_SENTIMENT_VS_PREV_WEEK,DELTA_NUM_REVIEWS_VS_PREV_WEEK,ROLLING_AVG_SENTIMENT_4W,SENTIMENT_TREND_SLOPE,WEEK_DATE
0,1,2023_W01,461,Lagoa,Algarve,126,Agua Hotels Riverside Hotel Apartamento,https://www.booking.com/hotel/pt/agua-hotels-riverside.html,agua-hotels-riverside,sim,yes,4.0,NaN,"2 piscinas, Acesso Wi-Fi gratuito, Estacionamento gratuito, Spa e centro de bem-estar, Centro de fitness, Comodidades para pessoas com mobilidade condicionada, Transfer (aeroporto), Quartos para não fumadores, Bar, Muito bom pequeno-almoço",882,52.267574,447.0,17.718202,32.159364,30.408017,15.0,8.6,1.502379,0.050000,0.266667,-0.50,0.450000,0.166667,0.825,0.175,0.275076,0.292831,"['towel/pool deposit process should be linked to the hotel room (no paper ticket required)', ""New Year's Eve dinner quality relative to price"", ""coffee included with the New Year's Eve dinner""]","['breakfast variety', 'location', 'river view', 'room quality (excellent, spacious, modern)', 'breakfast quality and variety (complete, many options)', 'sofa comfort (sofa in living room not comfortable)', 'kitchen equipment (missing several essential utensils)', 'reception assistance (staff provided missing utensils)', 'towel/pool deposit process (had to keep a paper ticket to reclaim deposit)', 'outdoor space', 'value for money', 'daily cleaning', 'bathroom/shower quality', 'breakfast quality', 'location by the river', 'spacious suite', 'bathroom', ""New Year's Eve dinner poor quality"", ""New Year's Eve dinner overpriced / poor value"", 'coffee after the dinner required extra payment', 'customer service']","['towel/pool deposit process should be linked to the hotel room (no paper ticket required)', ""New Year's Eve dinner quality relative to price"", ""coffee included with the New Year's Eve dinner""]",[],"['kitchen utensils availability (essential items expected to be provided)', ""coffee included with the New Year's Eve dinner""]","[""New Year's Eve dinner quality relative to price"", ""coffee included with the New Year's Eve dinner"", 'towel/pool deposit process should be linked to the hotel room (no paper ticket required)']","[""New Year's Eve dinner overpriced / poor value"", ""New Year's Eve dinner poor quality"", 'bathroom', 'bathroom/shower quality', 'breakfast quality', 'breakfast quality and variety (complete, many options)', 'breakfast variety', 'coffee after the dinner required extra payment', 'customer service', 'daily cleaning', 'kitchen equipment (missing several essential utensils)', 'location', 'location by the river', 'outdoor space', 'reception assistance (staff provided missing utensils)', 'river view', 'room quality (excellent, spacious, modern)', 'sofa comfort (sofa in living room not comfortable)', 'spacious suite', 'towel/pool deposit process (had to keep a paper ticket to reclaim deposit)', 'value for money']","[""New Year's Eve dinner quality relative to price"", ""coffee included with the New Year's Eve dinner"", 'towel/pool deposit process should be linked to the hotel room (no paper ticket required)']",[],"[""coffee included with the New Year's Eve dinner"", 'kitchen utensils availability (essential items expected to be provided)']",3.0,21.0,3.0,0.0,2.0,2.0,2.0,0.133333,0.133333,1.0,0.133333,0.0,0.266667,0.066667,unclear,0.266667,0.066667,0.066667,0.0,0.600000,1.530493,joy,0.255556,0.610555,0.200000,0.222024,0.175,0.217857,1.0,1.0,0.0,0.0,0.918296,1.220087,0.500000,0.316567,0.066667,0.146257,0.0,0.0,0.066667,0.112745,0.000000,0.016667,0.175,0.050000,1.530493,1.0,0.450000,6.0,3.0,40.000000,20.000000,23.866667,32.733333,56.600000,113.880765,0.0,26.666667,8.6,9.0,1.502379,0.071429,Low,13.333333,11.0,0.190476,0.000000,25.0,0.0,[],0.60,0.0,1.471602,2.401649,-0.244444,0.0,0.316567,0.000482,2023-01-02
1,1,2023_W02,373,Lagoa,Algarve,126,Agua Hotels Riverside Hotel Apartamento,https://www.booking.com/hotel/pt/agua-hotels-riverside.html,agua-hotels-riverside,sim,yes,4.0,NaN,"2 piscinas, Acesso Wi-Fi gratuito, Estacionamento gratuito, Spa e centro de bem-estar, Centro de fitness, Comodidades para pessoas com mobilidade condicionada, Transfer (aeroporto), Quartos para não fumadores, Bar, Muito bom pequeno-almoço",882,42.290249,365.0,12.825191,28.881853,20.772719,25.0,9.0,1.040833,0.014000,0.180000,-0.45,0.566667,0.075000,0.925,0.075,0.183712,0.183712,['coffee-making facilities'],"['room cleanliness', 'pleasant/comfortable room space', 'beautiful view', 'staff friendliness and accessibility', 'varied breakfast', 'lack of supervision at indoor pool/spa', 'other guests not wearing required swim caps', 'disruptive and unsafe behavior by young guests at pool', 'families with babies forced to leave pool area', 'jacuzzi monopolized for 2.5 hours', 'location', 'breakfast service', 'apartment comfort', 'sound insulation', 'kitchen facilities', 'dishwasher', 'suite upgrade', 'room aesthetics', 'cleanliness', 'river view', 'no coffee maker', 'brought instant coffee and boiled water', 'overall space atmosphere (pleasant)', 'room size (spacious)', 'room comfort/ambience (cozy)', 'location', 'river view', 'room décor/finishes (tiled)', 'bathroom décor/finishes (tiled)', 'cleanliness', 'food', 'room comfort', 'location', 'reception staff helpfulness', 'reception staff friendliness']",['coffee-making facilities'],[],['coffee-making facilities'],['coffee-making facilities'],"['apartment comfort', 'bathroom décor/finishes (tiled)', 'beautiful view', 'breakfast service', 'brought instant coffee and boiled water', 'cleanliness', 'dishwasher', 'disruptive and unsafe behavior by young guests at pool', 'families with babies forced to leave pool area', 'food', 'jacuzzi monopolized for 2.5 hours', 'kitchen facilities', 'lack of supervision at indoor pool/spa', 'location', 'no coffee maker', 'other guests not wearing required swim caps', 'overall space atmosphere (pleasant)', 'pleasant/comfortable room space', 'reception staff friendliness', 'reception staff helpfulness', 'river view', 'room aesthetics', 'room cleanliness', 'room comfort', 'room comfort/ambience (cozy)', 'room décor/finishes (tiled)', 'room size (spacious)', 'sound insulation', 'staff friendliness and accessibility', 'suite upgrade', 'varied breakfast']",['coffee-making facilities'],[],['coffee-making facilities'],1.0,35.0,1.0,0.0,1.0,1.0,1.0,0.040000,0.040000,1.0,0.040000,0.0,0.200000,0.000000,unclear,0.200000,0.000000,0.040000,0.0,0.760000,1.351644,joy,0.333333,0.694622,0.166667,0.165774,0.175,0.161607,1.0,1.0,0.0,0.0,1.530493,1.307998,0.255556,0.312401,0.133333,0.133529,0.0,0.0,0.266667,0.162745,0.066667,0.016667,0.075,0.014000,1.351644,1.0,0.566667,6.0,3.0,24.000000,12.000000,27.440000,28.360000,55.800000,141.516783,0.0,40.000000,9.0,9.0,1.040833,0.000000,Low,4.000000,13.0,0.193548,33.333333,20.0,0.0,['pool supervision'],0.72,0.0,1.755336,2.360672,0.077778,10.0,0.312401,0.000482,2023-01-09
2,1,2023_W03,332,Lagoa,Algarve,126,Agua Hotels Riverside Hotel Apartamento,https://www.booking.com/hotel/pt/agua-hotels-riverside.html,agua-hotels-riverside,sim,yes,4.0,NaN,"2 piscinas, Acesso Wi-Fi gratuito, Estacionamento gratuito, Spa e centro de bem-estar, Centro de fitness, Comodidades para pessoas com mobilidade condicionada, Transfer (aeroporto), Quartos para não fumadores, Bar, Muito bom pequeno-almoço",882,37.641723,325.0,11.010115,28.591816,17.625752,18.0,8.5,1.382666,0.038889,0.194444,-0.40,0.480000,0.116667,0.850,0.150,0.191485,0.250998,"['sauna should be properly hot (Finnish sauna standard)', 'steam sauna should produce steam / be operational', 'minibar present/stocked as per room description', 'reservation/payment transparency — should not be charged twice', 'mirror in room']","['breakfast', 'overall stay', 'room comfort', 'breakfast quality', 'spa quality', 'gym quality', 'infinity pool facing Rio Arade', 'spa facilities', 'sauna not hot enough', 'steam sauna had no steam / was cold', 'dinner quality (very good)', 'breakfast variety / many options', 'superior room spacious', 'room cleanliness (spotlessly clean)', 'fresh Algarvian fruits delivered to room', 'reservation/payment charged twice / confusing', 'minibar missing (only an empty fridge despite description)', 'room', 'breakfast', 'living room sofa', 'room mirror (absent)', 'overall condition (everything impeccable)', 'staff friendliness', 'quiet location', 'river view / scenic view', 'sofa comfort (not very comfortable)']","['sauna should be properly hot (Finnish sauna standard)', 'steam sauna should produce steam / be operational', 'minibar present/stocked as per room description', 'reservation/payment transparency — should not be charged twice', 'mirror in room']",[],"['sauna should be properly hot (Finnish sauna standard)', 'steam sauna should produce steam / be operational', 'minibar present/stocked as per room description', 'reservation/payment transparency — should not be charged twice', 'mirror in room']","['minibar present/stocked as per room description', 'mirror in room', 'reservation/payment transparency — should not be charged twice', 'sauna should be properly hot (Finnish sauna standard)', 'steam sauna should produce steam / be operational']","['breakfast', 'breakfast quality', 'breakfast variety / many options', 'dinner quality (very good)', 'fresh Algarvian fruits delivered to room', 'gym quality', 'infinity pool facing Rio Arade', 'living room sofa', 'minibar missing (only an empty fridge despite description)', 'overall condition (everything impeccable)', 'overall stay', 'quiet location', 'reservation/payment charged twice / confusing', 'river view / scenic view', 'room', 'room cleanliness (spotlessly clean)', 'room comfort', 'room mirror (absent)', 'sauna not hot enough', 'sofa comfort (not very comfortable)', 'spa facilities', 'spa quality', 'staff friendliness', 'steam sauna had no steam / was cold', 'superior room spacious']","['minibar present/stocked as per room description', 'mirror in room', 'reservation/payment transparency — should not be charged twice', 'sauna should be properly hot (Finnish sauna standard)', 'steam sauna should produce steam / be operational']",[],"['minibar present/stocked as per room description', 'mirror in room', 'reservation/payment transparency — should not be charged twice', 'sauna should be properly hot (Finnish sauna standard)', 'steam sauna should produce steam / be operational']",5.0,26.0,5.0,0.0,5.0,2.0,2.0,0.111111,0.111111,1.0,0.111111,0.0,0.222222,0.055556,unclear,0.222222,0.055556,0.055556,0.0,0.666667,1.572624,frustration,0.081818,0.565364,0.075000,0.139583,0.075,0.143750,1.0,1.0,0.0,0.0,1.351644,1.343264,0.333333,0.292677,0.040000,0.087778,0.0,0.0,0.200000,0.188889,0.000000,0.030556,0.150,0.038889,1.572624,1.0,0.480000,6.0,5.0,33.333333,27.777778,29.888889,32.388889,62.277778,195.668328,0.0,22.222222,8.5,8.5,1.382666,0.058824,Low,16.666667,24.0,0.127660,0.000000,0.0,0.0,"['steam sauna temperature', 'furniture', 'empty fridge', 'sauna maintenance', 'reservation system', 'payment confusion', 'minibar']",0.50,0.0,1.944717,2.910584,-0.251515,-7.0,0.292677,0.000482,2023-01-16

In [15]:
# ======================================================
# PREPARAR REVIEWS
# ======================================================

reviews_clean = reviews_by_hotel.copy()

reviews_clean = reviews_clean.drop(
    columns=[
        col for col in reviews_clean.columns
        if col.lower().startswith("unnamed:")
    ],
    errors="ignore",
)


# Detetar a coluna da data
possible_date_columns = [
    "review_post_date",
    "REVIEW_POST_DATE",
    "review_date",
    "REVIEW_DATE",
]

review_date_column = next(
    (
        col for col in possible_date_columns
        if col in reviews_clean.columns
    ),
    None,
)

if review_date_column is None:
    raise KeyError(
        "Não foi encontrada uma coluna de data das reviews. "
        f"Colunas disponíveis: {reviews_clean.columns.tolist()}"
    )


# Não restringir a um único formato, para suportar pequenas variações
reviews_clean["review_date"] = pd.to_datetime(
    reviews_clean[review_date_column],
    errors="coerce",
)


# Segunda tentativa para o formato original, caso necessário
invalid_dates = reviews_clean["review_date"].isna()

if invalid_dates.any():
    reviews_clean.loc[invalid_dates, "review_date"] = pd.to_datetime(
        reviews_clean.loc[invalid_dates, review_date_column],
        format="%m-%d-%Y %H:%M:%S",
        errors="coerce",
    )


reviews_clean["week_date"] = (
    reviews_clean["review_date"]
    - pd.to_timedelta(
        reviews_clean["review_date"].dt.weekday,
        unit="D",
    )
).dt.normalize()


iso_calendar = reviews_clean["review_date"].dt.isocalendar()

reviews_clean["WEEK_YEAR"] = (
    iso_calendar["year"].astype("Int64").astype("string")
    + "_W"
    + iso_calendar["week"].astype("Int64").astype("string").str.zfill(2)
)


reviews_clean["ID_HOTEL"] = pd.to_numeric(
    reviews_clean["ID_HOTEL"],
    errors="coerce",
).astype("Int64")


print("Reviews totais:", len(reviews_clean))
print("Datas inválidas:", reviews_clean["review_date"].isna().sum())
print("Data mínima:", reviews_clean["review_date"].min())
print("Data máxima:", reviews_clean["review_date"].max())
print("Hotéis:", reviews_clean["ID_HOTEL"].nunique())

Reviews totais: 452061
Datas inválidas: 0
Data mínima: 2022-04-30 00:00:00
Data máxima: 2025-05-02 00:00:00
Hotéis: 333

In [16]:
# ======================================================
# LIMITAR REVIEWS AO PAINEL
# ======================================================

df_final_clean = (
    df_final
    .drop_duplicates(subset=["ID_HOTEL", "WEEK_YEAR"])
    .copy()
)

df_final_clean["WEEK_DATE"] = pd.to_datetime(
    df_final_clean["WEEK_DATE"],
    errors="coerce",
).dt.normalize()


panel_start = df_final_clean["WEEK_DATE"].min()
panel_end = df_final_clean["WEEK_DATE"].max() + pd.Timedelta(days=6)


reviews_panel_period = reviews_clean[
    reviews_clean["review_date"].between(
        panel_start,
        panel_end,
        inclusive="both",
    )
].copy()


hotels_panel = set(
    df_final_clean["ID_HOTEL"]
    .dropna()
    .astype(int)
)

hotels_reviews = set(
    reviews_panel_period["ID_HOTEL"]
    .dropna()
    .astype(int)
)

common_hotels = sorted(hotels_panel & hotels_reviews)
only_reviews = sorted(hotels_reviews - hotels_panel)
only_panel = sorted(hotels_panel - hotels_reviews)


reviews_panel_period = reviews_panel_period[
    reviews_panel_period["ID_HOTEL"].isin(common_hotels)
].copy()

df_final_clean = df_final_clean[
    df_final_clean["ID_HOTEL"].isin(common_hotels)
].copy()


print("Início do painel:", panel_start)
print("Fim do painel:", panel_end)
print("Reviews dentro do período:", len(reviews_panel_period))
print("Hotéis comuns:", len(common_hotels))
print("Apenas nas reviews:", only_reviews)
print("Apenas no painel:", only_panel)
print("Dimensão final do painel:", df_final_clean.shape)

Início do painel: 2023-01-02 00:00:00
Fim do painel: 2024-12-29 00:00:00
Reviews dentro do período: 301318
Hotéis comuns: 329
Apenas nas reviews: [273, 307, 510, 547]
Apenas no painel: []
Dimensão final do painel: (28845, 122)

In [17]:
# ======================================================
# VALIDAÇÕES
# ======================================================

print("Painel:")
print(df_final_clean.shape)
print(df_final_clean[["ID_HOTEL", "WEEK_YEAR", "WEEK_DATE"]].head())

print("\nReviews:")
print(reviews_panel_period.shape)
print(
    reviews_panel_period[
        ["ID_HOTEL", "WEEK_YEAR", "review_date"]
    ].head()
)

print("\nDuplicados no painel:")
print(
    df_final_clean
    .duplicated(["ID_HOTEL", "WEEK_YEAR"])
    .sum()
)

print("\nReviews sem ID_HOTEL:")
print(reviews_panel_period["ID_HOTEL"].isna().sum())

print("\nReviews sem data:")
print(reviews_panel_period["review_date"].isna().sum())

Painel:
(28845, 122)
   ID_HOTEL WEEK_YEAR  WEEK_DATE
0         1  2023_W01 2023-01-02
1         1  2023_W02 2023-01-09
2         1  2023_W03 2023-01-16
3         1  2023_W04 2023-01-23
4         1  2023_W05 2023-01-30

Reviews:
(301318, 36)
      ID_HOTEL WEEK_YEAR review_date
1205       149  2024_W52  2024-12-29
1206       149  2024_W52  2024-12-29
1207       149  2024_W52  2024-12-29
1208       149  2024_W52  2024-12-29
1209       149  2024_W52  2024-12-29

Duplicados no painel:
0

Reviews sem ID_HOTEL:
0

Reviews sem data:
0

In [18]:
# ======================================================
# PREPARAR DATASETS PARA O CASE BUILDER
# ======================================================

panel_for_case_builder = df_final_clean.copy()
reviews_for_case_builder = reviews_panel_period.copy()


# O CaseBuilder espera "week_date" em minúsculas
if "WEEK_DATE" in panel_for_case_builder.columns:
    panel_for_case_builder = panel_for_case_builder.rename(
        columns={"WEEK_DATE": "week_date"}
    )


# Garantir tipos corretos
panel_for_case_builder["ID_HOTEL"] = pd.to_numeric(
    panel_for_case_builder["ID_HOTEL"],
    errors="coerce"
).astype("Int64")

panel_for_case_builder["week_date"] = pd.to_datetime(
    panel_for_case_builder["week_date"],
    errors="coerce"
).dt.normalize()


# O CaseBuilder espera também WEEK_YEAR
panel_for_case_builder["WEEK_YEAR"] = (
    panel_for_case_builder["WEEK_YEAR"]
    .astype("string")
    .str.strip()
)


# Remover linhas inválidas
panel_for_case_builder = (
    panel_for_case_builder
    .dropna(
        subset=[
            "ID_HOTEL",
            "WEEK_YEAR",
            "week_date",
        ]
    )
    .sort_values(
        ["ID_HOTEL", "week_date"]
    )
    .drop_duplicates(
        subset=["ID_HOTEL", "week_date"],
        keep="first"
    )
    .reset_index(drop=True)
)


# Reviews
reviews_for_case_builder["ID_HOTEL"] = pd.to_numeric(
    reviews_for_case_builder["ID_HOTEL"],
    errors="coerce"
).astype("Int64")


# O CaseBuilder volta a criar review_date internamente
# a partir de review_post_date, por isso esta coluna tem de existir
if "review_post_date" not in reviews_for_case_builder.columns:
    raise KeyError(
        "A coluna 'review_post_date' não existe nas reviews."
    )


reviews_for_case_builder = (
    reviews_for_case_builder
    .dropna(subset=["ID_HOTEL", "review_post_date"])
    .reset_index(drop=True)
)


print("Painel preparado:")
print(panel_for_case_builder.shape)
print(
    panel_for_case_builder[
        ["ID_HOTEL", "WEEK_YEAR", "week_date"]
    ].head()
)

print("\nReviews preparadas:")
print(reviews_for_case_builder.shape)
print(
    reviews_for_case_builder[
        ["ID_HOTEL", "review_post_date"]
    ].head()
)

print(
    "\nDuplicados ID_HOTEL + week_date:",
    panel_for_case_builder
    .duplicated(["ID_HOTEL", "week_date"])
    .sum()
)

Painel preparado:
(28845, 122)
   ID_HOTEL WEEK_YEAR  week_date
0         1  2023_W01 2023-01-02
1         1  2023_W02 2023-01-09
2         1  2023_W03 2023-01-16
3         1  2023_W04 2023-01-23
4         1  2023_W05 2023-01-30

Reviews preparadas:
(301318, 36)
   ID_HOTEL     review_post_date
0       149  12-29-2024 00:00:00
1       149  12-29-2024 00:00:00
2       149  12-29-2024 00:00:00
3       149  12-29-2024 00:00:00
4       149  12-29-2024 00:00:00

Duplicados ID_HOTEL + week_date: 0

In [19]:
from src.case_builder import CaseBuilder

In [20]:
builder = CaseBuilder(
    panel_df=panel_for_case_builder,
    reviews_df=reviews_for_case_builder
)

In [21]:
case = builder.build_case(
    hotel_id=149,
    decision_week="2024_W20",
    lookback_weeks=4,
    max_reviews=20,
    top_n_topics=10
)

In [22]:
complaints_df = pd.DataFrame(
    case["complaints"]
)

display(
    complaints_df[
        [
            "review_date",
            "rating",
            "language",
            "complaint_text",
            "disliked",
            "liked_context"
        ]
    ]
)

,review_date,rating,language,complaint_text,disliked,liked_context
0,2024-04-26,5.0,en-us,"Disliked: Reflecting on my stay at Hotel Mundial, there were several aspects that left me feeling underwhelmed. Firstly, the room and bathroom fell short of my expectations, with outdated furnishings and a cramped layout. The shower posed a safety concern due to its slippery floor and constant leakage, making it difficult to use comfortably. Additionally, the bedding arrangement, with two twin beds pushed together instead of a king bed as requested, was disappointing. The lack of amenities such as a steamer or iron further detracted from the overall comfort of the room. Despite the hotel's convenient location, the outdated facilities and lackluster amenities made it difficult for me to overlook these shortcomings. Overall, while there were some positive aspects to my stay, I found the hotel to be lacking in terms of value and comfort.","Reflecting on my stay at Hotel Mundial, there were several aspects that left me feeling underwhelmed. Firstly, the room and bathroom fell short of my expectations, with outdated furnishings and a cramped layout. The shower posed a safety concern due to its slippery floor and constant leakage, making it difficult to use comfortably. Additionally, the bedding arrangement, with two twin beds pushed together instead of a king bed as requested, was disappointing. The lack of amenities such as a steamer or iron further detracted from the overall comfort of the room. Despite the hotel's convenient location, the outdated facilities and lackluster amenities made it difficult for me to overlook these shortcomings. Overall, while there were some positive aspects to my stay, I found the hotel to be lacking in terms of value and comfort.","In terms of what I liked about Hotel Mundial, there were definitely some positives to highlight amidst the mixed experience. Firstly, the hotel's prime location stood out to me as a major advantage. Being close to many of Lisbon's main attractions and cities made exploring the area incredibly convenient. Additionally, the restaurant offered a picturesque view, and I particularly enjoyed the octopus salad we had for dinner. The abundance of breakfast choices was also a plus, even though I wished the quality of the food matched the variety. Finally, the staff were friendly and accommodating, which added a welcoming touch to our stay."
1,2024-05-08,6.0,en-us,Disliked: Not value for money. For the money you pay you'd expect at least a free bottle of water in the room. Breakfast is below average. Hotel is old and is a bit outdated. Doesn't have enough facilities (ex: Gym),Not value for money. For the money you pay you'd expect at least a free bottle of water in the room. Breakfast is below average. Hotel is old and is a bit outdated. Doesn't have enough facilities (ex: Gym),Location is very central. Beds are comfortable and shower was good. Staff were great and very helpful!
2,2024-04-30,6.0,de,Disliked: A hotel that has seen better days and is in urgent need of renovation. The rooms are worn and you simply don't feel comfortable. Cleanliness also leaves much to be desired. Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.,A hotel that has seen better days and is in urgent need of renovation. The rooms are worn and you simply don't feel comfortable. Cleanliness also leaves much to be desired. Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.,The hotel stands out for its location and the beautiful rooftop terrace.
3,2024-04-23,6.0,de,"Disliked: Stairs made of black stone. The edge is barely visible… potentially dangerous! It should be painted a light color. Large, many guests, breakfast has a high noise level, crowding 😰 The reception is often hectic as well.","Stairs made of black stone. The edge is barely visible… potentially dangerous! It should be painted a light color. Large, many guests, breakfast has a high noise level, crowding 😰 The reception is often hectic as well.",Location
4,2024-05-12,6.0,da,Disliked: It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.,It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.,The location
5,2024-04-29,6.0,en,Disliked: Wait time with bar staff sometimes considerably long in the lounge bar,Wait time with bar staff sometimes considerably long in the lounge bar,Roof top bar and location
6,2024-05-19,7.0,nl,Disliked: The bathroom is dated. If you're a bit taller you cannot sit properly on the toilet. You shower in the bathtub (which is very slippery). If you're a bit taller you don't fit well under the showerhead. There were two holes in the floor (drains?). As a result there was a sewer smell in the bathroom. We solved this by placing the bath mat over the two covers. Given the price of the room this should not happen.,The bathroom is dated. If you're a bit taller you cannot sit properly on the toilet. You shower in the bathtub (which is very slippery). If you're a bit taller you don't fit well under the showerhead. There were two holes in the floor (drains?). As a result there was a sewer smell in the bathroom. We solved this by placing the bath mat over the two covers. Given the price of the room this should not happen.,The staff are more than friendly and helpful. You really feel welcome as a guest. The breakfast is excellent. The upstairs restaurant is also worth it. The hotel is located close to public transport. No request or effort is too much. Every day a bottle of water was placed in the room.
7,2024-04-26,7.0,en-us,"Disliked: The fact that we tried numerous times to get a table at the Rooftop bar and got nowhere. In my opinion, preference should be given to guests that actually stay in the hotel and not to the public. One of the main reasons we chose this hotel was the Rooftop bar. Room service was non existent.","The fact that we tried numerous times to get a table at the Rooftop bar and got nowhere. In my opinion, preference should be given to guests that actually stay in the hotel and not to the public. One of the main reasons we chose this hotel was the Rooftop bar. Room service was non existent.","We loved the location. We loved the spacious sunny balcony. The complimentary bottle of wine and Portuguese pastry was a nice touch. And front office staff were informative, efficient and friendly."
8,2024-04-29,7.0,en-us,"Disliked: The room did not seem really clean- the carpet had hairs- like pet hair- on it, bath towels were worn and had holes in them.staff were not super knowledgeable and gave us wrong advice on dinner(said no reservations allowed ) and timing to get to train station by taxi.","The room did not seem really clean- the carpet had hairs- like pet hair- on it, bath towels were worn and had holes in them.staff were not super knowledgeable and gave us wrong advice on dinner(said no reservations allowed ) and timing to get to train station by taxi.","Fantastic location, corner room on upper level had nice views. Comfortable bed"
9,2024-05-07,7.0,it,"Disliked: Room cleaning was not adequate, the bathroom is dated and needs renovation. The bathtub drain was not working. Overall not up to the standard of a 4-star!","Room cleaning was not adequate, the bathroom is dated and needs renovation. The bathtub drain was not working. Overall not up to the standard of a 4-star!","Excellent location, convenient for transport services and for reaching the various areas of the city. However, the hotel's entrance is located on a poorly frequented square. Very rich and abundant breakfast. Friendly staff."
10,2024-05-14,7.0,fr,"Disliked: Too much noise at night, rooms are very poorly soundproofed. The breakfast lacks regional specialties.","Too much noise at night, rooms are very poorly soundproofed. The breakfast lacks regional specialties.",The room and the facilities are perfect.
11,2024-04-25,7.0,de,Disliked: Our room was very dated and urgently needs renovation.,Our room was very dated and urgently needs renovation.,"Very good location for exploring the city, good breakfast."
12,2024-05-03,7.0,it,Disliked: Breakfast not up to the standard of a 4-star,Breakfast not up to the standard of a 4-star,"Central location, very comfortable beds"
13,2024-05-16,8.0,de,"Disliked: Old doors without a proper closing mechanism mean that heavy wooden doors cannot be gently pulled closed or latched, but always slam shut. This means that at night you are woken by the slamming of the door whenever a neighbor enters their room. The breakfast is very monotonous and not particularly high-quality or healthy. There was little fresh fruit and vegetables and almost no muesli (only packet granola). The breakfast restaurant is very large and has more of a canteen character.","Old doors without a proper closing mechanism mean that heavy wooden doors cannot be gently pulled closed or latched, but always slam shut. This means that at night you are woken by the slamming of the door whenever a neighbor enters their room. The breakfast is very monotonous and not particularly high-quality or healthy. There was little fresh fruit and vegetables and almost no muesli (only packet granola). The breakfast restaurant is very large and has more of a canteen character.","Centrally located, clean hotel with a great rooftop bar. The rooms are functional and sufficiently large. There is a large complimentary bottle of water and a minibar is also available."
14,2024-05-18,8.0,de,"Disliked: A bit too loud to sleep. No hair conditioner or body lotion. I had a small emergency (during my stay I got my period); unfortunately the hotel reception had neither tampons nor pads, it was midnight and the shops were closed... A bit annoying. It would be nice if the hotel offered such items for such cases.","A bit too loud to sleep. No hair conditioner or body lotion. I had a small emergency (during my stay I got my period); unfortunately the hotel reception had neither tampons nor pads, it was midnight and the shops were closed... A bit annoying. It would be nice if the hotel offered such items for such cases.",The location
15,2024-05-11,8.0,nl,"Disliked: As a 70-year-old in a room with only one power outlet, having to lie on my stomach under the desk every day to plug my mobile phone into the charger...","As a 70-year-old in a room with only one power outlet, having to lie on my stomach under the desk every day to plug my mobile phone into the charger...",De ligging
16,2024-05-02,8.0,de,Disliked: Unfortunately the room staff were not on the ball; we had to ask reception several times for toilet paper and towels. At 4 stars I expect a bit more.,Unfortunately the room staff were not on the ball; we had to ask reception several times for toilet paper and towels. At 4 stars I expect a bit more.,"Very central, everything within walking distance, good breakfast included in the price, the room has an optimal size, good value for money"
17,2024-04-28,8.0,de,Disliked: Has seen better days; the breakfast situation is not cozy; there are many tour groups so it was also a bit noisy; the parking is very tight.,Has seen better days; the breakfast situation is not cozy; there are many tour groups so it was also a bit noisy; the parking is very tight.,"Great, outstanding location right in the middle, parking available, comfortable beds, the rooftop bar is very nice."
18,2024-04-23,8.0,fr,Disliked: Room 634 was spacious and ideal for three but the windows were not well insulated against noise.,Room 634 was spacious and ideal for three but the windows were not well insulated against noise.,We chose this hotel to have a room with 3 single beds. And a perfect location for visiting Lisbon. The rooftop bar is very nice for the view. Bus and metro nearby. Lively neighborhood. All the staff are lovely and helpful.
19,2024-04-27,8.0,fr,"Disliked: Very noisy in the streets near the hotel, which makes it impossible to sleep with the window open.","Very noisy in the streets near the hotel, which makes it impossible to sleep with the window open.",The breakfast is very comprehensive. The location is perfect for getting around without a car. The staff are friendly.

In [23]:
case

{'case_metadata': {'case_id': 'H149_20240513_L4',
  'hotel_id': 149,
  'decision_week': '2024_W20',
  'decision_date': '2024-05-13',
  'window_start': '2024-04-22',
  'window_end': '2024-05-19',
  'lookback_weeks_requested': 4,
  'panel_weeks_available': 4,
  'complete_window': True},
 'hotel_profile': {'ID_HOTEL': 149,
  'NAME': 'Hotel Mundial',
  'NOME_HOTEL_URL': 'hotelmundial',
  'ID_LOCAL': 'Lisboa',
  'N_ROOMS': 349,
  'STARS': 4.0,
  'PRINCIPAIS_COMODIDADES': 'Estacionamento privado, Acesso Wi-Fi gratuito, Transfer (aeroporto), Quartos familiares, Quartos para não fumadores, Restaurante, Receção disponível 24 horas, Comodidades para pessoas com mobilidade condicionada, Bar, Muito bom pequeno-almoço'},
 'latest_context': {'dominant_emotion': 'joy',
  'dominant_expectation_experience_label': 'experience_only',
  'season': 'Low',
  'priority_alert_flag': 0.0,
  'emerging_negative_topic': ['overpriced',
   'shower experience',
   'toilet comfort',
   'space',
   'no showers',
   'cocktails']},
 'metric_definitions': {'REVPAR_WEEK': {'label': 'Weekly RevPAR',
   'meaning': 'Weekly revenue per available room.',
   'higher_is_generally_better': True},
  'REVPOR_WEEK': {'label': 'Weekly RevPOR',
   'meaning': 'Weekly revenue per occupied room.',
   'higher_is_generally_better': True},
  'TREVPAR_WEEK': {'label': 'Weekly TRevPAR',
   'meaning': 'Weekly total revenue per available room.',
   'higher_is_generally_better': True},
  'TAXA_OCUPACAO': {'label': 'Occupancy rate',
   'meaning': 'Percentage of available room capacity occupied.',
   'higher_is_generally_better': True},
  'N_REVIEWS': {'label': 'Number of reviews',
   'meaning': 'Number of reviews associated with the hotel-week.',
   'higher_is_generally_better': None},
  'AVG_RATING': {'label': 'Average rating',
   'meaning': 'Average numerical review rating.',
   'higher_is_generally_better': True},
  'SENTIMENT_SCORE_AVG': {'label': 'Average sentiment',
   'meaning': 'Average sentiment score extracted from review text.',
   'higher_is_generally_better': True},
  'SENTIMENT_SCORE_STD': {'label': 'Sentiment dispersion',
   'meaning': 'Dispersion of sentiment across reviews.',
   'higher_is_generally_better': None},
  'EXPECTATION_EXPERIENCE_GAP_AVG': {'label': 'Expectation–experience gap',
   'meaning': 'Average discrepancy between expressed expectations and reported experience.',
   'higher_is_generally_better': False},
  'SEMANTIC_MISALIGNMENT_SCORE_AVG': {'label': 'Semantic misalignment',
   'meaning': 'Average semantic divergence between expectations and reported experience.',
   'higher_is_generally_better': False},
  'EXPECTATION_VIOLATION_RATIO': {'label': 'Expectation violation ratio',
   'meaning': 'Share or ratio of expectation-related observations classified as violated.',
   'higher_is_generally_better': False},
  'MAJOR_MISALIGNMENT_SHARE': {'label': 'Major misalignment share',
   'meaning': 'Share of reviews or review structures showing major expectation–experience misalignment.',
   'higher_is_generally_better': False},
  'EMOTION_ENTROPY': {'label': 'Emotional complexity',
   'meaning': 'Entropy-based heterogeneity of emotions expressed across reviews.',
   'higher_is_generally_better': None},
  'EXPECTATION_SHARE': {'label': 'Expectation share',
   'meaning': 'Share of reviews containing identifiable expectations.',
   'higher_is_generally_better': None},
  'HIGH_EXPECTATION_SHARE': {'label': 'High-expectation share',
   'meaning': 'Share of reviews containing high-intensity expectations.',
   'higher_is_generally_better': None},
  'HIGH_MISALIGNMENT_SHARE': {'label': 'High-misalignment share',
   'meaning': 'Share of observations with high semantic misalignment.',
   'higher_is_generally_better': False},
  'PERC_REVIEWS_NEGATIVE': {'label': 'Reviews containing negative/disliked content',
   'meaning': 'Percentage of reviews containing a negative or disliked text component. It does not mean that the full review or numerical rating is negative.',
   'higher_is_generally_better': False,
   'critical_interpretation_warning': 'Do not interpret this variable as the percentage of guests giving a negative overall evaluation.'},
  'PERC_OPERATIONAL_COMPLAINTS': {'label': 'Operational complaint share',
   'meaning': 'Percentage of complaint content associated with operational or service-delivery issues.',
   'higher_is_generally_better': False},
  'PERC_PRICE_VALUE_MENTIONS': {'label': 'Price–value mention share',
   'meaning': 'Percentage of review content mentioning price or perceived value.',
   'higher_is_generally_better': None},
  'POLARIZATION_INDEX': {'label': 'Review polarization',
   'meaning': 'Degree to which review experiences are divided or polarized.',
   'higher_is_generally_better': False},
  'COMPLEXITY_INDEX': {'label': 'Experience complexity index',
   'meaning': 'Composite indicator of heterogeneous and layered customer experience signals.',
   'higher_is_generally_better': None},
  'SENTIMENT_TREND_SLOPE': {'label': 'Precomputed sentiment trend slope',
   'meaning': 'Trend slope calculated previously in the source panel. Do not confuse it with the case-window trend recalculated by the Case Builder.',
   'higher_is_generally_better': None}},
 'weekly_history': [{'WEEK_YEAR': '2024_W17',
   'week_date': '2024-04-22',
   'REVPAR_WEEK': 137.79088647884825,
   'REVPOR_WEEK': 211.5028830434784,
   'TREVPAR_WEEK': 183.41268953229107,
   'TAXA_OCUPACAO': 89.11174785100286,
   'N_REVIEWS': 47.0,
   'AVG_RATING': 8.808510638297872,
   'SENTIMENT_SCORE_AVG': 0.3484848484848484,
   'SENTIMENT_SCORE_STD': 0.6214727976576596,
   'EXPECTATION_EXPERIENCE_GAP_AVG': 0.0791666666666666,
   'SEMANTIC_MISALIGNMENT_SCORE_AVG': 0.0833333333333333,
   'EXPECTATION_VIOLATION_RATIO': 0.9230769230769232,
   'MAJOR_MISALIGNMENT_SHARE': 0.0,
   'EMOTION_ENTROPY': 1.3397160194691369,
   'EXPECTATION_SHARE': 0.1702127659574468,
   'HIGH_EXPECTATION_SHARE': 0.0425531914893617,
   'HIGH_MISALIGNMENT_SHARE': 0.0638297872340425,
   'PERC_REVIEWS_NEGATIVE': 63.82978723404256,
   'PERC_OPERATIONAL_COMPLAINTS': 14.285714285714285,
   'PERC_PRICE_VALUE_MENTIONS': 0.0,
   'POLARIZATION_INDEX': 0.6595744680851063,
   'COMPLEXITY_INDEX': 2.564025934123769,
   'SENTIMENT_TREND_SLOPE': 0.0004705291930033},
  {'WEEK_YEAR': '2024_W18',
   'week_date': '2024-04-29',
   'REVPAR_WEEK': 138.88903819046234,
   'REVPOR_WEEK': 298.6903639947441,
   'TREVPAR_WEEK': 184.10846458588165,
   'TAXA_OCUPACAO': 89.07081457224723,
   'N_REVIEWS': 41.0,
   'AVG_RATING': 8.585365853658537,
   'SENTIMENT_SCORE_AVG': 0.2777777777777778,
   'SENTIMENT_SCORE_STD': 0.6086082815769437,
   'EXPECTATION_EXPERIENCE_GAP_AVG': 0.1203703703703703,
   'SEMANTIC_MISALIGNMENT_SCORE_AVG': 0.1351851851851851,
   'EXPECTATION_VIOLATION_RATIO': 0.8571428571428571,
   'MAJOR_MISALIGNMENT_SHARE': 0.0,
   'EMOTION_ENTROPY': 1.385724516098142,
   'EXPECTATION_SHARE': 0.1707317073170731,
   'HIGH_EXPECTATION_SHARE': 0.048780487804878,
   'HIGH_MISALIGNMENT_SHARE': 0.0975609756097561,
   'PERC_REVIEWS_NEGATIVE': 43.90243902439025,
   'PERC_OPERATIONAL_COMPLAINTS': 26.666666666666668,
   'PERC_PRICE_VALUE_MENTIONS': 0.0,
   'POLARIZATION_INDEX': 0.5853658536585366,
   'COMPLEXITY_INDEX': 2.7460819915270367,
   'SENTIMENT_TREND_SLOPE': 0.0004705291930033},
  {'WEEK_YEAR': '2024_W19',
   'week_date': '2024-05-06',
   'REVPAR_WEEK': 152.3059819649979,
   'REVPOR_WEEK': 248.9802766247022,
   'TREVPAR_WEEK': 197.27703353098275,
   'TAXA_OCUPACAO': 84.07695456406059,
   'N_REVIEWS': 31.0,
   'AVG_RATING': 8.612903225806452,
   'SENTIMENT_SCORE_AVG': 0.1749999999999999,
   'SENTIMENT_SCORE_STD': 0.6159951298508779,
   'EXPECTATION_EXPERIENCE_GAP_AVG': 0.2346153846153846,
   'SEMANTIC_MISALIGNMENT_SCORE_AVG': 0.25,
   'EXPECTATION_VIOLATION_RATIO': 0.8333333333333334,
   'MAJOR_MISALIGNMENT_SHARE': 0.064516129032258,
   'EMOTION_ENTROPY': 1.46553604083261,
   'EXPECTATION_SHARE': 0.1935483870967742,
   'HIGH_EXPECTATION_SHARE': 0.1290322580645161,
   'HIGH_MISALIGNMENT_SHARE': 0.1290322580645161,
   'PERC_REVIEWS_NEGATIVE': 41.935483870967744,
   'PERC_OPERATIONAL_COMPLAINTS': 18.181818181818183,
   'PERC_PRICE_VALUE_MENTIONS': 0.0,
   'POLARIZATION_INDEX': 0.6129032258064516,
   'COMPLEXITY_INDEX': 2.847243184652271,
   'SENTIMENT_TREND_SLOPE': 0.0004705291930033},
  {'WEEK_YEAR': '2024_W20',
   'week_date': '2024-05-13',
   'REVPAR_WEEK': 154.48296533177387,
   'REVPOR_WEEK': 261.13567753001746,
   'TREVPAR_WEEK': 209.317862853041,
   'TAXA_OCUPACAO': 87.39255014326648,
   'N_REVIEWS': 40.0,
   'AVG_RATING': 8.575,
   'SENTIMENT_SCORE_AVG': 0.2851063829787234,
   'SENTIMENT_SCORE_STD': 0.6050435569675435,
   'EXPECTATION_EXPERIENCE_GAP_AVG': 0.124074074074074,
   'SEMANTIC_MISALIGNMENT_SCORE_AVG': 0.1444444444444444,
   'EXPECTATION_VIOLATION_RATIO': 1.0,
   'MAJOR_MISALIGNMENT_SHARE': 0.0,
   'EMOTION_ENTROPY': 1.4048921852331595,
   'EXPECTATION_SHARE': 0.2,
   'HIGH_EXPECTATION_SHARE': 0.0,
   'HIGH_MISALIGNMENT_SHARE': 0.1,
   'PERC_REVIEWS_NEGATIVE': 50.0,
   'PERC_OPERATIONAL_COMPLAINTS': 17.647058823529413,
   'PERC_PRICE_VALUE_MENTIONS': 0.0,
   'POLARIZATION_INDEX': 0.5,
   'COMPLEXITY_INDEX': 2.6116464321996693,
   'SENTIMENT_TREND_SLOPE': 0.0004705291930033}],
 'trends': {'REVPAR_WEEK': {'direction': 'increasing',
   'trend_strength': 'consistent',
   'first_value': 137.79088647884825,
   'last_value': 154.48296533177387,
   'minimum_value': 137.79088647884825,
   'maximum_value': 154.48296533177387,
   'absolute_change': 16.69207885292562,
   'percentage_change': 12.114065944040469,
   'slope': 6.349318033331214,
   'standardized_slope': 0.8380324181089484,
   'direction_consistency': 1.0,
   'recent_movement': 'up',
   'recent_absolute_change': 2.1769833667759713,
   'recent_reversal': False,
   'n_observations': 4},
  'REVPOR_WEEK': {'direction': 'increasing',
   'trend_strength': 'moderate',
   'first_value': 211.5028830434784,
   'last_value': 261.13567753001746,
   'minimum_value': 211.5028830434784,
   'maximum_value': 298.6903639947441,
   'absolute_change': 49.63279448653907,
   'percentage_change': 23.466722425876398,
   'slope': 9.918829608957482,
   'standardized_slope': 0.31869188368803497,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'up',
   'recent_absolute_change': 12.155400905315247,
   'recent_reversal': False,
   'n_observations': 4},
  'TREVPAR_WEEK': {'direction': 'increasing',
   'trend_strength': 'consistent',
   'first_value': 183.41268953229107,
   'last_value': 209.317862853041,
   'minimum_value': 183.41268953229107,
   'maximum_value': 209.317862853041,
   'absolute_change': 25.905173320749924,
   'percentage_change': 14.123980945271041,
   'slope': 9.088408890735055,
   'standardized_slope': 0.852683968252205,
   'direction_consistency': 1.0,
   'recent_movement': 'up',
   'recent_absolute_change': 12.040829322058244,
   'recent_reversal': False,
   'n_observations': 4},
  'TAXA_OCUPACAO': {'direction': 'decreasing',
   'trend_strength': 'moderate',
   'first_value': 89.11174785100286,
   'last_value': 87.39255014326648,
   'minimum_value': 84.07695456406059,
   'maximum_value': 89.11174785100286,
   'absolute_change': -1.7191977077363845,
   'percentage_change': -1.929260450160766,
   'slope': -1.015145313139596,
   'standardized_slope': -0.4958760464806411,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'up',
   'recent_absolute_change': 3.3155955792058904,
   'recent_reversal': True,
   'n_observations': 4},
  'N_REVIEWS': {'direction': 'decreasing',
   'trend_strength': 'moderate',
   'first_value': 47.0,
   'last_value': 40.0,
   'minimum_value': 31.0,
   'maximum_value': 47.0,
   'absolute_change': -7.0,
   'percentage_change': -14.893617021276595,
   'slope': -3.10000000000001,
   'standardized_slope': -0.542214142113818,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'up',
   'recent_absolute_change': 9.0,
   'recent_reversal': True,
   'n_observations': 4},
  'AVG_RATING': {'direction': 'decreasing',
   'trend_strength': 'moderate',
   'first_value': 8.808510638297872,
   'last_value': 8.575,
   'minimum_value': 8.575,
   'maximum_value': 8.808510638297872,
   'absolute_change': -0.23351063829787222,
   'percentage_change': -2.650966183574878,
   'slope': -0.06729945427457124,
   'standardized_slope': -0.7072274259771043,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.03790322580645267,
   'recent_reversal': False,
   'n_observations': 4},
  'SENTIMENT_SCORE_AVG': {'direction': 'decreasing',
   'trend_strength': 'moderate',
   'first_value': 0.3484848484848484,
   'last_value': 0.2851063829787234,
   'minimum_value': 0.1749999999999999,
   'maximum_value': 0.3484848484848484,
   'absolute_change': -0.06337846550612497,
   'percentage_change': -18.18686401480108,
   'slope': -0.029291317429615334,
   'standardized_slope': -0.4711031700868375,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'up',
   'recent_absolute_change': 0.11010638297872352,
   'recent_reversal': True,
   'n_observations': 4},
  'SENTIMENT_SCORE_STD': {'direction': 'decreasing',
   'trend_strength': 'moderate',
   'first_value': 0.6214727976576596,
   'last_value': 0.6050435569675435,
   'minimum_value': 0.6050435569675435,
   'maximum_value': 0.6214727976576596,
   'absolute_change': -0.016429240690116087,
   'percentage_change': -2.6435977169134586,
   'slope': -0.004190087379641532,
   'standardized_slope': -0.6560689022260022,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.01095157288333437,
   'recent_reversal': False,
   'n_observations': 4},
  'EXPECTATION_EXPERIENCE_GAP_AVG': {'direction': 'increasing',
   'trend_strength': 'moderate',
   'first_value': 0.0791666666666666,
   'last_value': 0.124074074074074,
   'minimum_value': 0.0791666666666666,
   'maximum_value': 0.2346153846153846,
   'absolute_change': 0.04490740740740741,
   'percentage_change': 56.725146198830465,
   'slope': 0.024896723646723632,
   'standardized_slope': 0.4319111355690588,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.11054131054131058,
   'recent_reversal': True,
   'n_observations': 4},
  'SEMANTIC_MISALIGNMENT_SCORE_AVG': {'direction': 'increasing',
   'trend_strength': 'moderate',
   'first_value': 0.0833333333333333,
   'last_value': 0.1444444444444444,
   'minimum_value': 0.0833333333333333,
   'maximum_value': 0.25,
   'absolute_change': 0.0611111111111111,
   'percentage_change': 73.33333333333336,
   'slope': 0.02981481481481482,
   'standardized_slope': 0.4926087596545057,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.1055555555555556,
   'recent_reversal': True,
   'n_observations': 4},
  'EXPECTATION_VIOLATION_RATIO': {'direction': 'increasing',
   'trend_strength': 'weak',
   'first_value': 0.9230769230769232,
   'last_value': 1.0,
   'minimum_value': 0.8333333333333334,
   'maximum_value': 1.0,
   'absolute_change': 0.07692307692307676,
   'percentage_change': 8.333333333333314,
   'slope': 0.020695970695970567,
   'standardized_slope': 0.3196522241219279,
   'direction_consistency': 0.3333333333333333,
   'recent_movement': 'up',
   'recent_absolute_change': 0.16666666666666663,
   'recent_reversal': False,
   'n_observations': 4},
  'MAJOR_MISALIGNMENT_SHARE': {'direction': 'fluctuating',
   'trend_strength': 'fluctuating',
   'first_value': 0.0,
   'last_value': 0.0,
   'minimum_value': 0.0,
   'maximum_value': 0.064516129032258,
   'absolute_change': 0.0,
   'percentage_change': None,
   'slope': 0.0064516129032258,
   'standardized_slope': 0.23094010767585035,
   'direction_consistency': 0.3333333333333333,
   'recent_movement': 'down',
   'recent_absolute_change': -0.064516129032258,
   'recent_reversal': False,
   'n_observations': 4},
  'EMOTION_ENTROPY': {'direction': 'increasing',
   'trend_strength': 'moderate',
   'first_value': 1.3397160194691369,
   'last_value': 1.4048921852331595,
   'minimum_value': 1.3397160194691369,
   'maximum_value': 1.46553604083261,
   'absolute_change': 0.06517616576402263,
   'percentage_change': 4.864923970219355,
   'slope': 0.027534002202653434,
   'standardized_slope': 0.6098901439156774,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.0606438555994504,
   'recent_reversal': True,
   'n_observations': 4},
  'EXPECTATION_SHARE': {'direction': 'increasing',
   'trend_strength': 'consistent',
   'first_value': 0.1702127659574468,
   'last_value': 0.2,
   'minimum_value': 0.1702127659574468,
   'maximum_value': 0.2,
   'absolute_change': 0.029787234042553207,
   'percentage_change': 17.50000000000001,
   'slope': 0.011217838190736042,
   'standardized_slope': 0.8403763687056505,
   'direction_consistency': 1.0,
   'recent_movement': 'up',
   'recent_absolute_change': 0.006451612903225823,
   'recent_reversal': False,
   'n_observations': 4},
  'HIGH_EXPECTATION_SHARE': {'direction': 'fluctuating',
   'trend_strength': 'fluctuating',
   'first_value': 0.0425531914893617,
   'last_value': 0.0,
   'minimum_value': 0.0,
   'maximum_value': 0.1290322580645161,
   'absolute_change': -0.0425531914893617,
   'percentage_change': -100.0,
   'slope': -0.004740780420844707,
   'standardized_slope': -0.10165681664214256,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.1290322580645161,
   'recent_reversal': False,
   'n_observations': 4},
  'HIGH_MISALIGNMENT_SHARE': {'direction': 'increasing',
   'trend_strength': 'moderate',
   'first_value': 0.0638297872340425,
   'last_value': 0.1,
   'minimum_value': 0.0638297872340425,
   'maximum_value': 0.1290322580645161,
   'absolute_change': 0.0361702127659575,
   'percentage_change': 56.666666666666785,
   'slope': 0.013998192075263233,
   'standardized_slope': 0.6060198900100574,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.029032258064516092,
   'recent_reversal': True,
   'n_observations': 4},
  'PERC_REVIEWS_NEGATIVE': {'direction': 'decreasing',
   'trend_strength': 'moderate',
   'first_value': 63.82978723404256,
   'last_value': 50.0,
   'minimum_value': 41.935483870967744,
   'maximum_value': 63.82978723404256,
   'absolute_change': -13.829787234042563,
   'percentage_change': -21.66666666666668,
   'slope': -4.345631685555025,
   'standardized_slope': -0.5073577674999447,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'up',
   'recent_absolute_change': 8.064516129032256,
   'recent_reversal': True,
   'n_observations': 4},
  'PERC_OPERATIONAL_COMPLAINTS': {'direction': 'fluctuating',
   'trend_strength': 'fluctuating',
   'first_value': 14.285714285714285,
   'last_value': 17.647058823529413,
   'minimum_value': 14.285714285714285,
   'maximum_value': 26.666666666666668,
   'absolute_change': 3.3613445378151283,
   'percentage_change': 23.5294117647059,
   'slope': 0.15991851285968817,
   'standardized_slope': 0.035032982642629766,
   'direction_consistency': 0.6666666666666666,
   'recent_movement': 'down',
   'recent_absolute_change': -0.5347593582887704,
   'recent_reversal': False,
   'n_observations': 4},
  'PERC_PRICE_VALUE_MENTIONS': {'direction': 'stable',
   'trend_strength': 'stable',
   'first_value': 0.0,
   'last_value': 0.0,
   'minimum_value': 0.0,
   'maximum_value': 0.0,
   'absolute_change': 0.0,
   'percentage_change': None,
   'slope': 0.0,
   'standardized_slope': 0.0,
   'direction_consistency': 1.0,
   'recent_movement': 'flat',
   'recent_absolute_change': 0.0,
   'recent_reversal': False,
   'n_observations': 4},
  'POLARIZATION_INDEX': {'direction': 'decreasing',
   'trend_strength': 'moderate',
   'first_value': 0.6595744680851063,

In [24]:
complaints_df = pd.DataFrame(case["complaints"])

display(
    complaints_df[
        [
            "review_date",
            "rating",
            "language",
            "title",
            "disliked",
            "complaint_text"
        ]
    ]
)

,review_date,rating,language,title,disliked,complaint_text
0,2024-04-26,5.0,en-us,Convenient location and friendly staff contrasted by outdated facilities and disappointing room amen,"Reflecting on my stay at Hotel Mundial, there were several aspects that left me feeling underwhelmed. Firstly, the room and bathroom fell short of my expectations, with outdated furnishings and a cramped layout. The shower posed a safety concern due to its slippery floor and constant leakage, making it difficult to use comfortably. Additionally, the bedding arrangement, with two twin beds pushed together instead of a king bed as requested, was disappointing. The lack of amenities such as a steamer or iron further detracted from the overall comfort of the room. Despite the hotel's convenient location, the outdated facilities and lackluster amenities made it difficult for me to overlook these shortcomings. Overall, while there were some positive aspects to my stay, I found the hotel to be lacking in terms of value and comfort.","Disliked: Reflecting on my stay at Hotel Mundial, there were several aspects that left me feeling underwhelmed. Firstly, the room and bathroom fell short of my expectations, with outdated furnishings and a cramped layout. The shower posed a safety concern due to its slippery floor and constant leakage, making it difficult to use comfortably. Additionally, the bedding arrangement, with two twin beds pushed together instead of a king bed as requested, was disappointing. The lack of amenities such as a steamer or iron further detracted from the overall comfort of the room. Despite the hotel's convenient location, the outdated facilities and lackluster amenities made it difficult for me to overlook these shortcomings. Overall, while there were some positive aspects to my stay, I found the hotel to be lacking in terms of value and comfort."
1,2024-05-08,6.0,en-us,Pleasant,Not value for money. For the money you pay you'd expect at least a free bottle of water in the room. Breakfast is below average. Hotel is old and is a bit outdated. Doesn't have enough facilities (ex: Gym),Disliked: Not value for money. For the money you pay you'd expect at least a free bottle of water in the room. Breakfast is below average. Hotel is old and is a bit outdated. Doesn't have enough facilities (ex: Gym)
2,2024-04-30,6.0,de,Ich würde das Hotel nicht wieder buchen,A hotel that has seen better days and is in urgent need of renovation. The rooms are worn and you simply don't feel comfortable. Cleanliness also leaves much to be desired. Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.,Disliked: A hotel that has seen better days and is in urgent need of renovation. The rooms are worn and you simply don't feel comfortable. Cleanliness also leaves much to be desired. Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.
3,2024-04-23,6.0,de,Pleasant,"Stairs made of black stone. The edge is barely visible… potentially dangerous! It should be painted a light color. Large, many guests, breakfast has a high noise level, crowding 😰 The reception is often hectic as well.","Disliked: Stairs made of black stone. The edge is barely visible… potentially dangerous! It should be painted a light color. Large, many guests, breakfast has a high noise level, crowding 😰 The reception is often hectic as well."
4,2024-05-12,6.0,da,Pleasant,It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.,Disliked: It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.
5,2024-04-29,6.0,en,More training or more bet staff,Wait time with bar staff sometimes considerably long in the lounge bar,Disliked: Wait time with bar staff sometimes considerably long in the lounge bar
6,2024-05-19,7.0,nl,Comfortabel verblijf voor een stedentrip.,The bathroom is dated. If you're a bit taller you cannot sit properly on the toilet. You shower in the bathtub (which is very slippery). If you're a bit taller you don't fit well under the showerhead. There were two holes in the floor (drains?). As a result there was a sewer smell in the bathroom. We solved this by placing the bath mat over the two covers. Given the price of the room this should not happen.,Disliked: The bathroom is dated. If you're a bit taller you cannot sit properly on the toilet. You shower in the bathtub (which is very slippery). If you're a bit taller you don't fit well under the showerhead. There were two holes in the floor (drains?). As a result there was a sewer smell in the bathroom. We solved this by placing the bath mat over the two covers. Given the price of the room this should not happen.
7,2024-04-26,7.0,en-us,Would stay somewhere else.,"The fact that we tried numerous times to get a table at the Rooftop bar and got nowhere. In my opinion, preference should be given to guests that actually stay in the hotel and not to the public. One of the main reasons we chose this hotel was the Rooftop bar. Room service was non existent.","Disliked: The fact that we tried numerous times to get a table at the Rooftop bar and got nowhere. In my opinion, preference should be given to guests that actually stay in the hotel and not to the public. One of the main reasons we chose this hotel was the Rooftop bar. Room service was non existent."
8,2024-04-29,7.0,en-us,"Great location, good breakfast. Hotel towels, carpets in room- need cleaning/ updating/replacing.","The room did not seem really clean- the carpet had hairs- like pet hair- on it, bath towels were worn and had holes in them.staff were not super knowledgeable and gave us wrong advice on dinner(said no reservations allowed ) and timing to get to train station by taxi.","Disliked: The room did not seem really clean- the carpet had hairs- like pet hair- on it, bath towels were worn and had holes in them.staff were not super knowledgeable and gave us wrong advice on dinner(said no reservations allowed ) and timing to get to train station by taxi."
9,2024-05-07,7.0,it,Good,"Room cleaning was not adequate, the bathroom is dated and needs renovation. The bathtub drain was not working. Overall not up to the standard of a 4-star!","Disliked: Room cleaning was not adequate, the bathroom is dated and needs renovation. The bathtub drain was not working. Overall not up to the standard of a 4-star!"
10,2024-05-14,7.0,fr,Good,"Too much noise at night, rooms are very poorly soundproofed. The breakfast lacks regional specialties.","Disliked: Too much noise at night, rooms are very poorly soundproofed. The breakfast lacks regional specialties."
11,2024-04-25,7.0,de,Good,Our room was very dated and urgently needs renovation.,Disliked: Our room was very dated and urgently needs renovation.
12,2024-05-03,7.0,it,Good,Breakfast not up to the standard of a 4-star,Disliked: Breakfast not up to the standard of a 4-star
13,2024-05-16,8.0,de,Gutes Stadthotel,"Old doors without a proper closing mechanism mean that heavy wooden doors cannot be gently pulled closed or latched, but always slam shut. This means that at night you are woken by the slamming of the door whenever a neighbor enters their room. The breakfast is very monotonous and not particularly high-quality or healthy. There was little fresh fruit and vegetables and almost no muesli (only packet granola). The breakfast restaurant is very large and has more of a canteen character.","Disliked: Old doors without a proper closing mechanism mean that heavy wooden doors cannot be gently pulled closed or latched, but always slam shut. This means that at night you are woken by the slamming of the door whenever a neighbor enters their room. The breakfast is very monotonous and not particularly high-quality or healthy. There was little fresh fruit and vegetables and almost no muesli (only packet granola). The breakfast restaurant is very large and has more of a canteen character."
14,2024-05-18,8.0,de,Very good,"A bit too loud to sleep. No hair conditioner or body lotion. I had a small emergency (during my stay I got my period); unfortunately the hotel reception had neither tampons nor pads, it was midnight and the shops were closed... A bit annoying. It would be nice if the hotel offered such items for such cases.","Disliked: A bit too loud to sleep. No hair conditioner or body lotion. I had a small emergency (during my stay I got my period); unfortunately the hotel reception had neither tampons nor pads, it was midnight and the shops were closed... A bit annoying. It would be nice if the hotel offered such items for such cases."
15,2024-05-11,8.0,nl,Very good,"As a 70-year-old in a room with only one power outlet, having to lie on my stomach under the desk every day to plug my mobile phone into the charger...","Disliked: As a 70-year-old in a room with only one power outlet, having to lie on my stomach under the desk every day to plug my mobile phone into the charger..."
16,2024-05-02,8.0,de,Perfekte Lage für einen Kurztrip,Unfortunately the room staff were not on the ball; we had to ask reception several times for toilet paper and towels. At 4 stars I expect a bit more.,Disliked: Unfortunately the room staff were not on the ball; we had to ask reception several times for toilet paper and towels. At 4 stars I expect a bit more.
17,2024-04-28,8.0,de,Ein Hotel in toller Lage mitten in Lissabon,Has seen better days; the breakfast situation is not cozy; there are many tour groups so it was also a bit noisy; the parking is very tight.,Disliked: Has seen better days; the breakfast situation is not cozy; there are many tour groups so it was also a bit noisy; the parking is very tight.
18,2024-04-23,8.0,fr,Idéalement placé,Room 634 was spacious and ideal for three but the windows were not well insulated against noise.,Disliked: Room 634 was spacious and ideal for three but the windows were not well insulated against noise.
19,2024-04-27,8.0,fr,Hôtel très bien situé,"Very noisy in the streets near the hotel, which makes it impossible to sleep with the window open.","Disliked: Very noisy in the streets near the hotel, which makes it impossible to sleep with the window open."

In [25]:
case["trends"]["EXPECTATION_VIOLATION_RATIO"]

{'direction': 'increasing',
 'trend_strength': 'weak',
 'first_value': 0.9230769230769232,
 'last_value': 1.0,
 'minimum_value': 0.8333333333333334,
 'maximum_value': 1.0,
 'absolute_change': 0.07692307692307676,
 'percentage_change': 8.333333333333314,
 'slope': 0.020695970695970567,
 'standardized_slope': 0.3196522241219279,
 'direction_consistency': 0.3333333333333333,
 'recent_movement': 'up',
 'recent_absolute_change': 0.16666666666666663,
 'recent_reversal': False,
 'n_observations': 4}

In [26]:
pd.DataFrame(case["preliminary_signals"])

,signal,severity,metric,description,trend_strength,direction_consistency,recent_movement,recent_reversal
0,declining_sentiment,medium,SENTIMENT_SCORE_AVG,O sentimento médio apresenta uma tendência global decrescente.,moderate,0.666667,up,True
1,increasing_expectation_gap,high,EXPECTATION_EXPERIENCE_GAP_AVG,A discrepância entre expectativas e experiência apresenta uma tendência global crescente.,moderate,0.666667,down,True
2,increasing_misalignment,high,SEMANTIC_MISALIGNMENT_SCORE_AVG,O desalinhamento semântico apresenta uma tendência global crescente.,moderate,0.666667,down,True
3,increasing_emotional_complexity,medium,EMOTION_ENTROPY,A heterogeneidade emocional apresenta uma tendência global crescente.,moderate,0.666667,down,True

In [27]:
case.keys()

dict_keys(['case_metadata', 'hotel_profile', 'latest_context', 'metric_definitions', 'weekly_history', 'trends', 'topic_summary', 'preliminary_signals', 'complaints', 'complaint_metadata'])

In [28]:
case["case_metadata"]

{'case_id': 'H149_20240513_L4',
 'hotel_id': 149,
 'decision_week': '2024_W20',
 'decision_date': '2024-05-13',
 'window_start': '2024-04-22',
 'window_end': '2024-05-19',
 'lookback_weeks_requested': 4,
 'panel_weeks_available': 4,
 'complete_window': True}

In [29]:
pd.DataFrame(case["weekly_history"])

,WEEK_YEAR,week_date,REVPAR_WEEK,REVPOR_WEEK,TREVPAR_WEEK,TAXA_OCUPACAO,N_REVIEWS,AVG_RATING,SENTIMENT_SCORE_AVG,SENTIMENT_SCORE_STD,EXPECTATION_EXPERIENCE_GAP_AVG,SEMANTIC_MISALIGNMENT_SCORE_AVG,EXPECTATION_VIOLATION_RATIO,MAJOR_MISALIGNMENT_SHARE,EMOTION_ENTROPY,EXPECTATION_SHARE,HIGH_EXPECTATION_SHARE,HIGH_MISALIGNMENT_SHARE,PERC_REVIEWS_NEGATIVE,PERC_OPERATIONAL_COMPLAINTS,PERC_PRICE_VALUE_MENTIONS,POLARIZATION_INDEX,COMPLEXITY_INDEX,SENTIMENT_TREND_SLOPE
0,2024_W17,2024-04-22,137.790886,211.502883,183.412690,89.111748,47.0,8.808511,0.348485,0.621473,0.079167,0.083333,0.923077,0.000000,1.339716,0.170213,0.042553,0.063830,63.829787,14.285714,0.0,0.659574,2.564026,0.000471
1,2024_W18,2024-04-29,138.889038,298.690364,184.108465,89.070815,41.0,8.585366,0.277778,0.608608,0.120370,0.135185,0.857143,0.000000,1.385725,0.170732,0.048780,0.097561,43.902439,26.666667,0.0,0.585366,2.746082,0.000471
2,2024_W19,2024-05-06,152.305982,248.980277,197.277034,84.076955,31.0,8.612903,0.175000,0.615995,0.234615,0.250000,0.833333,0.064516,1.465536,0.193548,0.129032,0.129032,41.935484,18.181818,0.0,0.612903,2.847243,0.000471
3,2024_W20,2024-05-13,154.482965,261.135678,209.317863,87.392550,40.0,8.575000,0.285106,0.605044,0.124074,0.144444,1.000000,0.000000,1.404892,0.200000,0.000000,0.100000,50.000000,17.647059,0.0,0.500000,2.611646,0.000471

In [30]:
trend_table = (
    pd.DataFrame(case["trends"])
    .T
    .reset_index()
    .rename(columns={"index": "metric"})
)

display(trend_table)

,metric,direction,trend_strength,first_value,last_value,minimum_value,maximum_value,absolute_change,percentage_change,slope,standardized_slope,direction_consistency,recent_movement,recent_absolute_change,recent_reversal,n_observations
0,REVPAR_WEEK,increasing,consistent,137.790886,154.482965,137.790886,154.482965,16.692079,12.114066,6.349318,0.838032,1.0,up,2.176983,False,4
1,REVPOR_WEEK,increasing,moderate,211.502883,261.135678,211.502883,298.690364,49.632794,23.466722,9.91883,0.318692,0.666667,up,12.155401,False,4
2,TREVPAR_WEEK,increasing,consistent,183.41269,209.317863,183.41269,209.317863,25.905173,14.123981,9.088409,0.852684,1.0,up,12.040829,False,4
3,TAXA_OCUPACAO,decreasing,moderate,89.111748,87.39255,84.076955,89.111748,-1.719198,-1.92926,-1.015145,-0.495876,0.666667,up,3.315596,True,4
4,N_REVIEWS,decreasing,moderate,47.0,40.0,31.0,47.0,-7.0,-14.893617,-3.1,-0.542214,0.666667,up,9.0,True,4
5,AVG_RATING,decreasing,moderate,8.808511,8.575,8.575,8.808511,-0.233511,-2.650966,-0.067299,-0.707227,0.666667,down,-0.037903,False,4
6,SENTIMENT_SCORE_AVG,decreasing,moderate,0.348485,0.285106,0.175,0.348485,-0.063378,-18.186864,-0.029291,-0.471103,0.666667,up,0.110106,True,4
7,SENTIMENT_SCORE_STD,decreasing,moderate,0.621473,0.605044,0.605044,0.621473,-0.016429,-2.643598,-0.00419,-0.656069,0.666667,down,-0.010952,False,4
8,EXPECTATION_EXPERIENCE_GAP_AVG,increasing,moderate,0.079167,0.124074,0.079167,0.234615,0.044907,56.725146,0.024897,0.431911,0.666667,down,-0.110541,True,4
9,SEMANTIC_MISALIGNMENT_SCORE_AVG,increasing,moderate,0.083333,0.144444,0.083333,0.25,0.061111,73.333333,0.029815,0.492609,0.666667,down,-0.105556,True,4
10,EXPECTATION_VIOLATION_RATIO,increasing,weak,0.923077,1.0,0.833333,1.0,0.076923,8.333333,0.020696,0.319652,0.333333,up,0.166667,False,4
11,MAJOR_MISALIGNMENT_SHARE,fluctuating,fluctuating,0.0,0.0,0.0,0.064516,0.0,None,0.006452,0.23094,0.333333,down,-0.064516,False,4
12,EMOTION_ENTROPY,increasing,moderate,1.339716,1.404892,1.339716,1.465536,0.065176,4.864924,0.027534,0.60989,0.666667,down,-0.060644,True,4
13,EXPECTATION_SHARE,increasing,consistent,0.170213,0.2,0.170213,0.2,0.029787,17.5,0.011218,0.840376,1.0,up,0.006452,False,4
14,HIGH_EXPECTATION_SHARE,fluctuating,fluctuating,0.042553,0.0,0.0,0.129032,-0.042553,-100.0,-0.004741,-0.101657,0.666667,down,-0.129032,False,4
15,HIGH_MISALIGNMENT_SHARE,increasing,moderate,0.06383,0.1,0.06383,0.129032,0.03617,56.666667,0.013998,0.60602,0.666667,down,-0.029032,True,4
16,PERC_REVIEWS_NEGATIVE,decreasing,moderate,63.829787,50.0,41.935484,63.829787,-13.829787,-21.666667,-4.345632,-0.507358,0.666667,up,8.064516,True,4
17,PERC_OPERATIONAL_COMPLAINTS,fluctuating,fluctuating,14.285714,17.647059,14.285714,26.666667,3.361345,23.529412,0.159919,0.035033,0.666667,down,-0.534759,False,4
18,PERC_PRICE_VALUE_MENTIONS,stable,stable,0.0,0.0,0.0,0.0,0.0,None,0.0,0.0,1.0,flat,0.0,False,4
19,POLARIZATION_INDEX,decreasing,moderate,0.659574,0.5,0.5,0.659574,-0.159574,-24.193548,-0.045119,-0.777056,0.666667,down,-0.112903,False,4
20,COMPLEXITY_INDEX,increasing,moderate,2.564026,2.611646,2.564026,2.847243,0.04762,1.857255,0.024402,0.218569,0.666667,down,-0.235597,True,4
21,SENTIMENT_TREND_SLOPE,stable,stable,0.000471,0.000471,0.000471,0.000471,0.0,0.0,-0.0,0.0,1.0,flat,0.0,False,4

In [31]:
display(
    trend_table[
        trend_table["direction"].isin(
            ["increasing", "decreasing"]
        )
    ][
        [
            "metric",
            "direction",
            "first_value",
            "last_value",
            "absolute_change",
            "percentage_change",
            "standardized_slope"
        ]
    ]
)

,metric,direction,first_value,last_value,absolute_change,percentage_change,standardized_slope
0,REVPAR_WEEK,increasing,137.790886,154.482965,16.692079,12.114066,0.838032
1,REVPOR_WEEK,increasing,211.502883,261.135678,49.632794,23.466722,0.318692
2,TREVPAR_WEEK,increasing,183.41269,209.317863,25.905173,14.123981,0.852684
3,TAXA_OCUPACAO,decreasing,89.111748,87.39255,-1.719198,-1.92926,-0.495876
4,N_REVIEWS,decreasing,47.0,40.0,-7.0,-14.893617,-0.542214
5,AVG_RATING,decreasing,8.808511,8.575,-0.233511,-2.650966,-0.707227
6,SENTIMENT_SCORE_AVG,decreasing,0.348485,0.285106,-0.063378,-18.186864,-0.471103
7,SENTIMENT_SCORE_STD,decreasing,0.621473,0.605044,-0.016429,-2.643598,-0.656069
8,EXPECTATION_EXPERIENCE_GAP_AVG,increasing,0.079167,0.124074,0.044907,56.725146,0.431911
9,SEMANTIC_MISALIGNMENT_SCORE_AVG,increasing,0.083333,0.144444,0.061111,73.333333,0.492609
10,EXPECTATION_VIOLATION_RATIO,increasing,0.923077,1.0,0.076923,8.333333,0.319652
12,EMOTION_ENTROPY,increasing,1.339716,1.404892,0.065176,4.864924,0.60989
13,EXPECTATION_SHARE,increasing,0.170213,0.2,0.029787,17.5,0.840376
15,HIGH_MISALIGNMENT_SHARE,increasing,0.06383,0.1,0.03617,56.666667,0.60602
16,PERC_REVIEWS_NEGATIVE,decreasing,63.829787,50.0,-13.829787,-21.666667,-0.507358
19,POLARIZATION_INDEX,decreasing,0.659574,0.5,-0.159574,-24.193548,-0.777056
20,COMPLEXITY_INDEX,increasing,2.564026,2.611646,0.04762,1.857255,0.218569

In [32]:
case["topic_summary"]

{'raw_weekly_topics': {'EXPECTATION_TOPICS_UNIQUE': [{'topic': 'ability to reserve parking',
    'weeks_present': 1},
   {'topic': 'ability to reserve tables', 'weeks_present': 1},
   {'topic': 'ability to use rooftop terrace without mandatory gastronomy use',
    'weeks_present': 1},
   {'topic': 'access to rooftop terrace', 'weeks_present': 1},
   {'topic': 'adequate room cleanliness / regular housekeeping',
    'weeks_present': 1},
   {'topic': 'availability of basic in-room amenities (steamer/iron)',
    'weeks_present': 1},
   {'topic': 'availability of basic toiletries at hotel (hair conditioner, body lotion)',
    'weeks_present': 1},
   {'topic': 'availability of emergency feminine hygiene products at hotel (tampons, pads)',
    'weeks_present': 1},
   {'topic': 'bathroom condition appropriate for the price / value',
    'weeks_present': 1},
   {'topic': 'bathroom renovation / improved bathroom condition',
    'weeks_present': 1}],
  'EXPERIENCE_TOPICS_UNIQUE': [{'topic': 'breakfast', 'weeks_present': 4},
   {'topic': 'breakfast quality', 'weeks_present': 4},
   {'topic': 'cleanliness', 'weeks_present': 4},
   {'topic': 'location', 'weeks_present': 4},
   {'topic': 'rooftop bar', 'weeks_present': 4},
   {'topic': 'room comfort', 'weeks_present': 4},
   {'topic': 'room size', 'weeks_present': 4},
   {'topic': 'staff friendliness', 'weeks_present': 4},
   {'topic': 'staff helpfulness', 'weeks_present': 4},
   {'topic': 'bed comfort', 'weeks_present': 3}],
  'VIOLATED_EXPECTATION_TOPICS_UNIQUE': [{'topic': 'ability to reserve parking',
    'weeks_present': 1},
   {'topic': 'ability to reserve tables', 'weeks_present': 1},
   {'topic': 'ability to use rooftop terrace without mandatory gastronomy use',
    'weeks_present': 1},
   {'topic': 'access to rooftop terrace', 'weeks_present': 1},
   {'topic': 'adequate room cleanliness / regular housekeeping',
    'weeks_present': 1},
   {'topic': 'availability of basic in-room amenities (steamer/iron)',
    'weeks_present': 1},
   {'topic': 'availability of basic toiletries at hotel (hair conditioner, body lotion)',
    'weeks_present': 1},
   {'topic': 'availability of emergency feminine hygiene products at hotel (tampons, pads)',
    'weeks_present': 1},
   {'topic': 'bathroom condition appropriate for the price / value',
    'weeks_present': 1},
   {'topic': 'bathroom renovation / improved bathroom condition',
    'weeks_present': 1}],
  'LATENT_EXPECTATION_TOPICS_UNIQUE': [{'topic': 'ability to reserve parking',
    'weeks_present': 1},
   {'topic': 'ability to reserve terrace tables', 'weeks_present': 1},
   {'topic': 'acceptable value/comfort for the hotel', 'weeks_present': 1},
   {'topic': 'access to rooftop bar/restaurant', 'weeks_present': 1},
   {'topic': 'adequate room cleanliness / regular housekeeping',
    'weeks_present': 1},
   {'topic': 'amenities advertised/featured (rooftop) usable without extra purchase',
    'weeks_present': 1},
   {'topic': 'availability of basic toiletries at hotel (hair conditioner, body lotion)',
    'weeks_present': 1},
   {'topic': 'availability of emergency feminine hygiene products at hotel (tampons, pads)',
    'weeks_present': 1},
   {'topic': 'bathroom storage / shelves', 'weeks_present': 1},
   {'topic': 'bathroom usability and safety (non-slip surfaces, adequate shower height, comfortable toilet for taller guests)',
    'weeks_present': 1}],
  'EMERGING_NEGATIVE_TOPIC': [{'topic': 'bar/restaurant access',
    'weeks_present': 1},
   {'topic': 'cocktails', 'weeks_present': 1},
   {'topic': 'difficulties with rooftop reservations', 'weeks_present': 1},
   {'topic': 'infrastructure', 'weeks_present': 1},
   {'topic': 'neck pain', 'weeks_present': 1},
   {'topic': 'no showers', 'weeks_present': 1},
   {'topic': 'overpriced', 'weeks_present': 1},
   {'topic': 'parking cost', 'weeks_present': 1},
   {'topic': 'parking reservation', 'weeks_present': 1},
   {'topic': 'payment issue', 'weeks_present': 1}]},
 'managerial_categories': [{'category': 'breakfast',
   'label': 'Breakfast',
   'managerial_domain': 'food_and_beverage',
   'default_priority': 'medium',
   'weeks_present': 4,
   'experience_weeks': 4,
   'expectation_weeks': 0,
   'violated_expectation_weeks': 0,
   'latent_expectation_weeks': 0,
   'emerging_negative_weeks': 0,
   'cross_structure_topic_occurrences': 8,
   'review_mentions_total': 50,
   'positive_review_mentions': 34,
   'negative_review_mentions': 16,
   'net_sentiment_mentions': 18,
   'matched_raw_topics': ['breakfast', 'breakfast quality'],
   'source_columns': ['EXPERIENCE_TOPICS_UNIQUE']},
  {'category': 'restaurant_bar',
   'label': 'Restaurant and bar',
   'managerial_domain': 'food_and_beverage',
   'default_priority': 'medium',
   'weeks_present': 4,
   'experience_weeks': 4,
   'expectation_weeks': 1,
   'violated_expectation_weeks': 1,
   'latent_expectation_weeks': 1,
   'emerging_negative_weeks': 1,
   'cross_structure_topic_occurrences': 8,
   'review_mentions_total': 29,
   'positive_review_mentions': 20,
   'negative_review_mentions': 13,
   'net_sentiment_mentions': 7,
   'matched_raw_topics': ['ability to reserve tables',
    'access to rooftop bar/restaurant',
    'bar/restaurant access',
    'rooftop bar'],
   'source_columns': ['EMERGING_NEGATIVE_TOPIC',
    'EXPECTATION_TOPICS_UNIQUE',
    'EXPERIENCE_TOPICS_UNIQUE',
    'LATENT_EXPECTATION_TOPICS_UNIQUE',
    'VIOLATED_EXPECTATION_TOPICS_UNIQUE']},
  {'category': 'price_value',
   'label': 'Price–value',
   'managerial_domain': 'pricing_and_value',
   'default_priority': 'high',
   'weeks_present': 1,
   'experience_weeks': 0,
   'expectation_weeks': 1,
   'violated_expectation_weeks': 1,
   'latent_expectation_weeks': 1,
   'emerging_negative_weeks': 1,
   'cross_structure_topic_occurrences': 5,
   'review_mentions_total': 18,
   'positive_review_mentions': 6,
   'negative_review_mentions': 12,
   'net_sentiment_mentions': -6,
   'matched_raw_topics': ['acceptable value/comfort for the hotel',
    'bathroom condition appropriate for the price / value',
    'overpriced',
    'parking cost'],
   'source_columns': ['EMERGING_NEGATIVE_TOPIC',
    'EXPECTATION_TOPICS_UNIQUE',
    'LATENT_EXPECTATION_TOPICS_UNIQUE',
    'VIOLATED_EXPECTATION_TOPICS_UNIQUE']},
  {'category': 'room_comfort',
   'label': 'Room comfort',
   'managerial_domain': 'rooms_and_maintenance',
   'default_priority': 'high',
   'weeks_present': 4,
   'experience_weeks': 4,
   'expectation_weeks': 0,
   'violated_expectation_weeks': 0,
   'latent_expectation_weeks': 0,
   'emerging_negative_weeks': 0,
   'cross_structure_topic_occurrences': 11,
   'review_mentions_total': 19,
   'positive_review_mentions': 8,
   'negative_review_mentions': 11,
   'net_sentiment_mentions': -3,
   'matched_raw_topics': ['bed comfort', 'room comfort', 'room size'],
   'source_columns': ['EXPERIENCE_TOPICS_UNIQUE']},
  {'category': 'bathroom',
   'label': 'Bathroom condition',
   'managerial_domain': 'rooms_and_maintenance',
   'default_priority': 'high',
   'weeks_present': 1,
   'experience_weeks': 0,
   'expectation_weeks': 1,
   'violated_expectation_weeks': 1,
   'latent_expectation_weeks': 1,
   'emerging_negative_weeks': 0,
   'cross_structure_topic_occurrences': 9,
   'review_mentions_total': 14,
   'positive_review_mentions': 5,
   'negative_review_mentions': 9,
   'net_sentiment_mentions': -4,
   'matched_raw_topics': ['availability of basic toiletries at hotel (hair conditioner, body lotion)',
    'bathroom condition appropriate for the price / value',
    'bathroom renovation / improved bathroom condition',
    'bathroom storage / shelves',
    'bathroom usability and safety (non-slip surfaces, adequate shower height, comfortable toilet for taller guests)'],
   'source_columns': ['EXPECTATION_TOPICS_UNIQUE',
    'LATENT_EXPECTATION_TOPICS_UNIQUE',
    'VIOLATED_EXPECTATION_TOPICS_UNIQUE']},
  {'category': 'rooftop_access',
   'label': 'Rooftop access',
   'managerial_domain': 'access_and_facilities',
   'default_priority': 'medium',
   'weeks_present': 4,
   'experience_weeks': 4,
   'expectation_weeks': 1,
   'violated_expectation_weeks': 1,
   'latent_expectation_weeks': 1,
   'emerging_negative_weeks': 1,
   'cross_structure_topic_occurrences': 11,
   'review_mentions_total': 29,
   'positive_review_mentions': 24,
   'negative_review_mentions': 8,
   'net_sentiment_mentions': 16,
   'matched_raw_topics': ['ability to use rooftop terrace without mandatory gastronomy use',
    'access to rooftop bar/restaurant',
    'access to rooftop terrace',
    'amenities advertised/featured (rooftop) usable without extra purchase',
    'difficulties with rooftop reservations',
    'rooftop bar'],
   'source_columns': ['EMERGING_NEGATIVE_TOPIC',
    'EXPECTATION_TOPICS_UNIQUE',
    'EXPERIENCE_TOPICS_UNIQUE',
    'LATENT_EXPECTATION_TOPICS_UNIQUE',
    'VIOLATED_EXPECTATION_TOPICS_UNIQUE']},
  {'category': 'staff_service',
   'label': 'Staff and service',
   'managerial_domain': 'service_delivery',
   'default_priority': 'high',
   'weeks_present': 4,
   'experience_weeks': 4,
   'expectation_weeks': 0,
   'violated_expectation_weeks': 0,
   'latent_expectation_weeks': 0,
   'emerging_negative_weeks': 0,
   'cross_structure_topic_occurrences': 8,
   'review_mentions_total': 55,
   'positive_review_mentions': 46,
   'negative_review_mentions': 8,
   'net_sentiment_mentions': 38,
   'matched_raw_topics': ['staff friendliness', 'staff helpfulness'],
   'source_columns': ['EXPERIENCE_TOPICS_UNIQUE']},
  {'category': 'cleanliness',
   'label': 'Cleanliness and housekeeping',
   'managerial_domain': 'housekeeping',
   'default_priority': 'high',
   'weeks_present': 4,
   'experience_weeks': 4,
   'expectation_weeks': 1,
   'violated_expectation_weeks': 1,
   'latent_expectation_weeks': 1,
   'emerging_negative_weeks': 0,
   'cross_structure_topic_occurrences': 7,
   'review_mentions_total': 18,
   'positive_review_mentions': 14,
   'negative_review_mentions': 5,
   'net_sentiment_mentions': 9,
   'matched_raw_topics': ['adequate room cleanliness / regular housekeeping',
    'cleanliness'],
   'source_columns': ['EXPECTATION_TOPICS_UNIQUE',
    'EXPERIENCE_TOPICS_UNIQUE',
    'LATENT_EXPECTATION_TOPICS_UNIQUE',
    'VIOLATED_EXPECTATION_TOPICS_UNIQUE']},
  {'category': 'parking',
   'label': 'Parking',
   'managerial_domain': 'access_and_facilities',
   'default_priority': 'medium',
   'weeks_present': 1,
   'experience_weeks': 0,
   'expectation_weeks': 1,
   'violated_expectation_weeks': 1,
   'latent_expectation_weeks': 1,
   'emerging_negative_weeks': 1,
   'cross_structure_topic_occurrences': 5,
   'review_mentions_total': 6,
   'positive_review_mentions': 4,
   'negative_review_mentions': 3,
   'net_sentiment_mentions': 1,
   'matched_raw_topics': ['ability to reserve parking',
    'parking cost',
    'parking reservation'],
   'source_columns': ['EMERGING_NEGATIVE_TOPIC',
    'EXPECTATION_TOPICS_UNIQUE',
    'LATENT_EXPECTATION_TOPICS_UNIQUE',
    'VIOLATED_EXPECTATION_TOPICS_UNIQUE']},
  {'category': 'room_amenities',
   'label': 'In-room amenities',
   'managerial_domain': 'rooms_and_maintenance',
   'default_priority': 'medium',
   'weeks_present': 1,
   'experience_weeks': 0,
   'expectation_weeks': 1,
   'violated_expectation_weeks': 1,
   'latent_expectation_weeks': 1,
   'emerging_negative_weeks': 0,
   'cross_structure_topic_occurrences': 3,
   'review_mentions_total': 3,
   'positive_review_mentions': 2,
   'negative_review_mentions': 2,
   'net_sentiment_mentions': 0,
   'matched_raw_topics': ['amenities advertised/featured (rooftop) usable without extra purchase',
    'availability of basic in-room amenities (steamer/iron)'],
   'source_columns': ['EXPECTATION_TOPICS_UNIQUE',
    'LATENT_EXPECTATION_TOPICS_UNIQUE',
    'VIOLATED_EXPECTATION_TOPICS_UNIQUE']}],
 'interpretation_note': 'Topic-source metrics must be interpreted separately. experience_weeks may include positive or neutral experiences. violated_expectation_weeks and emerging_negative_weeks indicate negative evidence. negative_review_mentions are based only on review_text_disliked. Cross-structure topic occurrences may refer to the same underlying issue and are not independent complaints.'}

In [33]:
case["latest_context"]

{'dominant_emotion': 'joy',
 'dominant_expectation_experience_label': 'experience_only',
 'season': 'Low',
 'priority_alert_flag': 0.0,
 'emerging_negative_topic': ['overpriced',
  'shower experience',
  'toilet comfort',
  'space',
  'no showers',
  'cocktails']}

In [34]:
case["trends"]["EXPECTATION_EXPERIENCE_GAP_AVG"]

{'direction': 'increasing',
 'trend_strength': 'moderate',
 'first_value': 0.0791666666666666,
 'last_value': 0.124074074074074,
 'minimum_value': 0.0791666666666666,
 'maximum_value': 0.2346153846153846,
 'absolute_change': 0.04490740740740741,
 'percentage_change': 56.725146198830465,
 'slope': 0.024896723646723632,
 'standardized_slope': 0.4319111355690588,
 'direction_consistency': 0.6666666666666666,
 'recent_movement': 'down',
 'recent_absolute_change': -0.11054131054131058,
 'recent_reversal': True,
 'n_observations': 4}

# AGENT CONTEXT

In [35]:
from src.agent_context import (
    build_agent_context
)

In [36]:
agent_context = build_agent_context(
    case,
    top_n_categories=8,
    max_complaints=12
)

In [37]:
agent_context.keys()

dict_keys(['context_metadata', 'case', 'hotel', 'latest_context', 'business_performance', 'experience_indicators', 'preliminary_signals', 'managerial_evidence', 'diagnostic_vulnerabilities', 'strengths', 'complaint_evidence', 'complaint_sample_metadata', 'interpretation_rules'])

In [38]:
pd.DataFrame(
    agent_context[
        "diagnostic_vulnerabilities"
    ]
)

,area,managerial_domain,default_priority,review_mentions_total,positive_mentions,negative_mentions,net_mentions,positive_share,negative_share,experience_weeks,expectation_weeks,violated_expectation_weeks,emerging_negative_weeks,has_expectation_violation,is_emerging_negative,evidence_pattern,matched_topics,source_columns,diagnostic_score,diagnostic_score_components
0,Price–value,pricing_and_value,high,18,6,12,-6,0.333,0.667,0,1,1,1,True,True,net_negative,"[acceptable value/comfort for the hotel, bathroom condition appropriate for the price / value, overpriced, parking cost]","[EMERGING_NEGATIVE_TOPIC, EXPECTATION_TOPICS_UNIQUE, LATENT_EXPECTATION_TOPICS_UNIQUE, VIOLATED_EXPECTATION_TOPICS_UNIQUE]",24,"{'negative_frequency': 10, 'net_negative': 3, 'negative_share': 2, 'expectation_violation': 4, 'emerging_negative': 3, 'default_priority': 2}"
1,Bathroom condition,rooms_and_maintenance,high,14,5,9,-4,0.357,0.643,0,1,1,0,True,False,net_negative,"[availability of basic toiletries at hotel (hair conditioner, body lotion), bathroom condition appropriate for the price / value, bathroom renovation / improved bathroom condition, bathroom storage / shelves, bathroom usability and safety (non-slip surfaces, adequate shower height, comfortable toilet for taller guests)]","[EXPECTATION_TOPICS_UNIQUE, LATENT_EXPECTATION_TOPICS_UNIQUE, VIOLATED_EXPECTATION_TOPICS_UNIQUE]",20,"{'negative_frequency': 9, 'net_negative': 3, 'negative_share': 2, 'expectation_violation': 4, 'emerging_negative': 0, 'default_priority': 2}"
2,Restaurant and bar,food_and_beverage,medium,29,20,13,7,0.606,0.394,4,1,1,1,True,True,positive_with_friction,"[ability to reserve tables, access to rooftop bar/restaurant, bar/restaurant access, rooftop bar]","[EMERGING_NEGATIVE_TOPIC, EXPECTATION_TOPICS_UNIQUE, EXPERIENCE_TOPICS_UNIQUE, LATENT_EXPECTATION_TOPICS_UNIQUE, VIOLATED_EXPECTATION_TOPICS_UNIQUE]",17,"{'negative_frequency': 10, 'net_negative': 0, 'negative_share': 0, 'expectation_violation': 4, 'emerging_negative': 3, 'default_priority': 0}"
3,Room comfort,rooms_and_maintenance,high,19,8,11,-3,0.421,0.579,4,0,0,0,False,False,net_negative,"[bed comfort, room comfort, room size]",[EXPERIENCE_TOPICS_UNIQUE],16,"{'negative_frequency': 10, 'net_negative': 3, 'negative_share': 1, 'expectation_violation': 0, 'emerging_negative': 0, 'default_priority': 2}"
4,Rooftop access,access_and_facilities,medium,29,24,8,16,0.750,0.250,4,1,1,1,True,True,positive_with_friction,"[ability to use rooftop terrace without mandatory gastronomy use, access to rooftop bar/restaurant, access to rooftop terrace, amenities advertised/featured (rooftop) usable without extra purchase, difficulties with rooftop reservations, rooftop bar]","[EMERGING_NEGATIVE_TOPIC, EXPECTATION_TOPICS_UNIQUE, EXPERIENCE_TOPICS_UNIQUE, LATENT_EXPECTATION_TOPICS_UNIQUE, VIOLATED_EXPECTATION_TOPICS_UNIQUE]",15,"{'negative_frequency': 8, 'net_negative': 0, 'negative_share': 0, 'expectation_violation': 4, 'emerging_negative': 3, 'default_priority': 0}"
5,Cleanliness and housekeeping,housekeeping,high,18,14,5,9,0.737,0.263,4,1,1,0,True,False,positive_with_friction,"[adequate room cleanliness / regular housekeeping, cleanliness]","[EXPECTATION_TOPICS_UNIQUE, EXPERIENCE_TOPICS_UNIQUE, LATENT_EXPECTATION_TOPICS_UNIQUE, VIOLATED_EXPECTATION_TOPICS_UNIQUE]",11,"{'negative_frequency': 5, 'net_negative': 0, 'negative_share': 0, 'expectation_violation': 4, 'emerging_negative': 0, 'default_priority': 2}"

In [39]:
pd.DataFrame(
    agent_context[
        "strengths"
    ]
)

,area,positive_mentions,negative_mentions,positive_share,strength_type,has_expectation_violation,is_emerging_negative
0,Staff and service,46,8,0.852,clear_strength,False,False
1,Breakfast,34,16,0.680,clear_strength,False,False
2,Rooftop access,24,8,0.750,strength_with_friction,True,True
3,Cleanliness and housekeeping,14,5,0.737,strength_with_friction,True,False

In [40]:
pd.DataFrame(
    agent_context[
        "complaint_evidence"
    ]
)

,review_date,rating,original_language,complaint,positive_context,country,stay_type
0,2024-04-26,5.0,en-us,"Disliked: Reflecting on my stay at Hotel Mundial, there were several aspects that left me feeling underwhelmed. Firstly, the room and bathroom fell short of my expectations, with outdated furnishings and a cramped layout. The shower posed a safety concern due to its slippery floor and constant leakage, making it difficult to use comfortably. Additionally, the bedding arrangement, with two twin beds pushed together instead of a king bed as requested, was disappointing. The lack of amenities such as a steamer or iron further detracted from the overall comfort of the room. Despite the hotel's convenient location, the outdated facilities and lackluster amenities made it difficult for me to overlook these shortcomings. Overall, while there were some positive aspects to my stay, I found the hotel to be lacking in terms of value and comfort.","In terms of what I liked about Hotel Mundial, there were definitely some positives to highlight amidst the mixed experience. Firstly, the hotel's prime location stood out to me as a major advantage. Being close to many of Lisbon's main attractions and cities made exploring the area incredibly convenient. Additionally, the restaurant offered a picturesque view, and I particularly enjoyed the octopus salad we had for dinner. The abundance of breakfast choices was also a plus, even though I wished the quality of the food matched the variety. Finally, the staff were friendly and accommodating, which added a welcoming touch to our stay.",United States,Couple
1,2024-05-08,6.0,en-us,Disliked: Not value for money. For the money you pay you'd expect at least a free bottle of water in the room. Breakfast is below average. Hotel is old and is a bit outdated. Doesn't have enough facilities (ex: Gym),Location is very central. Beds are comfortable and shower was good. Staff were great and very helpful!,United Kingdom,Couple
2,2024-04-30,6.0,de,Disliked: A hotel that has seen better days and is in urgent need of renovation. The rooms are worn and you simply don't feel comfortable. Cleanliness also leaves much to be desired. Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.,The hotel stands out for its location and the beautiful rooftop terrace.,Germany,Couple
3,2024-04-23,6.0,de,"Disliked: Stairs made of black stone. The edge is barely visible… potentially dangerous! It should be painted a light color. Large, many guests, breakfast has a high noise level, crowding 😰 The reception is often hectic as well.",Location,Switzerland,Solo traveller
4,2024-05-12,6.0,da,Disliked: It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.,The location,Denmark,Group
5,2024-04-29,6.0,en,Disliked: Wait time with bar staff sometimes considerably long in the lounge bar,Roof top bar and location,United Kingdom,Group
6,2024-05-19,7.0,nl,Disliked: The bathroom is dated. If you're a bit taller you cannot sit properly on the toilet. You shower in the bathtub (which is very slippery). If you're a bit taller you don't fit well under the showerhead. There were two holes in the floor (drains?). As a result there was a sewer smell in the bathroom. We solved this by placing the bath mat over the two covers. Given the price of the room this should not happen.,The staff are more than friendly and helpful. You really feel welcome as a guest. The breakfast is excellent. The upstairs restaurant is also worth it. The hotel is located close to public transport. No request or effort is too much. Every day a bottle of water was placed in the room.,Netherlands,Couple
7,2024-04-26,7.0,en-us,"Disliked: The fact that we tried numerous times to get a table at the Rooftop bar and got nowhere. In my opinion, preference should be given to guests that actually stay in the hotel and not to the public. One of the main reasons we chose this hotel was the Rooftop bar. Room service was non existent.","We loved the location. We loved the spacious sunny balcony. The complimentary bottle of wine and Portuguese pastry was a nice touch. And front office staff were informative, efficient and friendly.",Malaysia,Couple
8,2024-04-29,7.0,en-us,"Disliked: The room did not seem really clean- the carpet had hairs- like pet hair- on it, bath towels were worn and had holes in them.staff were not super knowledgeable and gave us wrong advice on dinner(said no reservations allowed ) and timing to get to train station by taxi.","Fantastic location, corner room on upper level had nice views. Comfortable bed",United States,Couple
9,2024-05-07,7.0,it,"Disliked: Room cleaning was not adequate, the bathroom is dated and needs renovation. The bathtub drain was not working. Overall not up to the standard of a 4-star!","Excellent location, convenient for transport services and for reaching the various areas of the city. However, the hotel's entrance is located on a poorly frequented square. Very rich and abundant breakfast. Friendly staff.",Italy,Family
10,2024-05-14,7.0,fr,"Disliked: Too much noise at night, rooms are very poorly soundproofed. The breakfast lacks regional specialties.",The room and the facilities are perfect.,France,Couple
11,2024-04-25,7.0,de,Disliked: Our room was very dated and urgently needs renovation.,"Very good location for exploring the city, good breakfast.",Switzerland,Couple

In [41]:
managerial_df = pd.DataFrame(
    agent_context[
        "managerial_evidence"
    ]
)

display(
    managerial_df[
        [
            "area",
            "positive_mentions",
            "negative_mentions",
            "net_mentions",
            "positive_share",
            "negative_share",
            "has_expectation_violation",
            "is_emerging_negative",
            "evidence_pattern",
        ]
    ]
)

,area,positive_mentions,negative_mentions,net_mentions,positive_share,negative_share,has_expectation_violation,is_emerging_negative,evidence_pattern
0,Breakfast,34,16,18,0.680,0.320,False,False,predominantly_positive
1,Restaurant and bar,20,13,7,0.606,0.394,True,True,positive_with_friction
2,Price–value,6,12,-6,0.333,0.667,True,True,net_negative
3,Room comfort,8,11,-3,0.421,0.579,False,False,net_negative
4,Bathroom condition,5,9,-4,0.357,0.643,True,False,net_negative
5,Rooftop access,24,8,16,0.750,0.250,True,True,positive_with_friction
6,Staff and service,46,8,38,0.852,0.148,False,False,predominantly_positive
7,Cleanliness and housekeeping,14,5,9,0.737,0.263,True,False,positive_with_friction

In [42]:
vulnerabilities_df = pd.DataFrame(
    agent_context[
        "diagnostic_vulnerabilities"
    ]
)

display(
    vulnerabilities_df[
        [
            "area",
            "evidence_pattern",
            "positive_mentions",
            "negative_mentions",
            "negative_share",
            "has_expectation_violation",
            "is_emerging_negative",
            "diagnostic_score",
            "diagnostic_score_components",
        ]
    ]
)

,area,evidence_pattern,positive_mentions,negative_mentions,negative_share,has_expectation_violation,is_emerging_negative,diagnostic_score,diagnostic_score_components
0,Price–value,net_negative,6,12,0.667,True,True,24,"{'negative_frequency': 10, 'net_negative': 3, 'negative_share': 2, 'expectation_violation': 4, 'emerging_negative': 3, 'default_priority': 2}"
1,Bathroom condition,net_negative,5,9,0.643,True,False,20,"{'negative_frequency': 9, 'net_negative': 3, 'negative_share': 2, 'expectation_violation': 4, 'emerging_negative': 0, 'default_priority': 2}"
2,Restaurant and bar,positive_with_friction,20,13,0.394,True,True,17,"{'negative_frequency': 10, 'net_negative': 0, 'negative_share': 0, 'expectation_violation': 4, 'emerging_negative': 3, 'default_priority': 0}"
3,Room comfort,net_negative,8,11,0.579,False,False,16,"{'negative_frequency': 10, 'net_negative': 3, 'negative_share': 1, 'expectation_violation': 0, 'emerging_negative': 0, 'default_priority': 2}"
4,Rooftop access,positive_with_friction,24,8,0.250,True,True,15,"{'negative_frequency': 8, 'net_negative': 0, 'negative_share': 0, 'expectation_violation': 4, 'emerging_negative': 3, 'default_priority': 0}"
5,Cleanliness and housekeeping,positive_with_friction,14,5,0.263,True,False,11,"{'negative_frequency': 5, 'net_negative': 0, 'negative_share': 0, 'expectation_violation': 4, 'emerging_negative': 0, 'default_priority': 2}"

In [43]:
strengths_df = pd.DataFrame(
    agent_context[
        "strengths"
    ]
)

display(
    strengths_df
)

,area,positive_mentions,negative_mentions,positive_share,strength_type,has_expectation_violation,is_emerging_negative
0,Staff and service,46,8,0.852,clear_strength,False,False
1,Breakfast,34,16,0.680,clear_strength,False,False
2,Rooftop access,24,8,0.750,strength_with_friction,True,True
3,Cleanliness and housekeeping,14,5,0.737,strength_with_friction,True,False

In [44]:
complaints_df = pd.DataFrame(
    agent_context[
        "complaint_evidence"
    ]
)

display(
    complaints_df[
        [
            "review_date",
            "rating",
            "original_language",
            "complaint",
            "positive_context",
        ]
    ]
)

,review_date,rating,original_language,complaint,positive_context
0,2024-04-26,5.0,en-us,"Disliked: Reflecting on my stay at Hotel Mundial, there were several aspects that left me feeling underwhelmed. Firstly, the room and bathroom fell short of my expectations, with outdated furnishings and a cramped layout. The shower posed a safety concern due to its slippery floor and constant leakage, making it difficult to use comfortably. Additionally, the bedding arrangement, with two twin beds pushed together instead of a king bed as requested, was disappointing. The lack of amenities such as a steamer or iron further detracted from the overall comfort of the room. Despite the hotel's convenient location, the outdated facilities and lackluster amenities made it difficult for me to overlook these shortcomings. Overall, while there were some positive aspects to my stay, I found the hotel to be lacking in terms of value and comfort.","In terms of what I liked about Hotel Mundial, there were definitely some positives to highlight amidst the mixed experience. Firstly, the hotel's prime location stood out to me as a major advantage. Being close to many of Lisbon's main attractions and cities made exploring the area incredibly convenient. Additionally, the restaurant offered a picturesque view, and I particularly enjoyed the octopus salad we had for dinner. The abundance of breakfast choices was also a plus, even though I wished the quality of the food matched the variety. Finally, the staff were friendly and accommodating, which added a welcoming touch to our stay."
1,2024-05-08,6.0,en-us,Disliked: Not value for money. For the money you pay you'd expect at least a free bottle of water in the room. Breakfast is below average. Hotel is old and is a bit outdated. Doesn't have enough facilities (ex: Gym),Location is very central. Beds are comfortable and shower was good. Staff were great and very helpful!
2,2024-04-30,6.0,de,Disliked: A hotel that has seen better days and is in urgent need of renovation. The rooms are worn and you simply don't feel comfortable. Cleanliness also leaves much to be desired. Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.,The hotel stands out for its location and the beautiful rooftop terrace.
3,2024-04-23,6.0,de,"Disliked: Stairs made of black stone. The edge is barely visible… potentially dangerous! It should be painted a light color. Large, many guests, breakfast has a high noise level, crowding 😰 The reception is often hectic as well.",Location
4,2024-05-12,6.0,da,Disliked: It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.,The location
5,2024-04-29,6.0,en,Disliked: Wait time with bar staff sometimes considerably long in the lounge bar,Roof top bar and location
6,2024-05-19,7.0,nl,Disliked: The bathroom is dated. If you're a bit taller you cannot sit properly on the toilet. You shower in the bathtub (which is very slippery). If you're a bit taller you don't fit well under the showerhead. There were two holes in the floor (drains?). As a result there was a sewer smell in the bathroom. We solved this by placing the bath mat over the two covers. Given the price of the room this should not happen.,The staff are more than friendly and helpful. You really feel welcome as a guest. The breakfast is excellent. The upstairs restaurant is also worth it. The hotel is located close to public transport. No request or effort is too much. Every day a bottle of water was placed in the room.
7,2024-04-26,7.0,en-us,"Disliked: The fact that we tried numerous times to get a table at the Rooftop bar and got nowhere. In my opinion, preference should be given to guests that actually stay in the hotel and not to the public. One of the main reasons we chose this hotel was the Rooftop bar. Room service was non existent.","We loved the location. We loved the spacious sunny balcony. The complimentary bottle of wine and Portuguese pastry was a nice touch. And front office staff were informative, efficient and friendly."
8,2024-04-29,7.0,en-us,"Disliked: The room did not seem really clean- the carpet had hairs- like pet hair- on it, bath towels were worn and had holes in them.staff were not super knowledgeable and gave us wrong advice on dinner(said no reservations allowed ) and timing to get to train station by taxi.","Fantastic location, corner room on upper level had nice views. Comfortable bed"
9,2024-05-07,7.0,it,"Disliked: Room cleaning was not adequate, the bathroom is dated and needs renovation. The bathtub drain was not working. Overall not up to the standard of a 4-star!","Excellent location, convenient for transport services and for reaching the various areas of the city. However, the hotel's entrance is located on a poorly frequented square. Very rich and abundant breakfast. Friendly staff."
10,2024-05-14,7.0,fr,"Disliked: Too much noise at night, rooms are very poorly soundproofed. The breakfast lacks regional specialties.",The room and the facilities are perfect.
11,2024-04-25,7.0,de,Disliked: Our room was very dated and urgently needs renovation.,"Very good location for exploring the city, good breakfast."

# Decision_Agent

In [62]:
import importlib
import src.decision_agent

importlib.reload(
    src.decision_agent
)

from src.decision_agent import (
    run_decision_agent
)

In [63]:
decision = run_decision_agent(
    agent_context
)

In [64]:
decision[
    "overall_risk"
]

'moderate'

In [65]:
print(
    decision[
        "executive_summary"
    ]
)

Hotel Mundial shows clear strengths in staff/service and breakfast, and the rooftop remains a valued asset. However, four clusters require managerial attention: (1) bathroom safety and usability (urgent); (2) guest perception of price–value (review and alignment); (3) rooftop/restaurant access and reservations (preserve strength while resolving access friction); and (4) room condition and housekeeping (assess renovation need and housekeeping processes). A fifth, lower-priority item concerns bar service wait times and night-time noise/soundproofing. Recommendations emphasize inspection, policy/process review, and targeted operational fixes; where the evidence implies possible capital scope (room/bathroom renovation) we recommend assessment before committing investment.

In [66]:
priorities_df = pd.DataFrame(
    decision[
        "priorities"
    ]
)

display(
    priorities_df[
        [
            "rank",
            "area",
            "evidence_pattern",
            "managerial_priority",
            "intervention_type",
            "problem",
            "recommended_action",
            "safety_relevance",
            "requires_further_assessment",
            "confidence",
        ]
    ]
)

,rank,area,evidence_pattern,managerial_priority,intervention_type,problem,recommended_action,safety_relevance,requires_further_assessment,confidence
0,1,Bathroom condition (safety & usability),net_negative,urgent,mixed,"Multiple guests report slippery bathtub/shower surfaces, leaking/sloped showers, broken drains/holes, sewer smell and shower height issues; at least one report describes a potentially dangerous slippery floor.","Immediately inspect recently-reported rooms and public bathrooms for slipping hazards, leaks, blocked or damaged drains, and floor openings; implement urgent remediation where safety hazard is confirmed (temporary anti-slip mats/signage, repairs). Concurrently, audit bathroom amenities (toiletries, functioning drains, showerheads). If inspection suggests structural/renovation needs, commission a technical assessment to scope required capital work.",True,True,0.88
1,2,Price–value perception,net_negative,high,policy_process,"A notable share of guests perceive the stay as 'overpriced' given room condition and included amenities (water, parking). Expectation violations and emerging negative topic 'overpriced' are present.","Review pricing and value positioning relative to room condition and included guest amenities. Audit what is communicated and included (e.g., complimentary water, parking policy) and compare to guest expectations; consider updating promotional messaging, inclusions, or packaging if misalignment is confirmed. If pricing is to be maintained, strengthen value communication and on-property inclusions to reduce expectation gap.",False,True,0.76
2,3,Rooftop / Restaurant & bar access and reservations,positive_with_friction,high,policy_process,"Guests value the rooftop and rooftop restaurant/bar but report difficulties reserving tables, long wait times, and feeling that non-guests are prioritized over hotel guests, causing expectation violations despite overall positive sentiment for the rooftop.","Review rooftop access and reservation policies to ensure alignment with guest expectations and commercial objectives. Evaluate whether guest-priority access, reservation allocation, or clearer communication about rooftop availability and reservation procedures is appropriate. Improve front-desk and F&B coordination about reservations and guest guidance. Monitor wait times at peak periods and adjust operational staffing/queues as needed.",False,False,0.78
3,4,"Room condition, cleanliness and housekeeping",mixed,high,mixed,"Multiple guests describe dated rooms, worn furnishings, noisy rooms/poor soundproofing, and inconsistent housekeeping quality (carpet hairs, worn towels, inadequate cleaning). Some comments question whether current room standards match a 4-star positioning.","Short term: audit housekeeping processes, laundry/towel quality and room-cleaning checks to address immediate cleanliness lapses. Medium term: commission a condition assessment of room finishes and soundproofing to determine scope and cost of renovation or targeted refresh (prioritize bathrooms where safety issues were also reported). Use findings to align room category descriptions and pricing with actual condition or to plan refurbishment.",False,True,0.73
4,5,Bar service wait times & night-time noise / soundproofing,positive_with_friction,medium,operational,Guests report long wait times for bar service and problems with night-time noise due to poor soundproofing; these friction points reduce enjoyment of on-site F&B and room rest.,"Operationally review F&B staffing/peak-service procedures to reduce lounge/bar wait times and improve guest flow. Short-term actions could include queue management and clearer communication on expected wait. For noise complaints, perform a targeted assessment of soundproofing in frequently-complained rooms and, where feasible, deploy interim guest-facing mitigations (earplugs, room allocation guidance) while planning medium-term improvements.",False,False,0.62

In [67]:
for priority in decision[
    "priorities"
]:
    print("=" * 80)

    print(
        f"#{priority['rank']} "
        f"{priority['area']}"
    )

    print()

    print("EVIDENCE BASIS")
    print(
        json.dumps(
            priority[
                "evidence_basis"
            ],
            indent=2,
            ensure_ascii=False,
        )
    )

    print()

    print("SUPPORTING EVIDENCE")

    for evidence in priority[
        "supporting_evidence"
    ]:
        print(
            "-",
            evidence
        )

    print()

    print("POSITIVE COUNTEREVIDENCE")

    for evidence in priority[
        "positive_counterevidence"
    ]:
        print(
            "-",
            evidence
        )

    print()

================================================================================
#1 Bathroom condition (safety & usability)

EVIDENCE BASIS
{
  "positive_mentions": 5,
  "negative_mentions": 9,
  "expectation_violation": true,
  "emerging_negative": false,
  "experience_weeks": 0,
  "expectation_weeks": 1,
  "violated_expectation_weeks": 1,
  "emerging_negative_weeks": 0,
  "review_examples_used": 4,
  "relevant_trend_signals": [
    "emerging_negative_topic: shower experience",
    "emerging_negative_topic: toilet comfort",
    "matched diagnostic: Bathroom condition net_negative"
  ]
}

SUPPORTING EVIDENCE
- 2024-04-26: 'The shower posed a safety concern due to its slippery floor and constant leakage.'
- 2024-05-19: 'bathtub (which is very slippery)... there were two holes in the floor (drains?)... sewer smell in the bathroom.'
- 2024-05-07: 'The bathtub drain was not working.'
- Multiple managerial_evidence entries: Bathroom condition — 14 mentions (5 positive, 9 negative), evidence_pattern net_negative; has expectation violation = true.

POSITIVE COUNTEREVIDENCE
- Some reviews note overall positives (staff, location, breakfast) despite bathroom issues; a few guests still report adequate showers (managerial_evidence shows some positive mentions).

================================================================================
#2 Price–value perception

EVIDENCE BASIS
{
  "positive_mentions": 6,
  "negative_mentions": 12,
  "expectation_violation": true,
  "emerging_negative": true,
  "experience_weeks": 0,
  "expectation_weeks": 1,
  "violated_expectation_weeks": 1,
  "emerging_negative_weeks": 1,
  "review_examples_used": 4,
  "relevant_trend_signals": [
    "emerging_negative_topic: overpriced",
    "EXPECTATION_EXPERIENCE_GAP_AVG increasing (diagnostic signal)"
  ]
}

SUPPORTING EVIDENCE
- Managerial_evidence: Price–value — 18 mentions (6 positive, 12 negative), evidence_pattern net_negative; has_expectation_violation = true; emerging_negative = true.
- 2024-05-08: 'Not value for money... For the money you pay you'd expect at least a free bottle of water in the room.'
- 2024-05-12: 'It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.'
- 2024-04-26: 'Overall... found the hotel to be lacking in terms of value and comfort.'

POSITIVE COUNTEREVIDENCE
- Strong F&B and service positives (breakfast, staff, rooftop experience) that could be emphasized in value communication.

================================================================================
#3 Rooftop / Restaurant & bar access and reservations

EVIDENCE BASIS
{
  "positive_mentions": 24,
  "negative_mentions": 8,
  "expectation_violation": true,
  "emerging_negative": true,
  "experience_weeks": 4,
  "expectation_weeks": 1,
  "violated_expectation_weeks": 1,
  "emerging_negative_weeks": 1,
  "review_examples_used": 3,
  "relevant_trend_signals": [
    "EMERGING_NEGATIVE_TOPIC: access to rooftop bar/restaurant",
    "Restaurant and bar managerial_evidence: positive_with_friction"
  ]
}

SUPPORTING EVIDENCE
- Managerial_evidence: Rooftop access — 29 mentions (24 positive, 8 negative), evidence_pattern positive_with_friction; has_expectation_violation = true; is_emerging_negative = true.
- 2024-04-26: 'We tried numerous times to get a table at the Rooftop bar and got nowhere... preference should be given to guests that actually stay in the hotel.'
- 2024-04-30: 'Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.'
- 2024-04-29: 'Wait time with bar staff sometimes considerably long in the lounge bar.'

POSITIVE COUNTEREVIDENCE
- High positive share for rooftop (positive_mentions 24 / 29) — rooftop remains a valued strength when access works.

================================================================================
#4 Room condition, cleanliness and housekeeping

EVIDENCE BASIS
{
  "positive_mentions": 22,
  "negative_mentions": 16,
  "expectation_violation": true,
  "emerging_negative": false,
  "experience_weeks": 4,
  "expectation_weeks": 1,
  "violated_expectation_weeks": 1,
  "emerging_negative_weeks": 0,
  "review_examples_used": 4,
  "relevant_trend_signals": [
    "diagnostic: Room comfort net_negative",
    "EXPECTATION_EXPERIENCE_GAP_AVG increasing",
    "complaints referencing 'dated' rooms and poor soundproofing"
  ]
}

SUPPORTING EVIDENCE
- Managerial_evidence: Room comfort — 19 mentions (8 positive, 11 negative), evidence_pattern net_negative.
- Managerial_evidence: Cleanliness and housekeeping — 18 mentions (14 positive, 5 negative), evidence_pattern positive_with_friction; has_expectation_violation = true.
- 2024-04-26: 'the room and bathroom fell short... outdated furnishings and a cramped layout.'
- 2024-04-29: 'room did not seem really clean- the carpet had hairs... bath towels were worn and had holes in them.'
- 2024-05-07: 'Room cleaning was not adequate, the bathroom is dated and needs renovation.'
- 2024-04-25: 'Our room was very dated and urgently needs renovation.'
- 2024-05-14: 'Too much noise at night, rooms are very poorly soundproofed.'

POSITIVE COUNTEREVIDENCE
- Several guests praise the breakfast, staff helpfulness, and some guests report comfortable beds and nice views, indicating parts of the guest experience remain strong.

================================================================================
#5 Bar service wait times & night-time noise / soundproofing

EVIDENCE BASIS
{
  "positive_mentions": 20,
  "negative_mentions": 13,
  "expectation_violation": true,
  "emerging_negative": true,
  "experience_weeks": 4,
  "expectation_weeks": 1,
  "violated_expectation_weeks": 1,
  "emerging_negative_weeks": 1,
  "review_examples_used": 2,
  "relevant_trend_signals": [
    "EMERGING_NEGATIVE_TOPIC: cocktails / bar wait",
    "complaints referencing poor soundproofing"
  ]
}

SUPPORTING EVIDENCE
- 2024-04-29: 'Wait time with bar staff sometimes considerably long in the lounge bar.'
- 2024-05-14: 'Too much noise at night, rooms are very poorly soundproofed.'
- Managerial_evidence: Restaurant and bar — mixed positive_with_friction pattern; rooftop and bar show both strong positives and operational friction.

POSITIVE COUNTEREVIDENCE
- Rooftop and restaurant are overall positive attractions (high positive mentions) when access and service function well.

In [68]:
monitoring_df = pd.DataFrame(
    decision[
        "monitoring_indicators"
    ]
)

display(
    monitoring_df[
        [
            "indicator",
            "reason",
            "desired_direction",
            "monitoring_horizon",
        ]
    ]
)

,indicator,reason,desired_direction,monitoring_horizon
0,EXPECTATION_EXPERIENCE_GAP_AVG,"Has increased over the lookback and signals widening gap between what is promised/expected and delivered; relevant to price–value, room condition and rooftop access.",decrease,short_term
1,SEMANTIC_MISALIGNMENT_SCORE_AVG,Rising misalignment suggests marketing/communication may not match actual guest experience (relevant to rooftop access and price/value messaging).,decrease,short_term
2,SENTIMENT_SCORE_AVG,Overall sentiment trended down over the window (with recent reversal); track for deterioration or improvement after interventions.,increase,ongoing
3,"Frequency of bathroom-related complaints (slippery, leaks, drains, sewer smell)",Directly tracks safety/usability priority—immediate remediation should reduce these mentions.,decrease,immediate
4,Mentions of 'overpriced' / price-value complaints,Tracks perception of value and effectiveness of pricing/communication changes.,decrease,short_term

In [69]:
strengths_decision_df = pd.DataFrame(
    decision[
        "strengths_to_preserve"
    ]
)

display(
    strengths_decision_df
)

,area,reason,management_implication
0,Staff and service,"High positive mentions (46 positive, positive_share 0.852). Multiple reviews praise friendly, helpful, and welcoming staff—this is a clear strength.",Maintain service standards and recognition/training programs; ensure front-desk and F&B staff have clear processes for reservations and guest prioritization to avoid undermining this strength.
1,Breakfast,"Strong positive signal (34 positive mentions, positive_share 0.68) and repeated guest praise for abundant choices.",Preserve breakfast variety and quality; consider minor adjustments if specific regional specialties are requested (monitor feedback).
2,Rooftop (asset),High positive sentiment for rooftop terrace and restaurant (24 positive mentions); perceived as a differentiator and reason guests book.,Protect rooftop guest experience by resolving access/reservation friction and ensuring F&B service consistency so the rooftop continues to deliver positive impact.

In [70]:
monitoring_df = pd.DataFrame(
    decision[
        "monitoring_indicators"
    ]
)

display(
    monitoring_df
)

,indicator,reason,desired_direction,monitoring_horizon
0,EXPECTATION_EXPERIENCE_GAP_AVG,"Has increased over the lookback and signals widening gap between what is promised/expected and delivered; relevant to price–value, room condition and rooftop access.",decrease,short_term
1,SEMANTIC_MISALIGNMENT_SCORE_AVG,Rising misalignment suggests marketing/communication may not match actual guest experience (relevant to rooftop access and price/value messaging).,decrease,short_term
2,SENTIMENT_SCORE_AVG,Overall sentiment trended down over the window (with recent reversal); track for deterioration or improvement after interventions.,increase,ongoing
3,"Frequency of bathroom-related complaints (slippery, leaks, drains, sewer smell)",Directly tracks safety/usability priority—immediate remediation should reduce these mentions.,decrease,immediate
4,Mentions of 'overpriced' / price-value complaints,Tracks perception of value and effectiveness of pricing/communication changes.,decrease,short_term

# A - BASELINE FREQUENCY

In [76]:
import importlib
import src.baseline_frequency

importlib.reload(
    src.baseline_frequency
)

from src.baseline_frequency import (
    run_frequency_baseline
)

In [77]:
frequency_decision = (
    run_frequency_baseline(
        agent_context
    )
)

In [78]:
frequency_df = pd.DataFrame(
    frequency_decision[
        "priorities"
    ]
)

display(
    frequency_df
)

,rank,area,managerial_domain,managerial_priority,negative_mentions,positive_mentions,negative_share,rationale
0,1,Breakfast,food_and_beverage,high,16,34,0.3200,Breakfast was ranked #1 because it contains 16 negative review mentions.
1,2,Restaurant and bar,food_and_beverage,medium,13,20,0.3939,Restaurant and bar was ranked #2 because it contains 13 negative review mentions.
2,3,Price–value,pricing_and_value,medium,12,6,0.6667,Price–value was ranked #3 because it contains 12 negative review mentions.
3,4,Room comfort,rooms_and_maintenance,low,11,8,0.5789,Room comfort was ranked #4 because it contains 11 negative review mentions.
4,5,Bathroom condition,rooms_and_maintenance,low,9,5,0.6429,Bathroom condition was ranked #5 because it contains 9 negative review mentions.

# B - GENERIC PIPELINE

In [81]:
import importlib
import src.baseline_generic_llm

importlib.reload(
    src.baseline_generic_llm
)

from src.baseline_generic_llm import (
    build_generic_context,
    run_generic_llm_baseline,
)

In [82]:
generic_context = (
    build_generic_context(
        case,
        max_reviews=12,
    )
)

print(
    json.dumps(
        generic_context,
        indent=2,
        ensure_ascii=False,
    )
)

{
  "case": {
    "case_id": null,
    "decision_week": null,
    "decision_date": null,
    "window_start": null,
    "window_end": null
  },
  "hotel": {},
  "basic_performance": {
    "REVPAR_WEEK": {
      "first_value": 137.79088647884825,
      "last_value": 154.48296533177387,
      "percentage_change": 12.114065944040469
    },
    "REVPOR_WEEK": {
      "first_value": 211.5028830434784,
      "last_value": 261.13567753001746,
      "percentage_change": 23.466722425876398
    },
    "TREVPAR_WEEK": {
      "first_value": 183.41268953229107,
      "last_value": 209.317862853041,
      "percentage_change": 14.123980945271041
    },
    "TAXA_OCUPACAO": {
      "first_value": 89.11174785100286,
      "last_value": 87.39255014326648,
      "percentage_change": -1.929260450160766
    },
    "AVG_RATING": {
      "first_value": 8.808510638297872,
      "last_value": 8.575,
      "percentage_change": -2.650966183574878
    },
    "N_REVIEWS": {
      "first_value": 47.0,
      "last_value": 40.0,
      "percentage_change": -14.893617021276595
    }
  },
  "recent_customer_reviews": [
    {
      "review_date": "2024-04-26",
      "rating": 5.0,
      "complaint": "Disliked: Reflecting on my stay at Hotel Mundial, there were several aspects that left me feeling underwhelmed. Firstly, the room and bathroom fell short of my expectations, with outdated furnishings and a cramped layout. The shower posed a safety concern due to its slippery floor and constant leakage, making it difficult to use comfortably. Additionally, the bedding arrangement, with two twin beds pushed together instead of a king bed as requested, was disappointing. The lack of amenities such as a steamer or iron further detracted from the overall comfort of the room. Despite the hotel's convenient location, the outdated facilities and lackluster amenities made it difficult for me to overlook these shortcomings. Overall, while there were some positive aspects to my stay, I found the hotel to be lacking in terms of value and comfort.",
      "positive_context": "In terms of what I liked about Hotel Mundial, there were definitely some positives to highlight amidst the mixed experience. Firstly, the hotel's prime location stood out to me as a major advantage. Being close to many of Lisbon's main attractions and cities made exploring the area incredibly convenient. Additionally, the restaurant offered a picturesque view, and I particularly enjoyed the octopus salad we had for dinner. The abundance of breakfast choices was also a plus, even though I wished the quality of the food matched the variety. Finally, the staff were friendly and accommodating, which added a welcoming touch to our stay.",
      "country": "United States",
      "stay_type": "Couple"
    },
    {
      "review_date": "2024-05-08",
      "rating": 6.0,
      "complaint": "Disliked: Not value for money. For the money you pay you'd expect at least a free bottle of water in the room. Breakfast is below average. Hotel is old and is a bit outdated. Doesn't have enough facilities (ex: Gym)",
      "positive_context": "Location is very central. Beds are comfortable and shower was good. Staff were great and very helpful!",
      "country": "United Kingdom",
      "stay_type": "Couple"
    },
    {
      "review_date": "2024-04-30",
      "rating": 6.0,
      "complaint": "Disliked: A hotel that has seen better days and is in urgent need of renovation. The rooms are worn and you simply don't feel comfortable. Cleanliness also leaves much to be desired. Access to the beautiful rooftop terrace should always be guaranteed for hotel guests.",
      "positive_context": "The hotel stands out for its location and the beautiful rooftop terrace.",
      "country": "Germany",
      "stay_type": "Couple"
    },
    {
      "review_date": "2024-04-23",
      "rating": 6.0,
      "complaint": "Disliked: Stairs made of black stone. The edge is barely visible… potentially dangerous! It should be painted a light color. Large, many guests, breakfast has a high noise level, crowding 😰 The reception is often hectic as well.",
      "positive_context": "Location",
      "country": "Switzerland",
      "stay_type": "Solo traveller"
    },
    {
      "review_date": "2024-05-12",
      "rating": 6.0,
      "complaint": "Disliked: It was too expensive for what you got; it should probably be a 3-star hotel if you only looked at the rooms.",
      "positive_context": "The location",
      "country": "Denmark",
      "stay_type": "Group"
    },
    {
      "review_date": "2024-04-29",
      "rating": 6.0,
      "complaint": "Disliked: Wait time with bar staff sometimes considerably long in the lounge bar",
      "positive_context": "Roof top bar and location",
      "country": "United Kingdom",
      "stay_type": "Group"
    },
    {
      "review_date": "2024-05-19",
      "rating": 7.0,
      "complaint": "Disliked: The bathroom is dated. If you're a bit taller you cannot sit properly on the toilet. You shower in the bathtub (which is very slippery). If you're a bit taller you don't fit well under the showerhead. There were two holes in the floor (drains?). As a result there was a sewer smell in the bathroom. We solved this by placing the bath mat over the two covers. Given the price of the room this should not happen.",
      "positive_context": "The staff are more than friendly and helpful. You really feel welcome as a guest. The breakfast is excellent. The upstairs restaurant is also worth it. The hotel is located close to public transport. No request or effort is too much. Every day a bottle of water was placed in the room.",
      "country": "Netherlands",
      "stay_type": "Couple"
    },
    {
      "review_date": "2024-04-26",
      "rating": 7.0,
      "complaint": "Disliked: The fact that we tried numerous times to get a table at the Rooftop bar and got nowhere. In my opinion, preference should be given to guests that actually stay in the hotel and not to the public. One of the main reasons we chose this hotel was the Rooftop bar. Room service was non existent.",
      "positive_context": "We loved the location. We loved the spacious sunny balcony. The complimentary bottle of wine and Portuguese pastry was a nice touch. And front office staff were informative, efficient and friendly.",
      "country": "Malaysia",
      "stay_type": "Couple"
    },
    {
      "review_date": "2024-04-29",
      "rating": 7.0,
      "complaint": "Disliked: The room did not seem really clean- the carpet had hairs- like pet hair- on it, bath towels were worn and had holes in them.staff were not super knowledgeable and gave us wrong advice on dinner(said no reservations allowed ) and timing to get to train station by taxi.",
      "positive_context": "Fantastic location, corner room on upper level had nice views. Comfortable bed",
      "country": "United States",
      "stay_type": "Couple"
    },
    {
      "review_date": "2024-05-07",
      "rating": 7.0,
      "complaint": "Disliked: Room cleaning was not adequate, the bathroom is dated and needs renovation. The bathtub drain was not working. Overall not up to the standard of a 4-star!",
      "positive_context": "Excellent location, convenient for transport services and for reaching the various areas of the city. However, the hotel's entrance is located on a poorly frequented square. Very rich and abundant breakfast. Friendly staff.",
      "country": "Italy",
      "stay_type": "Family"
    },
    {
      "review_date": "2024-05-14",
      "rating": 7.0,
      "complaint": "Disliked: Too much noise at night, rooms are very poorly soundproofed. The breakfast lacks regional specialties.",
      "positive_context": "The room and the facilities are perfect.",
      "country": "France",
      "stay_type": "Couple"
    },
    {
      "review_date": "2024-04-25",
      "rating": 7.0,
      "complaint": "Disliked: Our room was very dated and urgently needs renovation.",
      "positive_context": "Very good location for exploring the city, good breakfast.",
      "country": "Switzerland",
      "stay_type": "Couple"
    }
  ]
}

In [83]:
generic_decision = (
    run_generic_llm_baseline(
        case,
        max_reviews=12,
    )
)

In [84]:
generic_df = pd.DataFrame(
    generic_decision[
        "priorities"
    ]
)

display(
    generic_df[
        [
            "rank",
            "area",
            "managerial_priority",
            "action_horizon",
            "intervention_type",
            "problem",
            "recommended_action",
            "safety_relevance",
            "requires_further_assessment",
            "confidence",
        ]
    ]
)

,rank,area,managerial_priority,action_horizon,intervention_type,problem,recommended_action,safety_relevance,requires_further_assessment,confidence
0,1,"Guest safety in wet/uneven areas (bathrooms, stairs)",urgent,immediate,maintenance,"Multiple reviewers reported slippery showers and bathtub surfaces, leaking showers, poorly visible black-stone stair edges and holes/drains in bathroom floors creating slip and trip hazards and sewer smell.","Conduct an immediate property-wide safety inspection of all bathrooms and public stairways. Implement temporary mitigations at once: anti-slip bath mats and adhesive non-slip strips in tubs/showers, clear signage where surfaces are slippery, temporary covers/guards for exposed holes/drains, install high-visibility nosing/strips on stair edges, and close or restrict any room or public area with severe hazards until repaired. Commission prioritized repairs for leaking showers, faulty drains and permanent anti-slip surfacing; schedule plumbing trades to resolve drainage/sewer issues.",True,True,0.90
1,2,Room and bathroom condition / renovation,high,medium_term,capital_assessment,"Numerous guests describe rooms and bathrooms as dated, cramped or worn (old furnishings, worn towels, poor bathroom layout and low shower head), which affects comfort and star-standard expectations.","Commission a condition survey and costed phased refurbishment plan prioritizing bathrooms (drains, showerheads, anti-slip surfacing, plumbing), mattresses and bedding configuration (ability to provide requested king beds rather than pushed twins), worn soft goods replacement (towels, carpets where needed), and room layout improvements where feasible. Use a phased rollout to avoid taking large room blocks offline at once; prioritize rooms with the worst reviews and those used for higher rate segments.",True,True,0.85
2,3,Housekeeping and cleanliness standards,high,short_term,operational,"Several reviews note inadequate room cleaning (carpet hairs, worn towels, inconsistent bathroom cleanliness and non-working drains), leading to perceptions of poor hygiene and lower guest satisfaction.","Perform an immediate housekeeping standards audit (spot checks across room types and floors). Retrain staff on cleaning checklists, focusing on carpets, towel inspection/replacement, bath/tub drains and odor control. Institute shift handover inspections, daily room audits with scoring, and a rapid response protocol for guest cleanliness complaints. Replace worn towels and damaged linens as a short-term investment. Track corrective action closure times.",False,True,0.85
3,4,Rooftop bar/terrace access and food & beverage service capacity,medium,short_term,policy_process,"Guests report difficulty getting rooftop bar tables (public given priority over hotel guests), long wait times at the lounge bar, and inconsistent room service — causing frustration because the rooftop is a key reason guests choose the hotel.",Implement a guest-priority policy for the rooftop (reserve a percentage of seating or a guest-only booking window). Introduce a simple reservation path for hotel guests at check-in and via the hotel app/concierge. Assess peak staffing levels at the rooftop/bar and adjust staffing or service processes to reduce wait times. Clarify and publicize room service availability and service standards at check-in.,False,True,0.70
4,5,"Value perception, amenities and pricing alignment",medium,medium_term,policy_process,"Multiple guests feel the hotel does not deliver value for the price paid (requests for basic inclusions like bottled water, complaints that facilities are limited, no gym), and some rate the breakfast below expectations despite others praising it.","Conduct a simple competitive benchmarking exercise to confirm star positioning and price parity. Consider low-cost amenity changes that improve perceived value: complimentary bottled water in rooms (where inconsistent), offering basic in-room iron/steamer on request or a loaner program, and reviewing breakfast menu to include a few regional specialties. Communicate clearly at booking/confirmation what is included to set expectations. Adjust rates or packaging where appropriate (e.g., 'city location & rooftop' premium vs economy room offerings).",False,True,0.70

In [85]:
print(
    generic_decision[
        "executive_summary"
    ]
)

Recent guest reviews consistently praise the hotel's location, rooftop views and friendly staff but highlight recurring problems: bathroom safety and drainage issues, outdated rooms needing renovation, inconsistent cleanliness/housekeeping, crowding and access problems at the rooftop/bar and perception of poor value for price. Immediate actions should address documented safety hazards and housekeeping; medium-term work should plan phased bathroom/room refurbishment and align pricing/amenities. Preserve strong location, rooftop asset, restaurant and staff responsiveness while monitoring guest ratings, safety incidents, housekeeping audit scores and rooftop guest access metrics.

In [86]:
pd.DataFrame(
    generic_decision[
        "strengths_to_preserve"
    ]
)

,area,reason,management_implication
0,Location,"Multiple reviews highlight the hotel's prime, central location and convenience for transport and attractions.","Leverage location in marketing, ensure concierge and front desk maintain strong local knowledge and transport guidance; prioritize refurb works to preserve guest access and minimize disruption."
1,Rooftop terrace and restaurant views,Guests repeatedly cite the rooftop terrace and upstairs restaurant (views and food) as standout positives.,"Protect rooftop as a guest-facing asset (see priority 4), maintain F&B quality and atmosphere while improving access control for guests."
2,Staff friendliness and service attitude,"Many guests praise friendly, helpful staff and front office efficiency.",Continue staff training and recognition programs; leverage staff strength during periods of change to maintain guest goodwill.
3,Breakfast offering (abundance/variety),"Several reviews praise abundant and excellent breakfast, even where some guests found it below average.",Maintain core breakfast variety while addressing quality and adding regional items selectively.